### ISSUE TITLE
Wurst extension command >runmap not work with project generated with git CLI, works with Wurst GUI

### ISSUE THREAD

**Issue by bertman12** [wurstscript/WurstScript#1002]
**Describe the bug**
ProjectName(s): wurst-practice-project-1; wurst-test-projecy
Generated a new wurst project with Git CLI using (grill generate myProjectName)
I used "code ." command in the Git CLI to open a new vscode workspace in the project root directory.
All project files created, but wurst.build file generated an empty object.
vscode was unable to perform any of the runmap functions provided by the wurst extension. 

Project Name: wurstPracticeProject2
I made a second wurst project but this time using the wurst GUI. Project was generated successfully. The wurst.build file was populated with properties about the project this time.
The runmap command worked, compiling the hello.wurst file and creating a new window for the test map printing "Hello World".

Both instances the wurst extension was confirmed to be running by checking the dev console in vscode. I'm unsure the cause of this issue. I attempted manually populating the wurst.build object myself but it did not fix the error.

Windows 10
Wurst compiler build: 1273
Wurst Language Support vscode extension v0.5.10
Node.JS v14.15.4
npm v6.14.10
openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment (build 12.0.2+10)
OpenJDK 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)
![wurst-extension-error](https://user-images.githubusercontent.com/31266442/120764569-1f747e00-c4cd-11eb-81a5-7ace755859a9.PNG)

[Language Server Logs](https://pastebin.com/1x67G7RE)
[Compiler Logs](https://pastebin.com/AmHJikHq)
No vscode output generated.

 * Include the steps required to reproduce the bug (e.g. a small code example or a link to your project code)
 * Pastbin and link the `compiler` and `languageServer` logs from `~/.wurst/logs/` (~ refers to your user's home directory)
 * Copy and paste the VSCode Output (CTRL + SHIFT + U) for `wurstLanguageServer` (drop down menu) into a code fence (```)

**Comment by Frotty** [comment]
> I used "code ." command in the Git CLI to open a new vscode workspace in the project root directory.

This sounds wrong. You should open the project root as a folder.

**Comment by bertman12** [comment]
I tried doing that as well after using the grill generate command. It still won't allow the runmap command. I am just using the GUI now to create projects. Not sure why I'm having an issue using runmap after making a project with the grill generate command but if I find more information I will update this thread.

**Comment by Frotty** [comment]
I justed tested it and it works. 
Your issue is probably that you set the game path in the setup which `grill generate` does not.
If it can not be detected you need to specify it in settings.json like `"wurst.wc3path": "C:\\Games\\Warcraft III\\_retail_\\x86_64"`.
Should probably add a filechooser for this.

**Comment by bertman12** [comment]
Thank you, this does work. I have a question that is off this topic but do you happen to know what language JASS is based from?
