### ISSUE TITLE
Is it possible to set imported loading screen in wurst.build?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#1028]

**Comment by Frotty** [comment]
Yes, you can see the according properties in included schema, which also provides suggestions.
![image](https://user-images.githubusercontent.com/1486037/131827970-dfe327d2-803b-48de-a53f-12397d18bec7.png)

**Comment by GetLocalPlayer** [comment]
Nothing pops up for me. Did I forget to install something specific?

**Comment by Frotty** [comment]
grill install to get the wurst.build schema
