### ISSUE TITLE
Please help me java.lang.NullPointerException

### ISSUE THREAD

**Issue by q531620267** [wurstscript/WurstScript#1030]
i just use war3 1.27 create a new project, run map,vs code show An exception was thrown when running the map: java.lang.NullPointerException .Thank you very much
![Y}V5@8ML{F~_Z5@$4YLENFV](https://user-images.githubusercontent.com/22743869/136254550-bcaaba63-6ecf-4389-8b38-6a0d6d08f039.png)

**Comment by Frotty** [comment]
Most likely you didn't follow the setup guide correctly (open folder, not workspace).
In any case, 1.27 isn't natively supported, you will need to do some custom setup.

**Comment by q531620267** [comment]
> 请您共享Wurst日志文件好吗？
> 
> * 并链接`compiler`和`languageServer`原木`~/.wurst/logs/`(~指用户的主目录)
> * 复制和粘贴VSCode输出(CTRL+Shift+U)`wurstLanguageServer`(下拉菜单)进入代码围栏(``‘)
[compiler.log](https://github.com/wurstscript/WurstScript/files/7296587/compiler.log)

[languageServer.log](https://github.com/wurstscript/WurstScript/files/7296590/languageServer.log)

Loading Wurst version 1.8.1.0-jenkins-Wurst-1315
initialization done!

**Comment by q531620267** [comment]
oh ,god
![image](https://user-images.githubusercontent.com/22743869/136269275-e15be0e5-0539-4a6b-bbce-abecb13c36c2.png)

**Comment by q531620267** [comment]
i fix it :dancing_men: 
https://github.com/wurstscript/WurstStdlib2/tree/pre1.29
