### ISSUE TITLE
Why are there so many lines of code after compilation

### ISSUE THREAD

**Issue by fbicirno** [wurstscript/WurstScript#1058]
Using triggers to make the same map, 
the number of lines of jass code is 50,000, 

and the number of lines of jass code in my wurst map has reached 300,000 lines, 

how to reduce the number of lines of code?
Will the number of lines of code affect the game lag or efficiency?

**Comment by Frotty** [comment]
Because a lot of code is being generated.

> Will the number of lines of code affect the game lag or efficiency?

No
