### ISSUE TITLE
Use w3x2lni to speed up compilation

### ISSUE THREAD

**Issue by fbicirno** [wurstscript/WurstScript#1059]
Here is the project ： https://github.com/sumneko/w3x2lni
**I think this tool can make wurst compile much faster**

I planned a feasible compilation process：

> 1. Run w2l.exe by command line to convert map to lnI folder format
> 2. Run wurst build map to compile the code into compiled j.txt
> 3. compiled j.txt Add to lnimapFolder\map\war3map.j
> 4. Add **[compiled objects]** to lnimapfolder\table\* ini
> 5. Add **[imports]** to lnimapfolder\resource\
> 6. Run w2l.exe converts lnI to obj
> 7. Map obj to_ In the build folder
> 8. all done!

**Comment by Frotty** [comment]
Thanks for the suggestion. However the w3x2lni project mainly offers conversion between slk and objmod files. This is not required in the wurst build and we already have our own toolchain [wc3libs](https://github.com/inwc3/wc3libs) to do these things. You can add the slk conversion as a custom step in vscode if you so desire.
The objmod generation is not a time critical task during compilation, so there would be no performance gain to be expected here anyway. But you can supply your values using the `-measure` arg.
