### ISSUE TITLE
Sometimes wurst built an unrunnable map.

### ISSUE THREAD

**Issue by cloudfox2** [wurstscript/WurstScript#1071]
Sometimes wurst built an unrunnable map (It crashes at loading), but sometimes it built successful with the same code. Reboot VSCode or computer won't change the situation.

Seem the jass part has some issues, if I replace the jass file to a runnable version, the map can run too. I can't find the specific issue, the jass can pass the syntax check.
It should not be any specific wurst code issue, since sometimes it can success.

I never met the issue before, it appeared these weeks. Seem success rate becomes lower and lower while my code becomes bigger, and it is down to zero now. If I checkout my code to some old version, it can success everytime. I really don't know what's the problem.

**Comment by cloudfox2** [comment]
My longest function in jass has 24 params.

**Comment by cloudfox2** [comment]
Seems it is due to a big recursive function. It has 6000+ lines in jass. I made some adjustment to cut it to 4000+ lines and it can run now.

**Comment by Frotty** [comment]
sounds like oplimit then? Usually shouldn't crash unless it's executed at map start or so. Should probably avoid recursion in most cases.

**Comment by cloudfox2** [comment]
I don't have such a big function in my code and I can't really understand that jass function, is wurst compiling override functions into one function? Its name is cyc_xxx.

**Comment by Frotty** [comment]
To follow up: Yes, to resolve cyclic functions, wurst puts them in one big function. Consider resolving your cycles to avoid this.
