### ISSUE TITLE
Can Wurst be upgraded to jdk17?

### ISSUE THREAD

**Issue by fbicirno** [wurstscript/WurstScript#1078]
Can Wurst be upgraded to jdk17?
The performance of jdk8 seems to have reached the upper limit.

### **For shorter compilation time and faster performance!**

**Comment by Frotty** [comment]
Do you have any evidence to back up those claims?
You can run wurst with a newer JRE, which should be most of the potential performance improvements. I don't see how compiling wurst with a newer JDK without any code changes would affect performance much if it all.

**Comment by fbicirno** [comment]
> Do you have any evidence to back up those claims? You can run wurst with a newer JRE, which should be most of the potential performance improvements. I don't see how compiling wurst with a newer JDK without any code changes would affect performance much if it all.

Sorry, I'm just guessing

**Comment by Frotty** [comment]
You can upgrade your system JDK which is used for Wurst to the latest version (21) to gain some performance.
Regarding general performance issues, you should add `-measure` to your `wurst_run.args` file and paste the results from the output tab. Do you have `-compiletimeCache` enabled?
I am in the process of making some small performance improvements with the latest commit and #1080, but don't expect any major gains for big projects. Wurst simply does a lot of stuff which isn't easily optimized, and therefore will require a long build time for big code bases.
