### ISSUE TITLE
hey, im looking for Skills ID for unique abilities of some niche races and units and Night Elf lady from campain that helps Maiev

### ISSUE THREAD

**Issue by SCARaw** [wurstscript/WurstScript#1091]
as in topic

sorry if i use this feature wrong, i m getting desperate xD

**Comment by Frotty** [comment]
Spells from the campaigns are custom, they don't have an ID that you can just take as base. The only way would probably be to open the campaigns and extract the spells from there. In any case, I don't see how this has anything to do with Wurst. Seems more fitting to ask in a discord server.
