### ISSUE TITLE
Remove cyclic dependencies between functions

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#154]
By creating one big function with an extra parameter to distinguish the functions.

**Comment by Cokemonkey11** [comment]
@peq is there documentation somewhere that explains how to use this?

There is no information about limitations of `ExecuteFunc` in the Wurst manual.

**Comment by peq** [comment]
ExecuteFunc can only be used with static strings. It is statically checked whether the function exists. 

For cyclic dependencies between functions you don't have to do anything, it just works and you can look at the compiled output to see how.

**Comment by Cokemonkey11** [comment]
Okay, so what's the best way to execute callback functions in Wurst?

**Comment by peq** [comment]
I think objects/closures work best:

http://peq.github.io/WurstScript/manual.html#lambda-expressions-and-closures

In some cases it might be more efficient to use Conditions/triggers, but
closures should be the default choice for callbacks.
