### ISSUE TITLE
Add static inner classes

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#213]
Especially needed in modules, e.g. to declare an iterator for the linkedlist module

**Comment by peq** [comment]
Started working on this in b96d0f7db9706a5c4f2a57212207f6147ea2dd97. First static inner classes have to work, before I can start with dynamic ones.

**Comment by peq** [comment]
[Note to self] 
Still required:

- accessing outer scopes (including checks about which elements can be accessed from a static context)
- qualified names for types etc.
- qualified names in constructors
- change meaning of `thistype` in inner classes or add a way to access thistype of outer class?

**Comment by Crigges** [comment]
Here are some thoughts about accessing the outer class from the inner one:
Java style:
```
class Outer
    class Inner
        function foo()
            Outer.thistype
```
I think this style is problematic here are modules since they don't represent a type.
Maybe a new keyword refering to the outer scope like "outer" can solve this problem:
```
class Outer
    class Inner
        function foo()
            outer.thistype
            outer.this              //for nonstatic inner classes
```
Iam not convinced by this solution either, since the name of keyword is to general to be a keyword.

**Comment by peq** [comment]
The most important thing is already working: Iterators for linked list modules (https://github.com/peq/WurstScript/blob/988ea843c09ca1c7951f18660c708ebbe63b6c78/Wurstpack/wurstscript/lib/data%20structures/LinkedListModule.wurst#L48-L76)

All the qualified names stuff and actually using the inner classes like normal classes is not yet working.

**Comment by Frotty** [comment]
👍

**Comment by Frotty** [comment]
> All the qualified names stuff and actually using the inner classes like normal classes is not yet working.

What's the status on this?

**Comment by peq** [comment]
I would say the main use case (iterator class in module) works, so we can close this and create a new issue if more features are required.
