### ISSUE TITLE
Get Class Names

### ISSUE THREAD

**Issue by Crigges** [wurstscript/WurstScript#234]
There shoud be a possibilty to get the classname of class.

The most easy syntax is:
--ClassName.toString()
or
--ClassName.name
or
--ClassName.getName()

It can also be done like in java, so more featues can be added easily:
Class obj = ClassName.getClass()
obj.getTypeId()
obj.getName()
--Optional--
obj.getSuperClass()
obj.getSubClasses() returns a list ob class objects
obj.getXYZ()
...

**Comment by Cokemonkey11** [comment]
:+1:
