### ISSUE TITLE
where to place unit tests of the standarlib?

### ISSUE THREAD

**Issue by Ruk33** [wurstscript/WurstScript#345]
i updated OnUnitEnterLeave/UnitIndexer code and added some tests to ensure certain functionality but where should i place this tests?

```
package OnUnitEnterLeaveTest

import Assert
import OnUnitEnterLeave

unit tmp = null
unit eventUnit = null
boolean enterFired = false
boolean leaveFired = false

function onEnterTest()
    eventUnit = getEnterLeaveUnit()
    n(getEnterLeaveUnit().getAbilityLevel('!e@$'), 0)
    enterFired = true

function onLeaveTest()
    BJDebugMsg("leave fired") // i know, high test tech ( / º3º)/
    e(tmp, getEnterLeaveUnit())

init
    onEnter(function onEnterTest)
    onLeave(function onLeaveTest)

    tmp = CreateUnit(GetLocalPlayer(), 'hfoo', 0, 0, 0)

    a(enterFired, "Enter event didn't fired")
    e(tmp, eventUnit) // we do it like this, because code event gets fired first and then assignment

    tmp.remove()
    //a(leaveFired, "Leave event didn't fired") // can't since this line is going to be executed first than any onLeave code
```

i was thinking on path/to/lib/tests/<same structure of the package>/<package-name>Test.wurst

in this case would be lib/tests/systems/OnUnitEnterLeaveTest.wurst

**Comment by peq** [comment]
Good question. If it is possible to test it with unit tests, then I would put the unit tests in the same module. If you have something like here, were you want to test the interaction within the game, I would not put it into the standard library directly. 

Maybe a good way would be to have it in a comment at the beginning of the file, because this test is also a good way to show how to use the library. And if someone wants to run your tests, he can just copy the code from the comment.

**Comment by Ruk33** [comment]
i don't think place tests in comments would be a good idea, if you want to run them you have to create the file, if you want to edit them, you have to also create the file, its kinda unorthodox (at least for me)

**Comment by Cokemonkey11** [comment]
In the case of `Knockback3` and `LinkedHashMap` I provide demo maps which might have some FV tests.

https://github.com/Cokemonkey11/knockback3-demo

https://github.com/Cokemonkey11/linked-hashmap-demo

I think this ticket is about convention, but I don't see much value in documenting it.

@peq if you'd like this documented I can write something in `gh-pages`.

**Comment by peq** [comment]
You mean documentation for the 2 libraries? Just add comments to the source code.

**Comment by Cokemonkey11** [comment]
In this case I am talking about demo or FV (large) tests, which don't belong in the library because they will be more detailed.

**Comment by Frotty** [comment]
outdated. Tests are named `package_name`+Tests.wurst and ignored from autocomplete.
At some point we could think about moving them all into a different folder.
