### ISSUE TITLE
No documentation for using vjass maps with wurst compiler

### ISSUE THREAD

**Issue by blakehawkins** [wurstscript/WurstScript#349]
I recall seeing an explanation somewhere of how to use wurst with an existing vjass project - extracting all the vjass triggers into wurst packages and compiling via wurst, but the manuals don't contain info on this.

Such a nice feature should be documented.

**Comment by Cokemonkey11** [comment]
whoops, I keep accidentally posting here with my other alias - this is me

**Comment by peq** [comment]
This is an experimental feature together with Jurst, but I agree that there should be some documentation.

**Comment by Cokemonkey11** [comment]
It seems to work quite well. One suggestion would be to write something in wurst console when beginning/ending the process successfully. I thought the feature was broken until I refreshed my project.

**Comment by Cokemonkey11** [comment]
@peq I'm happy to look at this week. I'm thinking that a section could be added to gh-docs branch which includes a short explanation of:

* how wurst behaves when compiling a map with existing vjass triggers
* how the 'extract to jurst' feature works and some steps to use it

Let me know if this sounds good and I'll get on it.

**Comment by peq** [comment]
Sounds good. Although the extract to Jurst feature is not yet included in vscode. Just don't put too much effort in explaining eclipse specific things.

**Comment by Frotty** [comment]
I think this is properly addressed now (tutorials on side and on hive)
