### ISSUE TITLE
DISBTN linking for optimizer

### ISSUE THREAD

**Issue by muzzel** [wurstscript/WurstScript#371]
This might be a nice feature to add to the optimizer:
http://www.hiveworkshop.com/forums/lab-715/getting-rid-disbtn-some-theorycrafting-267199/

**Comment by peq** [comment]
Detecting equivalent files and merging them in the MPQ? Or automatically generating DISBTN if it is not present?

**Comment by Crigges** [comment]
Neither i guess,  DISBN buttons are in most cases useless and just cost filesize. So the idea is that the mpq editor creates a pointer to the normal button for the DISBN button. This violates a few mpq concepts i guess but it should work fine.

**Comment by muzzel** [comment]
What crigges wrote.
Its a nice way to reduce filesize.

**Comment by peq** [comment]
What Crigges wrote sounds like automatically adding the DISBTN if not present, right? And because of this trick this would not increase the file size.

**Comment by Cokemonkey11** [comment]
Pointing DISBTN paths to BTN icons will cause all DISBTNs to look like BTNs, is that correct?

This will make your icons look silly when the menu is open. When you open an in-game menu, only DISBTNs are shown in the UI.

If you have a mix of DISBTNs and BTNs it will look like shit. If you have only BTNs it will still look silly.

**Comment by Frotty** [comment]
The DISBTN generation could be added to wc3libs and then used in Wurst.
The original idea however doesn't really make sense, as discussed.
I am closing this stale issue and opened https://github.com/inwc3/wc3libs/issues/53 .
