### ISSUE TITLE
Integrate muzzels Doodadmaker into Wurstpack

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#375]
https://github.com/muzzel/DoodadMaker

@muzzel wants to do some changes, before it is ready.

One idea to integrate it would be to integrate it into Wurstpack as an external tools and make it launchable similar to the grimext-tools.

**Comment by Crigges** [comment]
I think it shouldn't be part of the compiler. Just like the importtool. Maybe i will try to add a extra tab with thoose tools.
We still need a better java launcher for the editor.

**Comment by Cokemonkey11** [comment]
What is the point of compiletime doodads if doodads cannot be placed during runtime?

Or is this meant to be an alternative to the doodad object editor?

**Comment by peq** [comment]
The point is to make it easier to import models. Just put the models in a folder, use DoodadMaker to get the Wurst files which generate the object-editor doodads. Then you can adjust the code, if you want a different scale or so.

**Comment by Cokemonkey11** [comment]
Makes sense. :+1:

**Comment by Frotty** [comment]
muzzel is probably not gonna finish it?

**Comment by Frotty** [comment]
iirc muzzel didn't finish it and also wurstpack is deprecated anyway.
Closing.
