### ISSUE TITLE
New Java Launcher

### ISSUE THREAD

**Issue by Crigges** [wurstscript/WurstScript#376]
I createt some simple java launcher which works as following:

API: launcher.exe "pathtojar"

At first start it trys to start a dummy jarfile with the standard java -jar command if the jars runs successful this configuration is saved in the registry, otherwise it will ask you for a installed jre or gives you the option to download java: http://snag.gy/XKZI4.jpg

If you select a new jre it is testet again.  Once a sucessful configuration was found it is saved in the regsitry. 

What do you think about it?

**Comment by Cokemonkey11** [comment]
Without context I can only guess that this is related to Wurstpack, to aid initial configuration. Is that correct?

**Comment by peq** [comment]
Yes, on some systems the current launcher makes problems. Especially if there are two different versions of Java installed or the wrong version.

**Comment by Cokemonkey11** [comment]
I like this then :+1: but I think the GUI needs context information for non-programmers.

"Wurstpack depends on Java 8, but could not find it." or something similar.

**Comment by Crigges** [comment]
I just updated the launcher and added some features. The launcher waits now until the jre exits and if a error occurs the launcher will print it via message: 
![You killed the sausage :(](http://snag.gy/QQxcS.jpg)
Maybe I could support the error report feature that wurstscript is already using, I would just need some more information about it.

Here is the link to the repo:
https://github.com/Crigges/JavaLauncher

Here the downloadlink for the executable:
https://github.com/Crigges/JavaLauncher/raw/master/WindowsFormsApplication1/bin/Release/WindowsFormsApplication1.exe

**Comment by peq** [comment]
If you want to add the error-reporting, you can look at https://github.com/peq/WurstScript/blob/master/de.peeeq.wurstscript/src/de/peeeq/wurstio/ErrorReportingIO.java#L143
The PHP script to handle the requests can be found here: https://github.com/peq/peeeq.de-php/blob/master/wursterrors.php

Another question: Does the launcher require the .Net runtime to be installed, or can it also be compiled to a real standalone executable? If it requires .Net: how does Wurstpack behave if it is not installed?

**Comment by Frotty** [comment]
replaced by https://github.com/wurstscript/wurst-jar-wrapper
