### ISSUE TITLE
Import of TypeCasting is marked as unused, although it is used

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#381]
It is only used implicitly for generics, so Wurst thinks it is unused.

**Comment by Frotty** [comment]
:+1:

**Comment by Cokemonkey11** [comment]
As I understand, TypeCasting is imported by default. Is this only related to packages that `NoWurst`?

**Comment by peq** [comment]
Yes, and also own type casting functions you might have in different packages.

**Comment by Frotty** [comment]
Not longer an issue because we auto import it in stdlib.
