### ISSUE TITLE
Jurst global sized arrays are not supported

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#403]
In vJass, the following is valid:

```
library Example
    globals
        integer array sized[12]
    endglobals
endlibrary
```

And, for sizes less than 8192, this is semantically equivalent to:

```
library Example
    globals
        integer array sized
    endglobals
endlibrary
```
- vJass provides no bounds checking
- The dynamic sizing nature of `sized` is unchanged from vanilla jass

In general this feature is for large-sized arrays, as vjass supports the following:

```
library Example2
    globals
        integer array bigSized[9000]
    endglobals

    function test takes nothing returns nothing
        set bigSized[8500] = 42
        call BJDebugMsg(I2S(bigSized.size))
    endfuncton
endlibrary
```

This feature is rarely used as
- large, statically-allocated arrays are a code smell
- getting the size of a statically sized array promotes poor code quality - consider the following:

```
integer array foos[9000]
set q = foos.size

// vs

constant integer FOOS_MAX = 9000
integer array foos[FOOS_MAX]
set q = FOOS_MAX
```

However, I consider specifying the size of global arrays good vJass, for two reasons:

```
// Consistency with static struct members.
globals
    integer array sizeDoesNothing[12]
endglobals

struct SizeIsImportant
    static integer array bar[12]
endstruct
```

```
// Describes the author's intent programmatically, as 12 is
// clearly related to the number of players in the map.
unit array playerHeros[12]

// vs

unit array playerHeros
```

As a result, sized global arrays are quite common in my vJass, and I am in the process of migrating some vJass maps to Jurst. Therefore I propose one of two options. Either:
- Change the Eclipse "Extract scripts to files" feature so that it automatically drops the dead sizes from sized global arrays, or
- Allow sized global arrays in Jurst, even if they do nothing.

To be clear, I'm not interested in big arrays or the `.size` member, I just think that converting from vJass to Jurst should be as user-friendly as possible.

Related: #399

**Comment by Cokemonkey11** [comment]
@peq what was the result of this further discussion?

**Comment by Frotty** [comment]
Jurst is deprecated
