### ISSUE TITLE
Code problem: The method xxx is undefined for receiver of type Void

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#405]
Hello,

I'm trying to use a functional interface as a callback function in order to replace some legacy `ExecuteFunc` code with a wursty one.

Here are the two (quite long) packages in question:

[Muscii](http://peeeq.de/code.php?id=9048) (library)

[Music](http://peeeq.de/code.php?id=9049) (client)

The error occurs in Muscii line 196. Best guess is that
- I'm doing something wrong, _and_
- Jurst isn't behaving quite right here.

Excuse me if there's a glaring bug in the code :)

**Comment by peq** [comment]
Seems to be a parser problem in Jurst. It will parse the statement as 
`(destroy m).cbf`. If you put explicit parameters as in `destroy 
(m.cbf)`, it will look like a function call to Jurst, so the only option 
you have at the moment (until it is fixed) is to use a separate variable.

**Comment by Cokemonkey11** [comment]
Using a variable worked - I'll let you decide what to do with this ticket because I guess it's a minor parsing error

**Comment by Cokemonkey11** [comment]
@peq just a reminder that I think you planned to schedule this as a bugfix

**Comment by Frotty** [comment]
still valid?

**Comment by Cokemonkey11** [comment]
Dunno but I've started translating to wurst instead of using jurst at all for the most part.

I suspect this is still a bug (best guess)

**Comment by peq** [comment]
Not sure if there are still any users of the Jurst syntax, so closing this.
