### ISSUE TITLE
Wurst Dependency Management

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#418]
Had a discussion with Frotty this morning. Here is a document with some thoughts: https://docs.google.com/document/d/1Oh1HQ400ZzQTWTQ5uzEAhxhzn13lbxpVcWWoteHEdQs/edit?usp=sharing

Comments are still welcome.

**Comment by Cokemonkey11** [comment]
I think this deserves some context.

What are wurst dependencies? What is included?

* third party plugins
* third party wurst
* the standard library
* the newgen fork

etc.

**Comment by peq** [comment]
A dependency can consist of source code (.wurst, .jurst) and imports. The standard library would not be a dependency, but if we had a dependency manager, we could make the standard library much slimmer and have most of the current standard library as managed dependencies.

**Comment by blakehawkins** [comment]
I've added some comments. Flag me if unclear.

**Comment by Cokemonkey11** [comment]
I've added some comments. Flag me if unclear.

(whoops, wrong account again)

**Comment by Anchorist** [comment]
I'm taking this one: https://github.com/Anchorist/WurstDependencyManager

**Comment by peq** [comment]
@Anchorist Can you share a plan of what you want to implement? The setup tool already provides basic functionality for managing dependencies.

**Comment by Anchorist** [comment]
I'm basing on composer (php dependency manager) notation and golang dependency naming.

`ketch init` would create wurst repository (pull latest compiler and stdlib)
`ketch up` would update all dependencies in scope of stability level
`ketch require <github repo>:<ver>`  would add library to project dependency list and pull it

`<ver>` would be release at github, with possible override by prefixing version with `dev-<branch-name>`

I think dependency manager could be alternative or be used with setup tool

I took `ketch` name from doc, but I was more into `grill` or `bbq`

**Comment by Cokemonkey11** [comment]
can `<ver>` also match git SHA hashish?

**Comment by Anchorist** [comment]
No, but git SHA will be stored inside lock file

**Comment by Cokemonkey11** [comment]
I think you should add support for `ketch require <github repo>:<hashish>`

**Comment by Anchorist** [comment]
You think about full hash or just first 8 chars?

**Comment by Cokemonkey11** [comment]
https://stackoverflow.com/a/23303550/1669576

**Comment by Frotty** [comment]
we have non-transitive dep management for some time now.
