### ISSUE TITLE
Editor-support: error positions off-by-one on Windows

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#448]

**Comment by Cokemonkey11** [comment]
@peg I haven't experienced this. Guessing this is an old vscode bug?

**Comment by peq** [comment]
Ask frotty, it never works for him, no matter what I do :)

**Comment by Frotty** [comment]
I sent you a screenshot via icq, you created this ticket and then marked it as done i guess.

**Comment by peq** [comment]
So are the positions correct for you now?

**Comment by Frotty** [comment]
iirc i didnt even report one line off, instead spaces get appended to the error pos and errors overlap.

![image](https://cloud.githubusercontent.com/assets/1486037/17852238/741c91f4-6866-11e6-96a0-4ca8339c71b8.png)

**Comment by peq** [comment]
I still have to figure out, how to control the information in the hover window. Currently it shows all errors in some order and the usual hover info. It should not show the normal hover info, when there is an error.

The other problems are not so bad in my opinion. You should not use spaces at the end of lines anyway. Overlapping errors are a bit strange of course, especially if the outer one is a consequence of the inner one. That could be improved a bit.

**Comment by Frotty** [comment]
This is also a funny one 
![image](https://cloud.githubusercontent.com/assets/1486037/17863058/5c450476-6898-11e6-9112-586e5ddf7735.png)

And yes, it's not critical by any means.

**Comment by Frotty** [comment]
seems good for now
