### ISSUE TITLE
Optimization: CyclicFunctionRemover should remove maximal cycle

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#465]
In CyclicFunctionRemover a random cycle is chosen and then eliminated. If a function appears in many cycles, this can lead to complicated generated code,like:

```
function cyc_cyc_cyc_cyc_error takes integer funcChoice, integer funcChoice_2, integer funcChoice_3, integer funcChoice_4, string msg, integer loglvl, string msg_2, player showTo, integer loglvl_2, string msg_3 returns nothing
```

It looks like this can be done better ;)

**Comment by Crigges** [comment]
Maybe use binary search for the function choice for further optimization.

**Comment by peq** [comment]
I don't get your suggestion. How does binary search help with finding a maximal cycle? 

Do you want to help implementing this?

**Comment by Crigges** [comment]
You got me wrong srry. For me it looks like sometimes a lot of functions get merged into one and afaik the right function is determinated by using simple if statments:
```
function cyclic(int func)
	if func == 1
		//func1
	else if func == 2
		//func2
    else if func == 3
		//func3
	else 
		//func4
```
We could use binary search instead, just like for dynamic dispatch:
```
function cyclic(int func)
	if func <= 2
		if func == 1
			//func1
		else
			//func2
    else 
		if func == 3
			//func3
		else 
			//func4
```
