### ISSUE TITLE
re: predicates, This is a bug in the wurst compiler. Please Report it.

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#468]
![image](https://cloud.githubusercontent.com/assets/1418966/17096563/dd7226d0-5251-11e6-9c6a-adbe8d7ef735.png)

And here is code:

http://peeeq.de/code.php?id=28305&key=5795daf963e5a6.49806397

**Comment by Cokemonkey11** [comment]
@Frotty care to triage?

**Comment by peq** [comment]
This is probably related to #490
