### ISSUE TITLE
In lambdas with generic variable, [type]toIndex is not reverted

### ISSUE THREAD

**Issue by BlueSaint** [wurstscript/WurstScript#490]
Sorry if this is reported already, but I couldn't find it at least. Also the dialog told me to report this problem.
Example:

```
interface TFunc<T>
    abstract function run(T t)

function runFunc(TFunc<bool> func)
    func.run(false)

init
    runFunc( (bool b) -> begin
    end )
```

Gives error when compiling from WE. Doesn't give one when I use Run from Eclipse, but throws to main menu (guess no PJass check there?).

```
function dispatch_TFunc_run takes integer this, integer t returns nothing
    call closure_impl(this, t) // cannot convert integer to boolean
endfunction

function runFunc takes integer func returns nothing
    call dispatch_TFunc_run(func, booleanToIndex(false)) // boolean is converted to integer
endfunction
```

**Comment by peq** [comment]
It's a bug, but fixing this is not so easy at the moment. I am planning to rewrite the handling of generics some time, which would also fix this case.

If you need this for something important, I could add a quick and dirty workaround, but I would prefer to have a clean solution some time, as there are some other problems with the toIndex and fromIndex functions.

**Comment by BlueSaint** [comment]
Nah I'd rather have the clean solution, so I'm open to waiting. Thanks for acknowledging this.

**Comment by BlueSaint** [comment]
I'd actually like the quick and dirty workaround, sorry I didn't know the time scope was months...

**Comment by peq** [comment]
I'll probably have some time to look at it this week or on the weekend.

**Comment by Cokemonkey11** [comment]
@peq any progress on this?

**Comment by peq** [comment]
Seems to be fixed by some other change
