### ISSUE TITLE
Add compiletime expressions

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#499]
Syntax: `compiletime(expr)` where expr is an arbitrary expression.

Semantics: The expression will be evaluated at compiletime and the result of evaluation replaces the compiletime-expression.

Example:

```
constant int mybuff = compiletime(createBuff("Wurstified", "path\\to\\icon"))

function createBuff(string name, string icon) returns int
    int id = generateNewId()
    // object generation code
    return id
```

Open question (@Frotty):

Should it be possible to instantiate classes and have the objects still exist at runtime? For example `compiletime(new Buff(...))`.

**Comment by Frotty** [comment]
regarding the question, I suppose yes? `if compiletime` should still work inside `createBuff` olr not?

**Comment by Frotty** [comment]
is this done?

**Comment by peq** [comment]
Documentation is still missing.
