### ISSUE TITLE
Fix ambiguous references from same package

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#501]
Like this:
![image](https://cloud.githubusercontent.com/assets/1486037/21885163/bcd1390c-d8b6-11e6-83de-b393fae06b9f.png)

**Comment by peq** [comment]
@Frotty can you check if this change helps? You need to update vscode and the wurstscript.jar

**Comment by Frotty** [comment]
Nope
![image](https://cloud.githubusercontent.com/assets/1486037/21995624/24ef5d44-dc26-11e6-9953-d2ece1fcb7e9.png)

**Comment by peterzeller** [comment]
Ok, but now it is really referencing to the same path for both "alternatives". Strange.

**Comment by peq** [comment]
Ok, but now it is really referencing to the same path for both 
"alternatives". Strange.

**Comment by Frotty** [comment]
why do you add the same twice

**Comment by peq** [comment]
Actually, it always removes the old one before adding the new one, so I 
don't know how this can happen :D

**Comment by Frotty** [comment]
What information do you need? This happens _very often_ a fix would be nice.

**Comment by Frotty** [comment]
This still happens in some cases, but the original cause (BufferManager) got fixed. Will open a new ticket once we have reproducible steps.
