### ISSUE TITLE
Add compilerflag to convert binary OE-data to SLKs

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#513]
So the map loads much more quickly.
Since the compilation already is very time consuming, saving time on the map load would be ideal.

**Comment by Cokemonkey11** [comment]
@Frotty I think you've completed this?

**Comment by Frotty** [comment]
no

**Comment by karlek** [comment]
What's OE-data and SLKs?

**Comment by Frotty** [comment]
oe-data is the objmod data the object editor creates (.w3a .w3u etc.)
Most of these can be represented in non-binary formats slk/txt which are way faster read and loaded.

**Comment by PhoenixZeng** [comment]
maybe should provide a argument in wurst_run.args(like -converttoslk)
not always
If this is implemented

**Comment by Frotty** [comment]
obviously?

**Comment by Frotty** [comment]
not really a wurst task and too unstable to be commonly used. closing.

**Comment by PhoenixZeng** [comment]
u can use with the other cli-application to do this.
i use the `w3x2lni`
u can find it on github

**Comment by Frotty** [comment]
Cool, I can also use MPQ Editor, and world editor, and vJass.
But I don't want to, and we want to use native code.
Makes sense?
