### ISSUE TITLE
Discussion: Global Wurst config?

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#531]
e.g. in user home like many other programs.
Then the vscode plugin doesn't need an extra config and the wurstupdater will refer to same version.
later this could be used to store managed dependencies, maybe also logs.

**Comment by peq** [comment]
Makes sense. Do you want to implement this?

**Comment by Frotty** [comment]
I will need it for the setup, so eventually yes. But if you want to do it because I take too long that's fine too. 🌴

**Comment by Frotty** [comment]
Now exists inside `~/.wurst`
