### ISSUE TITLE
Put wurst project configuration and map info into one file

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#532]
Similar to a build gradle, but use an existing sheme like yaml or Json.
Next to the contents of wurst.dependencies (ideally with git repo support) it should contain things that can only added via the scenario editor right now, like ingame-mapname, description, loadingscreen etc.

wurst_run.args could probably stay separated since it might change, but args for the release task could also be specified here.

I'm planning to build a bare-bone version of this with wc3libs. I don't know how far you were with dependency management @peq and if you still want to finish it /are against a minimal solution.

**Comment by peq** [comment]
You can check the branch `dependencyManagement` for the dependency management stuff. What I did is all in this folder: https://github.com/peq/WurstScript/tree/dependencyManagement/de.peeeq.wurstscript/src/de/peeeq/wurstio/deps

The main thing I did were some tests with the Git library to checkout dependencies.

I think a minimal version is a good idea. If possible try to make it so, that we can add things later.

**Comment by Frotty** [comment]
we have `wurst.build` now.
