### ISSUE TITLE
Move wursty projects into a GitHub organisation "Wurst"

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#534]

**Comment by Frotty** [comment]
I see no point in this

**Comment by Cokemonkey11** [comment]
To find all the wursty projects, and only the wursty projects

**Comment by Frotty** [comment]
Okay, it is useful for the same reason as the inwc tools - more than one user has access to the repository settings.
Additionally if we split stdlib, wurstpack and maybe the docs size into different repos it will be more organized, but in different people's profiles. A Wurst group to find all content in one place then gets useful as well.
