### ISSUE TITLE
Interface checker freaks out at an overloaded function even if a properly implemented function exists

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#547]
So, I noticed this:

```
public class BaseAttributeBonus implements Bonus
    private int attr 
    private string name
    
    construct(string name, int attr)
        this.name = name
        this.attr = attr

    function apply(unit u, real val)
        apply(UnitBonus.of(u, this), val)

    function apply(UnitBonus unitBonus, real val)
        var total = GetHeroStatBJ(attr, unitBonus.getUnit(), false)
        var baseAttr = total - unitBonus.getVal() 
        var newAttr = baseAttr + val

        SetHeroStat(unitBonus.getUnit(), attr, newAttr.toInt())
        unitBonus.setVal(val)

    function add(unit u, real val)
        let unitBonus = UnitBonus.of(u, this)
        apply(unitBonus, unitBonus.getVal() + val)
```

As you can see, the function apply can take both UnitBonus and unit as the first parameter. However, the interface only has signature for apply(unit, real).

```
public interface  Bonus
    function apply(unit u, real val)
    function add(unit u, real val)
```

In this case, the interface checker will say nothing - because it checks from top to bottom, so it saw that I have implemented a function with the signature apply(unit, real). So far so good.

But if I do this:

```
public class BaseAttributeBonus implements Bonus
    private int attr 
    private string name
    
    construct(string name, int attr)
        this.name = name
        this.attr = attr

    function apply(UnitBonus unitBonus, real val)
        var total = GetHeroStatBJ(attr, unitBonus.getUnit(), false)
        var baseAttr = total - unitBonus.getVal() 
        var newAttr = baseAttr + val

        SetHeroStat(unitBonus.getUnit(), attr, newAttr.toInt())
        unitBonus.setVal(val)

    function apply(unit u, real val)
        apply(UnitBonus.of(u, this), val)

    function add(unit u, real val)
        let unitBonus = UnitBonus.of(u, this)
        apply(unitBonus, unitBonus.getVal() + val)
```

I get an error. Basically, since the interface implementation is checked from top to bottom, it will freak out at the first function apply signature, because it takes UnitBonus as the first argument. It won't even look past that, to realize that there's a proper implementation of apply(unit, real), it'll instead tell me that I haven't met the signature standards of apply(unit, real).

So, what are the solutions here?
1) Make sure the whole class is checked before throwing premature errors when checking the implementation of an interface
2) Make it so that you can't overload functions that have signatures in the interface you're implementing

Personally I am all for solution 1) since it doesn't break anything, and the 2) is not a rule that should be randomly imposed to the user (even if it is rather bad coding practice to have something like this in your code to begin with).

I am not even going to have those functions with the same name in the end product, but as I was copying the function around, I figured out this bug. This is not an issue that anyone should have since you shouldn't overload functions randomly like this, but it is a bug none the less (considering that it acts differently depending on whether the 'properly' defined function is bellow or above the 'faulty' one).

So let's make this consistent.

**Comment by Frotty** [comment]
annoying, but unimportant and non-critical I would say

**Comment by IgorSamurovic** [comment]
"annoying, but unimportant and non-critical I would say."

Pretty much, this would fit into the "known bug but we do not really care" category because it is so niche.

"More importantly: Why haven't you been in irc lately?"

My university moved exams from 26th of august to 18th of august and I lost my shit because I essentially lost a week I have had to prepare some shit, so I am focused on that right now.

**Comment by Frotty** [comment]
Alright, thanks for the heads-up. Good luck on your exams.
