### ISSUE TITLE
Add feature to build map from commandline / vscode

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#550]
- [x] It should be possible to build the map from the commandline or from vscode. The compiled map should be stored in the `build` folder.
- [x] It should be possible to configure map author, loadingscreen, etc. via the `wurst.build` config file

See https://github.com/inwc3/wc3libs/blob/master/src/main/java/net/moonlightflower/wc3libs/bin/app/W3I.java

**Comment by peq** [comment]
referenced wrong ticket

**Comment by peq** [comment]
Collecting requirements ....

> Cokemonkey11: as a vscode user I should be able to run a releasemap target that compiles the map into a release directory with the right file name, map name, verion number, all without actually running wc3

**Comment by Frotty** [comment]
Both features are now implemented, but wurst.build still needs restructure and more attributes like recommended players and loading screen stuff.

**Comment by karlek** [comment]
Close this issue and open a new one for `wurst.build` restructuring?

**Comment by Frotty** [comment]
Yea should do
