### ISSUE TITLE
Wurst cannot parse newlines in strings, which is valid in Jass

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#553]
E.g.
```
call SetMapDescription("Creator: Vadik29 |nTranslator: null |nDiscord:https://discord.gg/bBF4z8p |nMap Description: Choice Battle is based on choosing an Anime Character to fight against your enemy team in an Arena.  The game is based on rounds, that your team have to win. Everyone starts on Round 1, and whichever team that gets annihilated first, loses that round. When you've won up to a total of 15 rounds, you will then achieve Victory.|n
|n
After every round you will be rewarded with Gold, which you buy items with to either empower your own strength or the teams. The same goes to countering the enemy, so buy your items strategically!")
...
```
Throws errors

**Comment by peq** [comment]
Do we really want newlines in Strings? Either the indentation is messed up or you have a lot of whitespace in the String or you have some strange syntax rules.

```
init
	string s1 = "hello
world"
	string s2 = "hello
	world"
	string s3 = "hello
		world"
	string s4 = "hello
				 world"
```

I mean, which of these is allowed and which ones have weird whitespace at the beginning of the second line?

**Comment by Cokemonkey11** [comment]
Maybe allow it in jurst only?

FWIW I find rust's solution pretty nice - leading space on newline are ignored.

**Comment by Frotty** [comment]
I don't see the issue @peq ?
It's just for being able to parse Jass, which the Wurst grammar needs, not Jurst (to be able to parse war3map).
Wurst converts these newlines into \n\r, tabs are of course kept.

**Comment by peq** [comment]
I just would not allow them in Wurst, it is okay in Jass for compatibility.

**Comment by Frotty** [comment]
Okay I mixed it up, Jurst is enough to parse .j files, so I'm all for it.
See 8d5bcf5b59fb247f00b385de19a3ab0abe66c1b6
