### ISSUE TITLE
Error in File Baics.wurt line 26: java.io.FileNotFoundException: WurstExportedObjects_w3u.wurst.txt (Access is denied)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#556]
Wc3 starts and the map says "cannot load map data". Edit: Wc3 starts just fine but the wurst compiler still has the below error displayed.

![image](https://user-images.githubusercontent.com/1418966/31060446-1726ff3a-a70c-11e7-846c-b1d73dd61979.png)

Expected:

* better error message explaining the problem
* wc3 does not start if the compiler didn't complete successfully.

**Comment by Frotty** [comment]
Expected from a ticket:
- log

Seriously coke?
