### ISSUE TITLE
Compiler error trying to convert int to string (when it's clearly a string)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#560]
![image](https://user-images.githubusercontent.com/1418966/31412573-88d4e914-ae0d-11e7-9b03-87005edbd3f4.png)

This occurs with clean workspace.

**Comment by Cokemonkey11** [comment]
The problem is that `TowerDefinition` doesn't provide a constructor with 2 arguments. Can we catch this and give some nice errors?

**Comment by Cokemonkey11** [comment]
Nevermind, the above was indeed a bug, but the error still persists (even with clean workspace)

**Comment by Cokemonkey11** [comment]
@peq any idea..?

**Comment by Cokemonkey11** [comment]
Found the problem. `class TowerDefinition` needed to be public.

Is it possible to improve compiler error in this case?

**Comment by peq** [comment]
The bug occurs when executing compiletime functions. Actually the error should already be detected in the type-checking phase, if I see it correctly.

Can you give me a link to the code (minimal example or link to Git-repo + commit hash) so that I can see exactly what went wrong here?

**Comment by Cokemonkey11** [comment]
If you take this commit and remove the `public` from this line, you might trigger it:

https://bitbucket.org/Cokemonkey11/microrunnertd/src/a735a202558213e92889b69a3a8d537e1dbcc041/wurst/systems/definitions/TowerDefinition.wurst?at=master&fileviewer=file-view-default#TowerDefinition.wurst-4

But I'm too lazy to retest...
