### ISSUE TITLE
Merge repeated stacktrace lines

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#565]
Stacktraces are often bloated with duplicate lines.
Just Deleting them might lose valuable insight, so they should be displayed in 1 line with some sort of count indicator.

I'm not sure if this can be done in an efficient way, so I tagged it as discussion.

**Comment by Cokemonkey11** [comment]
Do you mean that there are duplicates from line `n` to line `n+1` ?

And which stack traces are you talking about - the code-generated ones that appear in game?

**Comment by Frotty** [comment]
Are there any other stacktraces?
And yes, e.g.
```
Entity Line 9
Entity Line 9
Entity Line 9
Buff Line 12
Buff Line 34
```

**Comment by peq** [comment]
The multiple lines are probably from artificial functions like dynamic
dispatch functions.

**Comment by Cokemonkey11** [comment]
> Are there any other stacktraces?

Yes, the wurst compiler for example has stack traces.

Since this is for debug messages, performance doesn't matter. Can just drop line by line into a list and then strip duplicates.

**Comment by Frotty** [comment]
> Yes, the wurst compiler for example has stack traces.

I trust you to use context to your advantage.

> performance doesn't matter

Not entirely true. As stacktraces grow big and therefore execute many ops, they can be the reason for hitting the oplimit, as was the case in EBR before they were backed by an array.

**Comment by Cokemonkey11** [comment]
> Not entirely true. As stacktraces grow big and therefore execute many ops, they can be the reason for hitting the oplimit, as was the case in EBR before they were backed by an array.

Hmm, don't we have some function for automatically making safe from op-limit? We at least talked about how this would work, of course.

**Comment by peq** [comment]
> Hmm, don't we have some function for automatically making safe from op-limit?

No.

> We at least talked about how this would work, of course.

Yes. I think the conclusion was that it is not possible to check at compile time and adding runtime support was not worth the effort to implement it and the impact it would have on performance.

I am closing this issue as I think it would be fixed by the changes proposed in https://github.com/wurstscript/WurstScript/issues/564
