### ISSUE TITLE
"angle" array in class

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#572]
```
class C
    angle array[2] ang
```
When above code compile, there will be translation error that wrote "can't make array type from array<real>"

I'm not sure if it is a bug, hence posted here for further clerify.

**Comment by Frotty** [comment]
It's a bug. arraymembers with tuple types don't seem to match. Will look into it.

**Comment by peq** [comment]
This is related to https://github.com/wurstscript/WurstScript/issues/364
