### ISSUE TITLE
Hot doc format issues with constructors and leading spaces

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#576]
Well I know I'm probably posting issues too frequently, I apologize for that. Still there is something bothering me while trying to document a function with Hot doc.

![image](https://user-images.githubusercontent.com/10547551/32872906-3089286e-cac4-11e7-8e33-2b6517746dad.png)

With the above code as an example, Hot doc seem to display wrongly, as shown in image below
![image](https://user-images.githubusercontent.com/10547551/32872987-9804041e-cac4-11e7-963c-8812ef0bd04d.png)
(Seem to happen with a constructor of class only, so far for me)There are some unwanted code came out in Hot doc.

![image](https://user-images.githubusercontent.com/10547551/32873033-caf2f664-cac4-11e7-8027-1bb3155b780d.png)
Between line 1 and line 2, there is 1 extra spacing which is a little bit annoy for me.

Thanks for taking your time reading this.

**Comment by Frotty** [comment]
Issues are welcome! However due to our limited time and this being a hobby project it might take some time for them to get addressed 🔜
