### ISSUE TITLE
Dependencies get borked when jumping to their declarations

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#582]
Example
1. Open stdlib2 in vscode
2. Open a package, e.g. OnUnitEnterLeave.wurst
3. Jump to a declaration of a native/function in common/blizzard.j
4. Go back to original package
5. Type anything
6. All common/blizzard.j usages now throw an error and are supposedly unknown.
And animated:
![](https://dl.dropboxusercontent.com/content_link/EMbpyfU6d0G7UtqRtXy6JJ0HikxOBJEOvB4gwfLnRyrGHmLTNmgcvAnOOisBVYiK/file?dl=0&duc_id=3IdYyAc4EM9bJ1K4V4YAT3FokBZovuk7ofrWhN1cOYWrSDS4sW9wOSsjLJsmYdEK&raw=1&size=2048x1536&size_mode=3)

**Comment by peq** [comment]
Should be fixed with abee3ef6ce315a39f27cccd2ece6721176addbf4
