### ISSUE TITLE
Map generated using the buildmap command is unopenable by wc3 (through map selection) and WE

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#591]
At the same time, I can run it from the console for some reason. I suspect this has something to do with the buildmap command messing with the map's metadata. I have attached a newly generated project that shares this issue with my maps. [MyWurstProject.zip](https://github.com/wurstscript/WurstScript/files/1503087/MyWurstProject.zip)

**Comment by Frotty** [comment]
Please elaborate. Which errors are you getting, etc.
The map works fine for me in WE and wc3.
![](https://i.imgur.com/yDnIePN.png)

**Comment by IgorSamurovic** [comment]
It doesn't show in map selection in wc3. We throws this error.

![image](https://user-images.githubusercontent.com/18104605/33230891-dc7fcf0a-d1eb-11e7-8c88-0406d4fd72b9.png)

**Comment by IgorSamurovic** [comment]
[maps.zip](https://github.com/wurstscript/WurstScript/files/1503195/maps.zip)
Here's the build vs runmap version.

**Comment by Frotty** [comment]
fixed by 47df2464362d0823ab1cc400ef09f76fe76684f5
