### ISSUE TITLE
S2I doesn't work in compiletime

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#593]
> calling int_toString(null)

When I should clearly get a number. The string.toInt() method also doesn't work, but because apparently the R2I function is being passed null.

**Comment by peq** [comment]
I added the missing natives, however ...

@Frotty Why does the Standard library use `Pow` and `R2I` instead of `S2I` for this?

**Comment by Frotty** [comment]
not sure if there was a particular reason for it. Can probably be changed. according to lep/jassdoc they do they same job.
