### ISSUE TITLE
Superclass detection for generic classes that extend other generic classes

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#595]
So, say you want to extend a LinkedList. The SubLinkedList<T> should be a subclass of LinkedList<T>. Right now the compiler says that they are not related, which forces a lot of boilerplate code to be written, as well as some ugly casts and generally bad practices.

This suggestion is probably the one to add to the "things to do when refactoring generics" list.

**Comment by Cokemonkey11** [comment]
> Right now the compiler says that they are not related, which forces a lot of boilerplate code to be written, as well as some ugly casts and generally bad practices.

It's not clear to me what the symptoms are. Have you written a function that take a LinkedList<T> as a parameter and then passed it a SubLinkedList<T> ?

My initial reaction is something like "don't extend functionality of a class with an implementation", but if you give better details of symptoms, this might be pointing to a more broad reaching problem.

**Comment by IgorSamurovic** [comment]
Oh damn, I wrote an edit to this but I forgot to save it.

Anyways, the problem I have with this is that LinkedList<string>.join() exists, that'll return a string after joining all the elements of a LinkedList<string>.

However, if I extend LinkedList to create List, the List<string> won't have the .join() method.
