### ISSUE TITLE
HaveSavedInteger doesn't work in compiletime/tests

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#596]
```
package test

@Test function test()
    let ht = InitHashtable()

    HaveSavedInteger(ht, 0, 0).assertEquals(false)
```

This throws:
> Running test <test.test> .. FAILED with exception:
	Local variable this is null.
Tests succeeded: 0/1
>> The following tests failed:
Local variable this is null.
... when calling boolean_assertEquals(null, false) in test.wurst:5
... when calling test() in test.wurst:3

As @Frotty said, this should not be possible, a bool should never, in any case, be null, but it seems like the native doesn't work at all in compiletime/tests.

**Comment by Frotty** [comment]
fixed by d79c111
