### ISSUE TITLE
Text Highlight issue

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#597]
1. Package name highlight is off by 1 :
![image](https://user-images.githubusercontent.com/10547551/33554733-ebafb0cc-d938-11e7-9623-080787ad938f.png)

2.
![image](https://user-images.githubusercontent.com/10547551/33554789-12a51546-d939-11e7-9447-4428596e91d2.png)
obviously "/** some description */" shouldn't be highlighted.

**Comment by Frotty** [comment]
And when does this happen?
