### ISSUE TITLE
WurstSetup.jar issue

### ISSUE THREAD

**Issue by MediumRareSteak-Hive** [wurstscript/WurstScript#598]
Attempting to install WurstScript..
Downloading compiler... done
Extracting compiler..
===ERROR COMPILER UPDATE===
error in opening zip file

WurstSetup.jar version: Most current version (9/12/2017)
Java version: "1.8.0_151" 32-bit

**Comment by Frotty** [comment]
Hi, the setup has it's own repo here https://github.com/wurstscript/WurstSetup
Please make future tickets for it there.

To debug this current problem, please provide the log from Users/YourName/.wurst/logs/setup.log

**Comment by MediumRareSteak-Hive** [comment]
2017-12-09 22:05:08,972 INFO  [SetupApp] - startup setup version: <1.1.3.1-jenkins-WurstSetup-30>

**Comment by Frotty** [comment]
Please paste the **complete** log @MediumRareSteak-Hive 1 line doesn't suffice. Either here in this ticket or link a [gist](https://gist.github.com/).

Thanks

**Comment by MediumRareSteak-Hive** [comment]
That line was the only content before I downloaded the new version and restarted it. I think this can be marked as solved or something.
