### ISSUE TITLE
Compiletime implementation of hashtable API is potentially wrong

### ISSUE THREAD

**Issue by SamuelMoriarty** [wurstscript/WurstScript#599]
I looked at the compiletime providers for hashtable and noticed that all natives seem to share the same underlying hashtable. The problem would arise if you tried to store an integer and a boolean at the same key - the boolean would overwrite the integer in the current implementation.

IIRC in WC3, however, they will not collide, since each value type storage is independent from each other.

**Comment by Frotty** [comment]
fixed by 67041dbb0385525f5c3092e24f405744d16981c4
