### ISSUE TITLE
Closures don't recognize class hierarchy

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#605]
I have this closure interface:
```
public interface ItemClosure
	function run(UnitInventory inventory, ItemInstance inst) 
```
I also have this assignment somewhere in code:
```
onUnequip = (UnitInventory inventory, ItemInstance inst) -> begin
    let armor = inst castTo ItemInstanceArmor
    inventory.getUnit().defense.add(armor.def)
end
```
ItemInstanceArmor is a subclass of ItemInstance, so this works, nothing weird there. What doesn't work, however, is this:
```
onUnequip = (UnitInventory inventory, ItemInstanceArmor inst) -> begin
    inventory.getUnit().defense.add(inst.def)
end
```
I get a huge red line across the whole assignment because:

```
file: 'file:///x%3A/wc3/projects/TheRpg/wurst/equipment/classes/ItemClassArmor.wurst'
severity: 'Error'
message: 'Cannot assign (UnitInventory, ItemInstanceArmor) -> Void to ItemClosure'
at: '42,9'
source: 'Wurst'
```

**Comment by peq** [comment]
I would say wurst is correct here. You pass a closure which accepts fewer
values than required.

**Comment by IgorSamurovic** [comment]
Elaborate. You mean, in the implementation, ItemInstanceArmor will use 2 values, one to refer to the instance of ItemInstanceArmor, and one to ItemInstance, right?

**Comment by peq** [comment]
Consider what happens if you call run: you pass a ItemInstance object. Your
closure only accepts ItemInstanceArmor objects, so the call is not possible.

**Comment by IgorSamurovic** [comment]
Actually, the thing is, the closure accepts ItemInstance object. ItemInstanceArmor extends ItemInstance. So why doesn't it accept ItemInstanceArmor? When I use ItemInstance, and cast it to ItemInstanceArmor, I get the value I expected, so why doesn't the closure accept it (and just cast it by itself, instead of forcing me to cast it one line bellow)? 

The whole point of this is that I have a working solution, that requires giving the instance of a class to the closure, and then downcasting it to a variable, and then using that variable. Why can't closure downcast this by itself? It seems logical that it would.

**Comment by peq** [comment]
Downcasts are not safe, so they are not done automatically.

This is the same (or even more restrictive) in most languages. If you want to read more about it have a look at https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)

**Comment by IgorSamurovic** [comment]
Oh, I didn't think about that at all. I've now spent some time reading up on the subject and I realized I didn't actually understand the problematics of it. Thank you!
