### ISSUE TITLE
Add UserDefaultImport.wurst functionality

### ISSUE THREAD

**Issue by IgorSamurovic** [wurstscript/WurstScript#607]
Basically, if a package ```UserDefaultImport``` is created, it would be imported into every user-defined package implicitly just like ```Wurst.wurst```. This makes it possible to import packages project-wide. The main use for this would be for users to easily import their extension functions across the board without having to clutter the Import block with them (though you can argue this can also be done by using ```import public``` functionality and a package called ```ExtensionFuncs``` or something).

The obvious problem with this idea, however, is that it might become harder to know exactly what your classes depend on, but I think it could be an option for users that want it, not for systems they'd want to share, but for their own projects. That being said, having an option to ```import NoUserDefaultImport``` would be nice too.

**Comment by Cokemonkey11** [comment]
Not a fan. I already find `Wurst.wurst` a bit smelly tbh.

**Comment by IgorSamurovic** [comment]
Well, I can see why you wouldn't be a fan, though. This is generally a really bad programming practice, which obscures the hierarchy. I just wanted it to be an option.

**Comment by Frotty** [comment]
You can already create your own `Wurst.wurst` that does this iirc. If not, you can still make a special package which has all the public imports you need.

**Comment by IgorSamurovic** [comment]
Alright then. I've been tinkering about with this for a while and I decided that, according to some of my suspicions, it really isn't a good idea.

**Comment by peq** [comment]
I think what we really want is that autocomplete shows all extension
functions and adds imports automatically.

**Comment by Frotty** [comment]
does configuring the Wurst.wurst package work? :P

**Comment by IgorSamurovic** [comment]
Just to comment for the record:
Making your own ```Wurst.wurst``` makes it possible to add default imports. While not advised, this gives those who want this feature an option.
