### ISSUE TITLE
Autocomplete broke in cascade operator

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#610]
```
@compiletime function generateAbility()
    new AbilityDefinitionFireBoltcreep(ABILID)
        ..setDamage(0, 0)
        ..<here autocomplete broke> //any code below here will broke the autocomplete

function b()
    skip
```

**Comment by Frotty** [comment]
post a complete compilable example and steps to reproduce. The given code works fine for me:
![image](https://user-images.githubusercontent.com/1486037/34359380-e5a558b4-ea57-11e7-8cc1-5f9db05993e2.png)

**Comment by peq** [comment]
This only seems to happen, if there is no text after the dot. I'll try to fix it.
