### ISSUE TITLE
Make autocomplete detect existing brackets

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#617]
Often times I just want to change a function call name, and not have wurst place brackets again.
Example:
![](https://i.imgur.com/GEZDvQS.gif)

The new `()` shouldn't be placed there. I think it is fine if it only works for parameterless calls for now,
but of course having it detect if the existing parameters match the autocompleted function, would be ideal.

IDEA example:
![](https://i.imgur.com/TcQJspr.gif)

**Comment by peq** [comment]
For the Alm Beisser ;)

**Comment by karlek** [comment]
Omg, yes thank you! <3
