### ISSUE TITLE
how to setup in China

### ISSUE THREAD

**Issue by zhongying1995** [wurstscript/WurstScript#622]
when i setup the WurstSetup.jar,it say Ready version:1.1.4.0-jenkins-WurstSetup-52    Server offline.All update functionality disabled. 
i had used the Lantern ,a VNP to Surf the foreign Internet(i am chinese),but can not setup Wurst.
So,what should i do?

**Comment by Frotty** [comment]
This issue was moved to wurstscript/WurstSetup#5
