### ISSUE TITLE
Failed to generate a 1.29 map that uses 1.29 natives

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#623]
Steps taken:

* Use `native` to trick wurst into compiling a map that uses PTR natives
* Edit the compiled `war3map.j` in the map archive to not declare `native`
* Save and re-test

Looks like some metadata is invalid after this because the map players/forces dont appear in lobby when testing after mpq editing.

Code: https://github.com/Cokemonkey11/execute-wurst/blob/ee432476c1d7f429da01616393c4029c57855299/wurst/Effects2.wurst

Expected behavior: map should run and generate lots of effects with custom orientation (PTR natives)

**Comment by Frotty** [comment]
Known bug.

**Comment by Frotty** [comment]
closing as of: https://github.com/wurstscript/WurstScript/pull/640

**Comment by Cokemonkey11** [comment]
Nice!
