### ISSUE TITLE
could your make some Implicit type cast

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#632]
just like this:
```
@enableCast public func aaa(...)
  var a = "s";
  var b = 1
  print(a + b) //s1
```
 or make a varsign "cast" like var and let
```
 cast a = "123"
 int b = 5 + a;//128
```
 (maybe on complitime?)

**Comment by Frotty** [comment]
Hi, pls use code format, I have edited your ticket.
I'm not sure what you mean by your examples though.
If it's just about the `print(a + b)`, then you can simply do
```
print(a + b.toString())
```
Or if you want to have the `+` operator be defined for `(string, int)`, you could overload it, see https://wurstlang.org/manual.html#operator-overloading

Do you just want this for easier string building? Or is there another purpose?

**Comment by PhoenixZeng** [comment]
sorry i try use the code format but i fail . And i`m sorry about my pool English
is the overloading operator  work on the jass base data type (like the int and string ) ? .
I thought it could only be used for class and trupe

i mean is  "can we use the variable with auto type conversion just like the javascript"

in JS .we can use the plus the string with the number
 if the string is a number-string     (like  "123" ) ,it can plus with the number get a number result and if it is a string like "abc" it will append they .
other example is if the function want a string param and i have a int value ,i dont have to use the I2S() or
the toString() . I think too much R2I(), I2S(),R2S() ...... is too cumbersome in the jass.
of course ,for safety and compatibility  wo can user the special annotation or keyword to open that.

the last word  "(maybe on complitime?)" means that:
    If you don't do this on the runtime .Maybe it can do it on the compile time

**Comment by Frotty** [comment]
We planned on adding some syntactic sugar for string building like 
`"you received $(amount) gold!"`
but didn't get around to it yet.

And of course, you can overload operators for any type.
I made an example for you
```
function string.op_plus(int i) returns string
	return this + i.toString()

let s = "blub" + 1
```

**Comment by PhoenixZeng** [comment]
wow,the Template is cool 
i put this your example in the hello.wurst but get a syntax error .
and i read your wurstlang document .
 i found your use castTo like this
```
class Test
    int val

init
    let t = new Test()
    let i = t castTo int
````
but i try to use that and the war3 print a " 1 "

**Comment by Frotty** [comment]
> i put this your example in the hello.wurst but get a syntax error .
Shouldn't be the case. Trying updating compiler and project. What error exactly is it?

> but i try to use that and the war3 print a " 1 "
Obviously, since it's for casting classes. In this case `castTo int` gets you the index that represents the object. I'm pretty sure this is not what you want.

**Comment by PhoenixZeng** [comment]
thanks .the syntax error is my error .
I was misled by your document.because the class Test have a int field "val" 
I was naive to think that it would turn to that "val".value

i am a Beginner on wurst .so i have some mistaken ideas
---------------------------------
other question
```
function [TYPE]ToIndex([TYPE] t) returns int

function [TYPE]FromIndex(int index) returns [TYPE]
    return ...
```
```
function unitToIndex(unit u) returns int
    return u.getHandleId()

function unitFromIndex(int index) returns unit
    data.saveFogState(0,ConvertFogState(index))
    return data.loadUnit(0)
```
what is this code mean .

mycode .  how to fix it
```
package store

public constant hashtable db = InitHashtable()

public function handle.set(string k,string k2)
    db.saveInt(k.getHash(), k2.getHash(),this.getHandleId())

public function get<T>(string k,string k2) returns T
    return ???

public function getUnit(string k, string k2) returns unit
    return db.loadUnitHandle(k.getHash(), k2.getHash())

```

**Comment by Frotty** [comment]
Yes, you are a beginner and aren't used to English, which is why you should try to ask concise, small questions (not on here, as I've said plenty times now), since the code you posted has no relation.

The `function [TYPE]ToIndex([TYPE] t) returns int`  is just an explanation inside the manual on how to write extension functions.
The second is implicit typecasting for primitive types in generics.
So I'm not sure what you're trying to do. However if you just want to save arbitrary handles inside a hashtabel, you should use HashMap, as I've shown in another ticket. See `HashMap.wurst`

**Comment by Frotty** [comment]
If you aren't elaborating on this I will close it, okay?

**Comment by PhoenixZeng** [comment]
yes， you can close this. thank you
