### ISSUE TITLE
More Operator Overloading

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#635]
Through some historical problems, I know that the overloading  operators which used by wurst are ambiguous
but support overloading the not-used operators by user maybe a good idea 
just like
 { }     ::  # $ ^ & ~ |  !
if it support  we can use  by myself definition like "&" as "and" , "!" as "not "

**Comment by Frotty** [comment]
There is an open ticket with the exact same name.
https://github.com/wurstscript/WurstScript/issues/297
Please verify that an issue doesn't already exist and that it's a valid ticket before creating it.. 👎 

Also, adding overloading for such operators `{ } ^ & ~` that don't even exist in the language, doesn
t really make sense.
