### ISSUE TITLE
World Editor specific variables caused translation error

### ISSUE THREAD

**Issue by lhing17** [wurstscript/WurstScript#639]
Variable references from units on the map will cause translation error. I found this issue was posted in history version and the reply was "gg_XXX" variables would be ignored or "external" keyword would be introduced. However, neither of the above solutions is included in the current version.

**Comment by Frotty** [comment]
No. World Editor variable references work, but different. Wurst now simply parses the entire war3map.j, and if that file contains the gg_ variables, you can use them.
Depending on your world editor version and plugins, the "gg_" variables will only get generated once used from inside the editor. A workaround for this is to create a GUI trigger and select the units you want to reference in your wurst packages.
