### ISSUE TITLE
Handling of boolean operators in Jass files incorrect

### ISSUE THREAD

**Issue by nvs** [wurstscript/WurstScript#641]
Given the following snippet:
``` jass
if true or false and false then
	call BJDebugMsg ("true")
else
	call BJDebugMsg ("false") // This is executed by Warcraft.
endif
```

Given that `or` has higher precedence in Jass than `and`, the expected result from Wurst should be:
``` jass
if (true or false) and false then
	call BJDebugMsg ("true")
else
	call BJDebugMsg ("false") // Should be executed.
endif
```

However, this is what is produced by Wurst:
``` jass
if true or (false and false) then
	call BJDebugMsg("true") // And this is erroneously executed in game.
else
	call BJDebugMsg("false")
endif
```

The operator precedence in Jass may end up being a gotcha to many users. However, maps that either intentionally or unintentionally rely on the expected precedence may unexpectedly break when given to Wurst.

**Comment by Frotty** [comment]
Yea, in Wurst and has higher precedence. 
Simple workaround for you is to add brackets, but this should be fixed I suppose.

**Comment by nvs** [comment]
Yeah, I plan to add brackets. Fixing is probably for the best, to ensure comaptibility with existing Jass/vJass scripts.
