### ISSUE TITLE
Ignore new common.j natives if game version too low

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#645]
Since we want to ship the latest jass API with wurst, but keep backwards compat,
the new natives should simply be ignored so that everyone can use the same standard library.

**Comment by peq** [comment]
Hmm, shouldn't this already work as we remove all unused functions?

**Comment by karlek** [comment]
I couldn't compile my map as the Blz* natives were missing from common.j

**Comment by Frotty** [comment]
@karlek If you want to compile pre 1.29 , you need the stdlib branch pre 1.29 which doesn't contains the extension functions etc.

I guess we need the setup tool now to offer a pre-1.29 setup

**Comment by karlek** [comment]
Yeah, I don't think the mapping community in general has the git skill to change branches freely.

**Comment by PhoenixZeng** [comment]
yes.
 a other 1.29 set is the JASS_MAX_ARRAY_SIZE = 32768 at 1.29
I use the standard library very carefully to make sure that my map can run on 1.27. But there is nothing I can do about this array size.

**Comment by Frotty** [comment]
@PhoenixZeng we don't use `JASS_MAX_ARRAY_SIZE` anywhere.
What exactly is your problem?

**Comment by PhoenixZeng** [comment]
@Frotty in compiled.j.txt
i can find code like this very much:
and it will report a error in sometime GameRun
`````
	if ForGroupCallback_firstFree == 0 then
		if ForGroupCallback_maxIndex < 32768 then
			set ForGroupCallback_maxIndex = ForGroupCallback_maxIndex + 1
			set this_21 = ForGroupCallback_maxIndex
			set ForGroupCallback_typeId[this_21] = 701
		else
			set wurst_stack[wurst_stack_depth] = ""
			set wurst_stack_depth = wurst_stack_depth + 1
			call error("Out of memory: Could not create Closure.")
			set this_21 = 0
		endif
`````

**Comment by Frotty** [comment]
Yes, but that isn't related to this ticket, which is taking about common.j/blizzard.j

**Comment by PhoenixZeng** [comment]
emm.
i think the `32768` should read the `common.j - JASS_MAX_ARRAY_SIZE` ,but  from the Compiler (or other way)
and the common.j/blizzard.j always base on the game version

**Comment by Frotty** [comment]
Yes, if we want to support pre 1.29 development fully, we probably need some fallback functionality.
However, if you reach the array limit, you need to fix your code anyway :)

**Comment by Cokemonkey11** [comment]
Code that doesn't behave well (leaks class instances) will easily hit the array limit.

**Comment by PhoenixZeng** [comment]
@DaffaMage    `linkedlist ``s `LLEntry` may hit 8192 in a large map. And interface or class which have too many subclasses will easily hit the array limit

**Comment by DaffaMage** [comment]
I see then, my apologies.

**Comment by peq** [comment]
If we compile with an old common.j the current version of the standard library will probably give some errors since it uses some new natives.

Why can't we just compile with the new common.j and use pjass to check the final war3map.j against the target version common.j? 

And for array size we can just add an option.

**Comment by Frotty** [comment]
Yes, I think the project's common.j Blizzard.j aren't passed to Pjass. Other than that it should be working.
