### ISSUE TITLE
Is there a way to get the compiletime objects into the WE map?

### ISSUE THREAD

**Issue by freddyalready** [wurstscript/WurstScript#648]
Hi,
I created some units via compiletime functions & object editing. Now i want to place these units into my map. is there an built in way to get the objects into my world editor map? I know i could copy paste them from the _build map but they wont have the correct ids.
Thanks in advance!

**Comment by Frotty** [comment]
> I know i could copy paste them from the _build map but they wont have the correct ids.

What do you mean by wrong?
If you generate ids they might not stay as you want them, so for doodad/destructable you could use fixed id.
Units usually shouldn't be preplaced.

**Comment by Frotty** [comment]
Some times you of course want the convenience on placement in editor.
Another solution is to have a dummy object in editor, which you place on map. then you replace that dummy unit with the unit you actually want.
