### ISSUE TITLE
The function TriggerRegisterVariableEvent is not allowed in Wurst

### ISSUE THREAD

**Issue by kilanth** [wurstscript/WurstScript#650]
Obviously, it is not a bug, but how to get around it?
I use imported damage detection library and I don't want spent time researching how to make 1, so yeah, help me out. What to do?
Library link https://www.hiveworkshop.com/threads/gui-friendly-damage-detection-v1-2-1.149098/
It is slightly modified to fit my needs, still very powerful library!

**Comment by Frotty** [comment]
The standard library contains the `DamageDetection` package doe damage detection needs.
Unless you are maintaining an existing map, you shouldn't import vjass to jass compiled resources.
If that's the case, you have to replace the TRVE in original code, e.g. with regular triggers and actions.

**Comment by kilanth** [comment]
Hey, thanks for quick reply!
The thing is I have a working map, and I've done more or less 4k lines. After a small intro with wurst script I knew I wanted to switch to that amazing project, but do you think it will take a lot of time translating old Jass scripts to Wurst?

**Comment by Frotty** [comment]
I guess that highly depends on your motivation and the code you have written.
You could start translating your vjass to Jurst, which is a jass friendlier dialect (https://wurstlang.org/tutorials/legacymaps.html#jurst-dialect)
Which might make it psosible to take over code with a few search&replace operations.

**Comment by Ruk33** [comment]
I don't know very well how JASS & Wurst work together, but, can't you use a wrapper?. As far as I'm reading in the manual for legacy maps (https://wurstlang.org/tutorials/legacymaps.html) you should  be able to do so.

Try this, with a little bit of luck it should work.

In your map (using plain old JASS), create a function that takes the same parameters and returns the same as TriggerRegisterVariableEvent does:

```function TriggerRegisterVariableEventWrapper takes ... returns ...
    return TriggerRegisterVariableEvent(...)
endfunction```

Then, in your Wurst project, don't call TriggerRegisterVariableEvent, instead, call your wrapper. That way Wurst shouldn't be able to throw the error that you're getting.

Regards.

**Comment by kilanth** [comment]
Hello there, 
Following the guide you've linked, adding argument to wurst_run.args still extracts map's .j script and overrides any changes I'm making, namely, creating Wrapper as suggested by @Ruk33 .
wurst_run.args looks like this
`-noExtractMapScript`

**Comment by Frotty** [comment]
@Ruk33 No, the Jass code needs to be parsed by wurst to combine it with the wurst output.
Thus it won't work. Rest of the guide applies.

**Comment by peq** [comment]
Do you still have Gui triggers in your map? If not it should be easy to replace your damage detection code with a different damage detection system. `TriggerRegisterVariableEvent` is only useful for integrating with Gui triggers.

It would theoretically be possible for us to support `TriggerRegisterVariableEvent` in Wurst like we did for `ExecuteFunc`, but in a pure Wurst map there are no real uses for it.

**Comment by kilanth** [comment]
@peq Thanks for the advice, man. I think I'm just gonna go on with Wurst learning for now and making few engines first on its own. I do have other considerable question to ask - function list if any. On your manual, there are a bunch of tutorials and concepts of the language, but no javadoc-like dump of all standard libraries and functions for free use. Like that DamageDetection package mentioned by Frotty. Where to look for function/var list rather than a source of it by ctrl+clicking on the package? Cheers, that will be final question :)

**Comment by Frotty** [comment]
We have a javadoc equivalent hotdoc, but it's currently out of order.
Other than that I recommend vscode global search and package search (ctrl + p).
We are working on adding a javadoc-like section to our website.
