### ISSUE TITLE
strange Module: linkedlistmodule

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#656]
````
class Path
    use LinkedListModule
    static Path top = new Path(main_top,Way.Top)
    static Path left = new Path(main_left,Way.Left)
    static Path right = new Path(main_right,Way.Right)
    static Path bottom = new Path(main_bottom,Way.Bottom)
    construct(Rects start,Way way)
        this.way = way
        this.start = start
        print("->init path"+Path.size.toString())  // right here 
    static function getSize() returns int
        return Path.size
````

````
init
    doAfter(1)->
        print(Path.size) // 0 
        print(Path.getSize()) // 0 why? the function get the size from the class 
        Path top = new Path(main_top,Way.Top)
        Path left = new Path(main_left,Way.Left)
        print(Path.size) // 2 why?
        print(Path.getSize()) // 2
````

well . `for i in class(which use the linkedlist)` used good.  But it's very strange to use it outside of the class (looks like only work when new Instance in same function)

**Comment by peq** [comment]
Should now be fixed: Module instance variables will be initialized before class variables.

**Comment by peq** [comment]
However, it is still possible to mess this up, by creating a class instance, before the class has been initialized. We should probably add a warning to avoid this.

**Comment by Frotty** [comment]
Because package init happens top-down.
Simply moving your init block after the class will solve your problem.

**Comment by PhoenixZeng** [comment]
change the package block position to
class  - public const(test1) - init block
it worked ,good 
(if the const move to after the init block ,print 4,6,2,5. collide with the manual `At the beginning of an init block you can assume that all global variables inside the current package are initialized.`
thanks.

**Comment by Frotty** [comment]
Yes, your second mistake was creating a class object before the class' definition.
E.g. this works fine:

```
package demo
import LinkedListModule
import ClosureTimers

init
    doAfter(1)->
        for i in Path1
            print(2.)

public class Path1
    use LinkedListModule
    construct()
        print("init path"+Path1.size.toString())

public constant Path1 _top = new Path1()
```

Just like

```
constant B = A
constant A = 1
```

A warning should be added.
