### ISSUE TITLE
How to break compile and show stack info by user?

### ISSUE THREAD

**Issue by dulingzhi** [wurstscript/WurstScript#659]
Hi guys,
    I`m writing a locale library, I want to stop compile when compiletime missing locale record.

thx.

**Comment by Frotty** [comment]
`package ErrorHandling`
you can use `error("my message")` and the stack will be in the Output->WurstLangServer tab.

**Comment by Frotty** [comment]
With https://github.com/wurstscript/WurstStdlib2/commit/ef0623e658f0b35b560e49bb1f3413b04f209406
The compilation is now aborted properly again.
