### ISSUE TITLE
should report error when function name endwith "_"

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#660]
example:
function aa_()

this function not report error . and could compile

but it cant run on the wc3

**Comment by Frotty** [comment]
Hi, thanks for your frequent reports - however you keep making the same mistakes.+

1. Use proper markdown highlight please. see https://guides.github.com/features/mastering-markdown/

2. Provide a complete, self contained package, that reproduces the error **in a clean project**!

What you said works perfectly fine:
```
package Test

function aa_()
	print("abc")

init
	aa_()
```
![](https://i.imgur.com/LfAncJl.png)

**Comment by PhoenixZeng** [comment]
````
abstract class Hello
	abstract function do_()
	static function do(Hello _h)
		_h.do_()


init
	print("1")
	Hello.do()->
		print("2")
````
this cant run on wc3 1.27
because the compiled has this
`function dispatch_Hello_Hello_Hello_do_ takes ...`  (endwith "_")

**Comment by PhoenixZeng** [comment]
and the last bug i say is that:
````
class A

@test function aa()
 //if the const have a small value ,it work .
// one time set the con as a big val, the langserver report error
// after that , it always  report error whether what val is the can .until restart the vscode
	var con = 1000  

	for i=0 to const
		new A()
````

**Comment by Frotty** [comment]
> this cant run on wc3 1.27

I see. I had inliner/name compression enabled. Both optimizations get rid of the function and therefore the issue. In the end the obvious workaround is still to simply not name your function like that. Thought should probably be fixed.

> and the last bug i say is that:

If it's unrelated to this issue, make another ticket..
