### ISSUE TITLE
wurstpack_compiler.zip Not found at runnning Install WurstScript

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstScript#661]
Where to start for error searching?
![1](https://user-images.githubusercontent.com/640169/40580786-c9939bfc-6146-11e8-823a-d6126ba9dfe2.PNG)
![2](https://user-images.githubusercontent.com/640169/40580787-cb161220-6146-11e8-8489-2900fa828f8c.PNG)

**Comment by Krypt0n** [comment]
wrong repo --> moving to -> https://github.com/wurstscript/WurstSetup/issues/12

**Comment by Frotty** [comment]
So what was the issue?
