### ISSUE TITLE
Show black screen with no dialog when run the map

### ISSUE THREAD

**Issue by luoshui9** [wurstscript/WurstScript#664]
>>Wurst : run a wurst map
>>Compilation completed, no issue at this moment.
>>Wc3(ver 1.29.2.9208) runs
>>Shows nothing but a black screen with sound( I believe that was the background sound in title screen). No black error dialog was shown. 

The Wurst file is brand new, no code from myself but "helloworld".
I have checked directory Maps/Test. Duplicate WurstRunMap.w3x wasn't found.

I tried Wurst on wc3 1.24, it works normally. 
Then I install 1.29 patch, delete and re-install Wurst with new game path and new project root, twice.
It doesn't work still.

Thanks for your help in advance.

**Comment by peq** [comment]
Can you please share the log files from `${user.home}/.wurst/logs/`?

I think with the new patch the map file should be under `${user.home}/My Documents/Warcraft III/Maps/Test/WurstTestMap.w3x`. Can you check if it exists and if you can run the map manually?

**Comment by luoshui9** [comment]
[languageServer.log](https://github.com/wurstscript/WurstScript/files/2065191/languageServer.log)
The map is exists in the directory you said. I can run the map with original World Editor.


Thanks for reply.

**Comment by Frotty** [comment]
As the tickets before, check if the WurstRunMap exists in your documents wc3 folder and game rot at the same time, that doesn't work.
The other main issue is a war3.exe in your game directory that shouldn't be there. Delete that if it exists.
If you want us to check out the logs I highly suggest pasting them somewhere, and not uploading.

**Comment by luoshui9** [comment]
I try to delete the map WurstRunMap.w3x in my Documents\Warcraft III\Maps\Test folder. However, the map is regenerated by Wurst every time I run the map in VScode.
I can't find any war3.exe in my 1.29 game directory. But I do have a low version wc3 with its war3.exe in a total difference directory.

log might quire long so I paste it on my hub
[LanguageServer](https://github.com/luoshui9/wc3/blob/luoshui9-Stuff/Log%20LanguageServer)
[Compiler](https://github.com/luoshui9/wc3/blob/luoshui9-Stuff/Log%20compiler)
[setup](https://github.com/luoshui9/wc3/blob/luoshui9-Stuff/Log%20setup)

**Comment by Frotty** [comment]
The one in documents is from wurst. You need to delet ethe one from the game's root maps folder, where it was located pre 1.29.
