### ISSUE TITLE
Can not find LinkedList.wurst (VSCode)

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#665]
`The import LinkedList could not be found in file C:\Users\Ban\.wurst\stdlib\wurst\data\LinkedList.wurst`
And only LinkedList.wurst.

**Comment by GetLocalPlayer** [comment]
I'm afraid, I can't. Standard library has LinkedList.wurst file that includes LinkedList package.

**Comment by GetLocalPlayer** [comment]
Have just noticed, VSCode has issues everywhere in new syntax like `vararg` or new lamda style. Probably I should build the latest version of extension by myself instead of using VSCode loader.

**Comment by peq** [comment]
> Probably I should build the latest version of extension by myself instead of using VSCode loader.

Yes, the vscode plugin does not update Wurst automatically. Frotty is planning to implement this.

**Comment by GetLocalPlayer** [comment]
Indeed.
Solved.
