### ISSUE TITLE
Map Created by YDWE can't be operated by wurst

### ISSUE THREAD

**Issue by luciouskami** [wurstscript/WurstScript#674]
**Can Wurst support maps which created by [YDWE](https://github.com/actboy168/YDWE)?**
Because a map created/saved by [YDWE](https://github.com/actboy168/YDWE),it can't be injected code and import res by wurst,I must do an extra operation that using WE to save map again. So that the map can be injected by wurst.
**Is it possible to use the [StormLib](https://github.com/ladislav-zezula/StormLib) to manage to MPQ operations?**
If wurst use the same 3rd praty library as [YDWE](https://github.com/actboy168/YDWE) the issue will be solved.
Here 's the two map,they have huge difference.
![error](https://user-images.githubusercontent.com/10268785/41402355-b536d54a-6ff4-11e8-8c6a-d5bd4a98048e.png)

[MyWurstProject.zip](https://github.com/wurstscript/WurstScript/files/2101548/MyWurstProject.zip)

**Comment by luciouskami** [comment]
In fact both [YDWE](https://github.com/actboy168/YDWE) and [w3x2lni](https://github.com/sumneko/w3x2lni/) use [w2l](https://github.com/sumneko/w3x2lni/blob/master/w2l.exe).I think it is the best warpper which afford user use commandline to manage their maps.[Doc](https://sumneko.github.io/w3x2lni/#/en-us/)

**Comment by Frotty** [comment]
YDWE corrupts/protects the map. Make the author fix that, or simply use wurst first.
We want to use native java cross platform code, and not ship platform dependent binaries.
If it's important to you, feel free to add support to https://github.com/inwc3/JMPQ3

**Comment by Frotty** [comment]
Hey, due to recent updates to jmpq by the amazing @WaterKnight and me, maps like these should now be fully supported by wurstscript 😎 

@luciouskami Can you please update wurst and verify this?

Cheers 🍻
