### ISSUE TITLE
Does Wurst support campaign?

### ISSUE THREAD

**Issue by LazyKnightX** [wurstscript/WurstScript#675]
Seem there is no question about campaigns, so I asked here.

Does wurstscript support edit campaign?
I didn't find any issue related to this (and searched for a while).

If it supports, what I need to do to use wurst in the campaign?

**Comment by Frotty** [comment]
Campaigns are just a collection of regular maps.
You can use wurst on those maps just as usual, but you will have to use the campaign manager to assemble the final product.

**Comment by LazyKnightX** [comment]
The question is the campaign provide features like sharing object data or sharing import data.
It's easy to start an single map, but how to start a single map in campaign by wurst, without lose campaign's sharing data?

**Comment by Frotty** [comment]
I'm not sure what you mean by sharing data, but no, wurst has no specific handling fo campaigns.
However people have used it before.
If you have specific features you want to request, please make a new ticket and fill out the template.

**Comment by Cokemonkey11** [comment]
wurst has better than sharing data, you just import the same scripts in different maps
