### ISSUE TITLE
config option: test map with elevated permissions

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#678]
I have a problem:

- If I launch wc3 without administrator access, then lots of things won't work. Single player CGs, campaign, wc3 battle.net lobbies, and wc3 normal games (ladder matches)

- If I launch the world editor and test *any* map, wc3 will crash during test map
- If I launch the world editor with administrator mode, then wc3 will run fine during test map

I'd like to be able to testmap wc3 with administrator access, without running vscode with elevated permissions.

The solution I'd like:

- a config option to enable elevated permissions when running wc3 via test map

**Comment by Frotty** [comment]
> If I launch wc3 without administrator access, then lots of things won't work. Single player CGs, campaign, wc3 battle.net lobbies, and wc3 normal games (ladder matches)
> If I launch the world editor and test any map, wc3 will crash during test map

Sounds like local problems with your installation.
The wurst started processes inherited parent permissions, try starting vscode as admin?
But yeah I guess could be added.

**Comment by Cokemonkey11** [comment]
> Sounds like local problems with your installation.

Definitely. Unfortunately, seems like a regression in 1.29.x as I have reinstalled a couple times with no luck. I have an open battle.net support ticket but they don't know the issue.

> The wurst started processes inherited parent permissions, try starting vscode as admin?

I believe that would work - much the same as why running worldedit as an admin works for launching test map - but I am trying to minimize the surface area of elevated permissions...

> I would say it's a bad idea to run Wurst or Warcraft as admin.

I agree, but battle.net support is saying otherwise (and even claiming the safety of worldedit function... :D ). I will keep trying to get a list of permission changes needed.

> Adding an option would suggest it's something normal to run programs as admin.

I wonder if it makes sense as a "hidden" option in run arguments file.

**Comment by Frotty** [comment]
> I wonder if it makes sense as a "hidden" option in run arguments file.

Do hidden options ever make sense? ;)
Idk, doesn't really seem like a job for wurst, and highly depends on setup.
In theory you could also create a shortcut, tick "run as admin" and tell wurst to use that?

Do we still need this ticket?

**Comment by Cokemonkey11** [comment]
Yes, I still run vscode, worldedit, and wc3 with elevated permissions, which is dangerous.

I haven't raised this issue at blizzard apart from battle.net support (who are clueless).

I think the manual process of creating a shortcut file and making wurst use that as launcher is too much jank for "potentially all windows 7 users at 1.29+" to cope with - don't you think?

**Comment by Frotty** [comment]
It's fine - you seem to be the only one having the issue.

**Comment by Cokemonkey11** [comment]
I think if we have at least one empirical example of a user with windows 7 and doesn't have this problem on 1.29 then I'm happy with no change

**Comment by Frotty** [comment]
We have plenty win7 users that don't have this issue

**Comment by Cokemonkey11** [comment]
I would feel more comfortable with an example of an actual individual but ok
