### ISSUE TITLE
What error???

### ISSUE THREAD

**Issue by LLRukia** [wurstscript/WurstScript#680]
java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement (E:\WurstProject\BossForWarcraftIII\wurst\Base\BaseSkills.wurst:13): must not happen Please open a ticket with source code and the error log.

This is my file which threw the error:
package BaseSkills

```
public abstract class IBaseSkills
    protected unit m_self_unit
    protected trigger m_tr_self
    construct(unit u)
        this.m_self_unit = u
        this.m_tr_self = CreateTrigger()
    ondestroy
        DisableTrigger(this.m_tr_self)
        DestroyTrigger(this.m_tr_self)



    abstract function cast()

    abstract function listen()
```

I can run my project on another computer.

 Please check attachment about compile log and language server log.
[compiler.log](https://github.com/wurstscript/WurstScript/files/2127748/compiler.log)
[languageServer.log](https://github.com/wurstscript/WurstScript/files/2127749/languageServer.log)

**Comment by Frotty** [comment]
Please pastebin logs, don't upload them :)
This bug has already been addressed.
Please make sure your compiler is up to date before you report bugs.
Cheers
