### ISSUE TITLE
CASC support (1.30)

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#684]
When 1.30 exits PTR*, some object data will be present in CASC instead of MPQ.

Wurst compiler and tools should transparently select the right archives and libraries for sourcing data from CASC or MPQ archives.

\* assuming nothing changes from present PTR 1.30

**Comment by Cokemonkey11** [comment]
https://www.hiveworkshop.com/threads/stop-the-casc-madness.306917/

**Comment by Frotty** [comment]
What wurst-relevant data is inside the casc archives?
Someone probably needs to do a Java port of https://github.com/ladislav-zezula/CascLib then, but I'm not gonna.

**Comment by Cokemonkey11** [comment]
> What wurst-relevant data is inside the casc archives?

I don't know, but it will become more relevant soon.

> Someone probably needs to do a Java port of https://github.com/ladislav-zezula/CascLib then, but I'm not gonna.

I guess you mean a JVM port. I would be surprised if there's really no opensource JVM CASC library in any form...

**Comment by Krypt0n** [comment]
maybe there could be mpq to casc converter so wurst can still use the normal mpq data, but i guess that would be almost the same effort like implementing a casclib for wurst

**Comment by Frotty** [comment]
See https://github.com/DrSuperGood/JCASC
