### ISSUE TITLE
Stack trace inaccuracies on runtime error

### ISSUE THREAD

**Issue by Halithor** [wurstscript/WurstScript#686]
While using the data structures in the standard library I encountered an issue with the stacktraces I was getting. While certain statements are valid, the stacktrace points to them as the issue, when real cause of the error is  the next line. 
Example code:
```wurst
package Hello

import HashMap
import LinkedList
import HashSet

constant map = new HashMap<int, LinkedList<int>>
constant activeUnits = new HashSet<unit>()

init
	activeUnits.add(createUnit(players[0], 'hfoo', vec2(0, 0), (0).asAngleDegrees()))
	for LinkedList<int> someList in map.get(1)
		print("thing")
```
[Pastebin](https://bin.wurstlang.org/ataxudakes.wurst)

Error:
![](https://i.imgur.com/iXw1ykJ.jpg). 

It points to the HashSet.add() call, when really the issue is that the HashMap.get() call is returning null on the next line.

Placing that code into a Hello package in the template project should reproduce the error. Using compiler build 845.

**Comment by peq** [comment]
Pushed some commits to improve it, but have not checked if it works as intended in the game.

**Comment by Frotty** [comment]
@Halithor Can you rerun this test and see how the trace changed?

**Comment by peq** [comment]
Looks better now:

![](https://i.imgur.com/SZP4qyw.png)

First and last line of the stacktrace could still be improved, but I think that is a different issue.
