### ISSUE TITLE
Object Generation Ids become incorrect

### ISSUE THREAD

**Issue by cljnilsson** [wurstscript/WurstScript#687]
I am currently generating every single custom object in a map of mine.
I want to generate everything in a single file, but that becomes troublesome since some units references buildings, some buildings reference units and so on.

I solved this by having a list of generated ids which is then imported into abilities.wurst, units.wurst and so on.

This works fine - mostly, seemingly randomly some units have the incorrect abilities.
This fixed itself after working on the map further for a while but now it also happened for my units.

I am making a custom techtree and now the initially spawned workers are ghouls rather than the intended acolytes. And a ziggurat is spawned instead of a necropolis. 

id generation file: https://bin.wurstlang.org/utinuceyof.wurst
Which prints: https://i.gyazo.com/beb1c9f466533d4a20a4ccce37ece72c.png
Generation: https://bin.wurstlang.org/zefihiranu.wurst
WurstRunMap: https://i.gyazo.com/c4fc88acaf116f6f749b16c7626af010.png

"necropolis" is generated first in the id file yet "zigurat" has the first id, I do not feel like it should matter but it seems to :-/

I'd love to think I am just retarded and just doing something wrong, but it literary spawned the correct unit minutes ago, and has for days. And I did not change anything in the spawn related files

**Comment by Frotty** [comment]
Please check https://wurstlang.org/blog/bestofthewurst3.html in perticular #object editing 101

This is a user error. The way you are generating your ids, it can have different orders of execution between runtime/compiletime and therefore you get "random" errors.

Easiest solution would be to use compiletime expression as shown in the blog.

**Comment by cljnilsson** [comment]
I suspected it was a user error but I could not seem to find a common thread in the randomness.

That compiletime function was the error, thanks.
