### ISSUE TITLE
VScode suggest me invisible private function to Auto-complete

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#689]
_From @vitalexbel on June 28, 2017 13:50_

```
public class Word
    Partner creator

    function add()
        creator.stats.recalcPoints()

public class Partner
    Stats stats

public class Stats
    private function recalcPoints()
```

![screenshot_11](https://user-images.githubusercontent.com/29229748/27640203-3cf82cf6-5c21-11e7-9c5a-2aafa1545c86.png)
![screenshot_7](https://user-images.githubusercontent.com/29229748/27640078-e3ed8610-5c20-11e7-9583-e023b6771557.png)
![screenshot_8](https://user-images.githubusercontent.com/29229748/27640079-e3ee202a-5c20-11e7-8646-122f9681eb4b.png)
![screenshot_9](https://user-images.githubusercontent.com/29229748/27640109-012dd608-5c21-11e7-9fee-7e0a4aca77d5.png)

_Copied from original issue: wurstscript/wurst4vscode#24_

**Comment by Frotty** [comment]
autocomplete is part of the compiler, this ticket should be moved.
IIRC this was on purpose, so that even if a function is private by mistake, or not yet imported, you can find it, and perhaps apply the import quickfix. As shown in the screenshot, it should be ad a lower position.

The thing that could change, would be a different icon or so.

**Comment by peq** [comment]
No, it was not on purpose. Probably broke, when I did the type refactoring.
