### ISSUE TITLE
Runmap fails on linux with wine on a non-english locale

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#692]
**Describe the bug**
As described by the rrvbtvs(?) guy in channel yesterday the path calculated here:

https://github.com/wurstscript/WurstScript/blob/f0d6d720ffdcacc89e1b8f2175f550f642c78dbf/de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java#L175

Was locale insensitive.
I attempted a fix by using the document's folder local name, but it doesn't seem to work with wine or whatever.

@peq maybe help testing tonite :)

**Comment by Frotty** [comment]
Okay seems to be a wine issue on certain setups.
"My Documents" is actually a windows symlink and would work on different locales,
but in this case the symlink wasn't pointing to the wine user's documents folder, but instead the linux user's. I don't think there really is a fix from our side for this.

As a workaround there has been the
`-runmapTarget <Path to the folder that contains the Maps folder>`
argument for some time now.
Closing this.

**Comment by Cokemonkey11** [comment]
Is there any reason actually that the My Documents symlink must be used instead of the actual directory?
