### ISSUE TITLE
Generic abstract class inheritance issue

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#697]
When a class inherits generic abstract class, compiler seems unable to find out variables in the generic abstract class.
![image](https://user-images.githubusercontent.com/10547551/43044800-c22ddd3a-8ddf-11e8-8043-02d03e75d2dd.png)
Compiler build for me is 863.

**Comment by peq** [comment]
As a workaround you can try writing `this.someInt`. Will try to fix it soon.
