### ISSUE TITLE
Local optimizations take forever to complete on 24-player maps with 2 forces

### ISSUE THREAD

**Issue by ElusiveMori** [wurstscript/WurstScript#700]
Steps to reproduce:

1. Make a 24-player map like this:
![1](https://i.imgur.com/Ps1p01J.png)

2. Make 2 forces like this:
![2](https://i.imgur.com/yPd6DTC.png)

Saving this map in WorldEdit produces this monstrosity of a function:
https://pastebin.com/JED2J7V3

If inlining is turned on, this gets turned into an even bigger monstrosity:
https://pastebin.com/r3kURDAY

That is **4 thousand lines of JASS code.**

If you now turn on local optimizations, it takes forever for them to actually run, compared to 2-4 seconds on normal 12-player maps (or a 24-player map with no forces). If you remove these 2 forces, everything goes back to normal.

I don't know how this bug should be addressed, but it can be a major pain for maps with 24 players where 2 or more forces are involved. I like compiling with all optimizations enabled because even on my big project (15k lines of optimized jass emitted) it doesn't take too long to finish, with 90% of stdlib imported. But this function, it just can't regurgitate.

One of the safer options would be to just disable optimizations on the `config` function directly, since it only runs once per map and hardly needs optimization at all. I don't think anyone would suffer from it.

**Comment by Frotty** [comment]
Idk, did you highly exaggerate here?
Takes like 10-15 seconds instead of 5-10 for me.
Really not critical.

**Comment by Frotty** [comment]
has been fixed by #1024
