### ISSUE TITLE
Can't build the map since war3map.j file contains keyword/built-in-type in wurst

### ISSUE THREAD

**Issue by luoshui9** [wurstscript/WurstScript#702]
I am still having some legacy Jass. When I try to build a map with these code, I can't build the map because wurst says I can't use "mod" as an argument name or tried to declare "int" as a variable name in j file.

**Comment by Frotty** [comment]
Paste your .j file then. https://bin.wurstlang.org

**Comment by luoshui9** [comment]
https://bin.wurstlang.org/bufixenihe.wurst

**Comment by Cokemonkey11** [comment]
In wurst, `mod` and `int` are reserved keywords, so you must rename those variables to something else

**Comment by Frotty** [comment]
> In wurst, mod and int are reserved keywords, so you must rename those variables to something else

In a .wurst file, yes. In a .j file they should in theory be accepted.

**Comment by Frotty** [comment]
should be fixed now 💎
