### ISSUE TITLE
Package Namespaces / Field Of View

### ISSUE THREAD

**Issue by DoctorRyner** [wurstscript/WurstScript#707]
You can have some variables or classes or enums in the different packages with the same names like in these screenshots

<img width="442" alt="2018-08-10 1 58 27" src="https://user-images.githubusercontent.com/24430919/43925621-257f9daa-9c41-11e8-879d-5d7800e7b29a.png">
<img width="442" alt="2018-08-10 2 00 59" src="https://user-images.githubusercontent.com/24430919/43925653-40d13528-9c41-11e8-8859-9fb37c64c3a8.png">

Is there an implementation of field of view? How can I differ one class Config from Config of another package?

My temporal solutions is:
<img width="772" alt="2018-08-10 2 02 19" src="https://user-images.githubusercontent.com/24430919/43925732-869a4a54-9c41-11e8-826b-60df3372142d.png">
<img width="497" alt="2018-08-10 2 02 24" src="https://user-images.githubusercontent.com/24430919/43925736-89426d04-9c41-11e8-8c2e-ca7a1ef51250.png">
<img width="401" alt="2018-08-10 2 02 44" src="https://user-images.githubusercontent.com/24430919/43925737-8c351886-9c41-11e8-836d-ad079b814e7a.png">

But that is a shitty solution, can you implement something like this?
<img width="295" alt="2018-08-10 2 06 35" src="https://user-images.githubusercontent.com/24430919/43925920-2479c164-9c42-11e8-9098-79c39d2b2a4b.png">
<img width="339" alt="2018-08-10 2 06 44" src="https://user-images.githubusercontent.com/24430919/43925923-27f9f75a-9c42-11e8-8eec-0352d0eed07f.png">

Or might be I missing something?

**Comment by DoctorRyner** [comment]
Do you suggest me to use names like Script_Name_Config in the class Config example to differ them? If that is then its ok (maybe), but "namespaces" is an important and useful feature

**Comment by Frotty** [comment]
yes, `RukiaWConfig` in this case. packages are namespaces, but there is no way to strictly reference elements with same name.

**Comment by DoctorRyner** [comment]
Oh, thats unfortunate but thanks for you reply

**Comment by peq** [comment]
This is definitely something we want to support in a future Wurst version. One suggestion (using qualified names) is tracked in #250. Another solution would be to allow renames in the import statements as you can do in Scala or Haskell.

```
import Rukia_W {Config -> Config_W}
import Rukia_Q {Config -> Config_Q}
```
