### ISSUE TITLE
Import error not updating correctly on file remove/add

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#711]
Say we have package `R` which imports an unknown package. The import line throws an error as expected.
```
package R
import A // <-- error
```
If we now add `A.wurst` we are inside the A package and the import error has gone away, without needing to re-save the file. (As expected 👍)
**But** if we now remove the `A.wurst` package, the import in package `R` will **not** throw an error, __unless__ I re-save the file or clean the workspace. (Bad 👎 )
Also, if I now add `A.wurst` again, the import Error will not automatically go away, like it did the first time.  (Also bad 👎 )

**Note** At this point not even a re-save or clean of the workspace fixes the error. Only reloading the window.
![ ](https://i.imgur.com/bnQWXdY.png)

edit: The same happens when renaming a package. The import error doesn't update properly.

**Comment by peq** [comment]
Should be fixed with 516241971ef906a5563669451482f590140b30e6. If not please try to add a testcase to `ModelManagerTests` ;)
