### ISSUE TITLE
Moving packages breaks JumpToDecl

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#712]
Consider following package. We can Jump to the Test package via the import.
```
package A
import Test
```
We now move package `Test` into a different folder. Jump to decl doesn't work anymore and can cause following error:
```
Unable to open 'Test.wurst': File not found (file:///c:/Users/Frotty/Documents/GitHub/Castle Siege Deluxe/wurst/spawning/Test.wurst).
```

**Comment by peq** [comment]
Should be fixed with 516241971ef906a5563669451482f590140b30e6. If not please try to add a testcase to `ModelManagerTests` ;)
