### ISSUE TITLE
wurst:Run in fullscreen

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#714]
The topic. Is it possible?

**Comment by Frotty** [comment]
soon

**Comment by Frotty** [comment]
btw, you know you can switch to fullscreen on the fly using `alt + ENTER` right?

**Comment by Frotty** [comment]
> Which won't set correct resolution but yes, I know.

Not sure how that's possible, if your registry is set appropriately?

Are you asking for the special `-nativefullscreen` arg that was added?

**Comment by Frotty** [comment]
possible for some time via wc3runArgs config
