### ISSUE TITLE
Autocomplete isn't showing up during function parameter input

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#715]
Compiler version build: 925

**Comment by peq** [comment]
![image](https://user-images.githubusercontent.com/1071762/44675978-422afb80-aa32-11e8-991b-a0d6043af7ce.png)
Works for me. Can you add a concrete example? It's probably some incomplete expression in your code which the parser cannot handle.

The most useful bug report for Autocomplete would include a minimal testcase as in https://github.com/wurstscript/WurstScript/blob/master/de.peeeq.wurstscript/src/test/java/tests/wurstscript/tests/AutoCompleteTests.java .

**Comment by peq** [comment]
Hmm, that also works for me:
![output](https://user-images.githubusercontent.com/1071762/44680031-ee71df80-aa3c-11e8-80d0-553e04125c32.gif)

Does it work if you invoke autocomplete with `Ctrl+space`?

**Comment by DDLegionTN** [comment]
![test](https://user-images.githubusercontent.com/10547551/44699537-45b49600-aab7-11e8-83fe-304717df6446.gif)
Works with `Ctrl+space`

[languageServer.log](https://github.com/wurstscript/WurstScript/files/2326416/languageServer.log)
Log attached in case you would need it.

**Comment by SamuelMoriarty** [comment]
I have seen this occur occasionally as well.
It's very hit-and-miss. Most of the times it works, sometimes it doesn't. I'll try to pay more attention and see if I can make steps to reproduce.

**Comment by DDLegionTN** [comment]
Since there is no more brackets adding to auto-complete function anymore, so i guess this issue is no longer an issue and can be closed?

**Comment by Frotty** [comment]
Closing this stale issue. If this still occurs in a reproducible manner, feel free to open a new ticket.
