### ISSUE TITLE
Function suggestion for function overloading

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#722]
![image](https://user-images.githubusercontent.com/10547551/45068720-6f933b80-b0fb-11e8-9e26-1f2199de24ec.png)
Suggested function overloading should match to the best match of the function but not suggesting the first function.

**Comment by peq** [comment]
Hmm, currently it first filters by parameter number and then by matching types. That is of course not very useful when you are not finished writing down all arguments, but it might be better if you used autocomplete where the number of arguments is already correct but the types are not yet known.

I think the vscode UI also supports showing all overloads in the parameter info, but that is a bit more work to implement.

**Comment by DDLegionTN** [comment]
Right. Since the time there is no defined arguments when I used autocomplete as no brackets will be added. Now this problem should be insignificant after the fix.
