### ISSUE TITLE
StringIndexOutOfBoundsException for toCharsetString()

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#728]
```
package Test

import ObjectIdGenerator

@compiletime function a()
    ABIL_ID_GEN.next().toCharsetString()
```

![image](https://user-images.githubusercontent.com/10547551/45637643-954a1880-badd-11e8-94e4-a287ae41fa76.png)

**Comment by peq** [comment]
You probably wanted to use  `toRawCode` from the `ObjectIds` package. `toCharsetString` is for converting a single character only. The naming of that function is not optimal, but I am not sure if it is worth changing.

What do you think @Frotty ?

**Comment by Frotty** [comment]
Yes, should probably `error` instead of returning -1 on invalid input.
