### ISSUE TITLE
forUnitsAll always throws an error

### ISSUE THREAD

**Issue by Kyromyr** [wurstscript/WurstScript#736]
Error: `Called ForGroupCallback.ForGroupCallback on invalid object.`

```
	forUnitsAll() u ->
		skip
```

**Comment by Frotty** [comment]
Thanks for the report, i pushed a [fix](a416352d15eb92abf99c7f82ffae92690cc008f9) 👍 
Update your project using the setup tool to receive it.

Btw this is a [standard library](https://github.com/wurstscript/WurstStdlib2) issue, please post further tickets in the appropriate repository.
