### ISSUE TITLE
Missing error when initializing dynamic array class member

### ISSUE THREAD

**Issue by Meai1** [wurstscript/WurstScript#740]
`You encountered a bug in the interpreter: java.lang.Error: wrong number of parameters when calling func Conflagration_genObj()`

I got this bug after trying to work around the other bug that doesnt allow tuples, so I just use flat ints now but now the new bug.

I think all I changed was from this with tuples:

```
    public tuple point(int x, int y)
    point array[6] MY_IDS_BTNPOS = [
        point(0, 2),
        point(1, 2),
        point(2, 2),
        point(3, 2),
        point(1, 1),
        point(2, 1)
    ]
// ..presetButtonPosNormal(MY_IDS_BTNPOS[i].x, MY_IDS_BTNPOS[i].y)
```

to this:
```

  int array[6] MY_IDS_BTNPOS = [
        0, 2,
        1, 2,
        2, 2,
        3, 2,
        1, 1,
        2, 1
    ]

// ..presetButtonPosNormal(MY_IDS_BTNPOS[i], MY_IDS_BTNPOS[i+1])
```

[wurst (2).zip](https://github.com/wurstscript/WurstScript/files/2495323/wurst.2.zip)

**Comment by peq** [comment]
Wurst now gives a compilation error if a non-static method is annotated with `@compiletime`.
