### ISSUE TITLE
Ambiguous reference with identical location

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#742]
Reference to type Escaper is ambiguous. Alternatives are:
 * class Escaper defined in line 40 (C:\Users\Frotty\Documents\GitHub\EBR\wurst\escaper\Escaper.wurst)
 * class Escaper defined in line 40 (C:\Users\Frotty\Documents\GitHub\EBR\wurst\escaper\Escaper.wurst)

**Comment by peq** [comment]
Please include steps to reproduce (project revision numbers, which file was edited when the error occurred, ...)

**Comment by Frotty** [comment]
Idk, it happens irregularly - so i don't have steps to reproduce. Sometimes i reloaded the did appear, sometimes didn't. 
We should add some more logging perhaps

**Comment by Frotty** [comment]
It still occurs from time to time in extended coding sessions, but I have no way of reproducing it yet from a clean state easily. Will open a new ticket if I can.
