### ISSUE TITLE
Improve compilation speed

### ISSUE THREAD

**Issue by peq** [wurstscript/WurstScript#743]
Here is an overview of the compilation times for EBR for the different phases when compiled with `-runcompiletimefunctions  -stacktraces -inline -localOptimizations -measure`.

```
parse files: 5592ms
Typecheck program: 6296ms
Translate program to Im: 1347ms
 to intermediate lang: 1347ms
Run compiletime functions: 1180ms
Transform program to Jass: 46558ms
 translate classes: 409ms
 add stack traces: 12706ms
 inlining: 1025ms
  inline functions: 987ms
 eliminate tuples: 1197ms
 remove func refs: 14ms
 remove cyclic functions: 1228ms
 flatten: 190ms
 local optimizations: 29150ms
  Constant and Copy Propagated: 1295ms
  Useless function calls removed: 592ms
  Globals Inlined: 417ms
  Branches merged: 7114ms
  Simple Rewrites: 2668ms
  Temp variables merged: 2981ms
  Local variables merged: 12214ms
 null setting: 281ms
 translate to jass: 256ms
Print Jass: 104ms
Run PJass: 708ms
```

It looks like "add stack traces" , " Local variables merged", "Temp variables merged",  "Branches merged" would be good targets to make faster.

**Comment by Frotty** [comment]
I think it would be nice if we could setup a test suite of some wurst resources (stdlib, fdef. ebr. itt) and then let jenkins compile it with master and the opt-branch so we can directly see and validate changes made.

**Comment by peq** [comment]
Current state:

```
parse files: 5324ms
Typecheck program: 7020ms
Translate program to Im: 1585ms
 to intermediate lang: 1585ms
Run compiletime functions: 1232ms
Transform program to Jass: 25817ms
 Eliminate generics: 152ms
 translate classes: 314ms
 add stack traces: 504ms
 inlining: 1307ms
 eliminate tuples: 506ms
 remove func refs: 18ms
 remove cyclic functions: 318ms
 flatten: 68ms
 local optimizations: 22105ms
  Constant and Copy Propagated: 1221ms
  Useless function calls removed: 738ms
  Globals Inlined: 352ms
  Branches merged: 303ms
  Simple Rewrites: 1441ms
  Temp variables merged: 2162ms
  Local variables merged: 14466ms
 null setting: 226ms
 translate to jass: 286ms
Print Jass: 147ms
Run PJass: 179ms
```

Probably also helped that some debug checks are disabled by default now.

**Comment by Frotty** [comment]
should display sum after the value so we can see where the times differ. Typecheck seems to take 1000ms longer almost e.g.
I will run this also and post results.

**Comment by Frotty** [comment]
I think the JVM would need to be warmed up and have enough heap to not cause any garbage collection during build to produce useful results.
Right now without opimizations I get heavy fluctuations of up to 1000ms in most tasks, e.g. `Transform program to Jass`
and `Run compiletime functions` (900 vs 1600).

**Comment by Frotty** [comment]
Several performance improvements have been done, builds are now much faster. If you still have specific performance bottlenecks open a separate ticket with measurements and reproduction map/project.
