### ISSUE TITLE
Translation Error : Cannot convert null to int

### ISSUE THREAD

**Issue by DDLegionTN** [wurstscript/WurstScript#744]
```
function foo<T>(T t)

init
    foo(null)
```
![image](https://user-images.githubusercontent.com/10547551/47407053-e1971100-d78b-11e8-8d88-49be60b5869c.png)

**Comment by Frotty** [comment]
Missing "cannot infer type of null" error I guess.
Or did you expect this to work?

**Comment by DDLegionTN** [comment]
Was working before (forgot compiler version), now when i tried to recompile such error happen.

**Comment by peq** [comment]
Maybe you can post your real use case. I fixed the example, but there might be more complex situations that are still broken.

**Comment by peq** [comment]
PS: probably was broken in earlier compiler versions too, but now Pjass is run by default again.
