### ISSUE TITLE
Pjass has found the following problem:  Undeclared function BlzSetUnitAbilityManaCost

### ISSUE THREAD

**Issue by anufis** [wurstscript/WurstScript#745]
Getting this error while compiling after last update.

This is a bug in the Wurst Compiler. Please Report it. Pjass has found the following problem:  Undeclared function BlzSetUnitAbilityManaCost. Maybe you meant BlzGetUnitAbilityManaCost or BlzGetAbilityManaCost

-noPJass argument in wurst_run.args fixes the problem.

**Comment by Frotty** [comment]
Looks like the function is not part of the mainline common.j
Are you on PTR?

**Comment by Frotty** [comment]
@nvm link/pr ? 🍨

**Comment by nvs** [comment]
These are what I was using on my bots during that patch, so they should have the same checksum as those within the MPQ (if that matters to you):

- [scripts-1.29.2.zip](https://github.com/wurstscript/WurstScript/files/2512441/scripts-1.29.2.zip)

**Comment by Frotty** [comment]
Literally the only difference is that one function 😅 
Thanks!
