### ISSUE TITLE
EVENT_DIALOG_BUTTON_CLICK missing?

### ISSUE THREAD

**Issue by Meai1** [wurstscript/WurstScript#746]
Error:
![grafik](https://user-images.githubusercontent.com/1112157/47425208-f377b480-d789-11e8-90d4-03df2bf0339b.png)

Code:
```
EventListener.add(EVENT_DIALOG_BUTTON_CLICK) ->
    print("test")
```

How else can I make a dialog? Same error if I use `EVENT_DIALOG_CLICK`.

**Comment by Frotty** [comment]
1. This is a [standard library](https://github.com/wurstscript/WurstStdlib2) issue

2. Use [DialogBog](https://github.com/wurstscript/WurstStdlib2/blob/200f171296d017d262aec8ad67b3962cdedd4e67/wurst/util/DialogBox.wurst)
