### ISSUE TITLE
@inline and empty return statements

### ISSUE THREAD

**Issue by bobokvsky** [wurstscript/WurstScript#748]
There is a simple idea. I wan't stop actions of some trigger when it needed. For example, there is the next code:

```
@inline public function triggerSleepAction(real time)
    if someCondition()
        return
    else
        TriggerSleepAction(time)

function triggerActions()  // running triggerly
    print("This msg appears.")
    triggerSleepAction(5.0)
    print("This msg shouldn't appear")
```

I expected that `@inline` would insert code into `triggerActions()` like that:
```
function triggerActions takes nothing returns nothing
	local string msg = "This msg appears."
	local string msg_2
	call DisplayTimedTextToPlayer(Player_localPlayer, 0., 0., 45., msg)
	if someCondition() then
		return
	else
		call TriggerSleepAction(5.0)
	endif
	set msg_2 = "This msg shouldn't appear"
	call DisplayTimedTextToPlayer(Player_localPlayer, 0., 0., 45., msg_2)
endfunction
```
So the second message shouldn't appear when someCondition() returns true.

In fact, Wurst compiles the code into that:
```
function triggerSleepAction takes real time returns nothing
	if someCondition() then
		return
	else
		call TriggerSleepAction(time)
	endif
endfunction

function startGame takes nothing returns nothing
	local string msg = "This msg appears."
	local string msg_2
	call DisplayTimedTextToPlayer(Player_localPlayer, 0., 0., 45., msg)
	call triggerSleepAction(5.0)
	set msg_2 = "This msg shouldn't appear"
	call DisplayTimedTextToPlayer(Player_localPlayer, 0., 0., 45., msg_2)
endfunction
```

The second message appears regardless of what the function `someCondition()` returns, so my idea doesn't work.

I think, `@inline` should be inproved so that empty `return` statements would be inlined into code too. It would be great!

**Comment by Frotty** [comment]
The inliner can only handle functions with a single return statement, and this won't change.
Make your function contain only one return by using a temp variable, and it will be inlined.

**Comment by bobokvsky** [comment]
Of course I know that `TriggerSleepAction` is a bad thing. I'm using this function with timers like did in `PolledWait`, and of course in many causes I use timers instead.

The problem is that I really need return statements to the `triggerActions`. Idea is good because I can write whole code of some, for example, whole linear dungeon, in one function, not even using closures and new functions that add some unreadability and more tabs. I use for it trigger-run actions and construction like `waitUntilHeroesKillsBoss()` like that:
```
public function waitUntilHeroesKillsBoss(unit whichBoss)
    while whichUnit.isAlive()
        triggerSleepAction(bj_POLLED_WAIT_INTERVAL)
```
The problem is I wan't stop further trigger-run actions if some Heroes are all dead (this is what `someCondition()` returns, for example), clear all objects in dungeon and re-run the dungeon again from the beginning.
So the `return` statements are really needed in this case, and I thought `@inline` would make it. But... your solution doesn't work. 

The second message is still appearing. Is there nothing I can do here except manually inline the functions by hands or changing code in compiler to do so? :(

**Comment by Frotty** [comment]
I think your solution is needlessly complicated and misguided - if you think you require such a specific feature it is much more likely there is a different, better suited solution to your problem.
If you don't want to go that route for "unreadability and more tabs", I'm not sure expect.

**Comment by peq** [comment]
I think the feature you need would be continuations or generator functions, which Wurst does not support at the moment. 

You could try to create a fluent API using closures, so that you can write something like:

```
function triggerActions()
    do(() -> print("mesage 1."))
        .thenWait(5.seconds())
        .then(() -> print("message 2"))
        .thenWait(2.seconds())
        .then(() -> print("message 3"))
```

Or you could nest closures and write something like:

```
function triggerActions()
    print("mesage 1.")
    after(5.seconds()) ->
        print("message 2")
        after(2.seconds()) ->
            print("message 3")
```
