### ISSUE TITLE
ThunderBolt

### ISSUE THREAD

**Issue by N1ghtSiren** [wurstscript/WurstScript#751]
**Hidden stun**
AbilityDefinitionMountainKingThunderBolt -> setBuffs -> Not clearing default stun, but adds our buff
*    Creating spell:

    new AbilityDefinitionAuraSlow('B0A0')
    ..setTooltipNormal(1,"Archer's Test Spell")
    ..setTooltipNormalExtended(1,"TooltipNormalExtended|n|n|n|nArcher's Mark ")
    ..setIconNormal("ReplaceableTextures\\CommandButtons\\BTNAncientOfTheMoon.blp")`

    new AbilityDefinitionMountainKingThunderBolt('A0A0')
    ..setName("BuffPlacer: ArcherMark")
    //..setBuffs(1,"B0A0") //Our buff disabled
    ..setDurationHero(1,5)
    ..setDurationNormal(1,5)
    ..setLevels(1)
    ..setTargetsAllowed(1,"all")
![wc3scrnshot_110318_024735_01](https://user-images.githubusercontent.com/33629215/47942252-1e44d400-df13-11e8-95e8-2732f9496c9b.png)
*    It's become stunned for 5 seconds.

*    Buff enabled:

    new AbilityDefinitionAuraSlow('B0A0')
    ..setTooltipNormal(1,"Archer's Test Spell")
    ..setTooltipNormalExtended(1,"TooltipNormalExtended|n|n|n|nArcher's Mark ")
    ..setIconNormal("ReplaceableTextures\\CommandButtons\\BTNAncientOfTheMoon.blp")`

    new AbilityDefinitionMountainKingThunderBolt('A0A0')
    ..setName("BuffPlacer: ArcherMark")
    ..setBuffs(1,"B0A0") //Our buff Enabled
    ..setDurationHero(1,5)
    ..setDurationNormal(1,5)
    ..setLevels(1)
    ..setTargetsAllowed(1,"all")
![wc3scrnshot_110318_025141_02](https://user-images.githubusercontent.com/33629215/47942412-aa56fb80-df13-11e8-9005-846ef8f624dd.png)
*    It's become stunned for 5 seconds without animation overhead and 'BPSE' buff .

*    Lets clear all buffs:

    new AbilityDefinitionAuraSlow('B0A0')
    ..setTooltipNormal(1,"Archer's Test Spell")
    ..setTooltipNormalExtended(1,"TooltipNormalExtended|n|n|n|nArcher's Mark ")
    ..setIconNormal("ReplaceableTextures\\CommandButtons\\BTNAncientOfTheMoon.blp")`

    new AbilityDefinitionMountainKingThunderBolt('A0A0')
    ..setName("BuffPlacer: ArcherMark")
    ..setBuffs(1,"") //All buffs cleared
    ..setDurationHero(1,5)
    ..setDurationNormal(1,5)
    ..setLevels(1)
    ..setTargetsAllowed(1,"all")
![wc3scrnshot_110318_024735_01](https://user-images.githubusercontent.com/33629215/47942252-1e44d400-df13-11e8-95e8-2732f9496c9b.png)

*    Default Stun appears.

Please, rework that, or give temprorary solution how to add buffs, which will be visible by players.
Only one thing i see for now - Use WE to create spells.

**Comment by N1ghtSiren** [comment]
* wc3 version - 1.26

**Comment by anufis** [comment]
You are doing it wrong. You need to create buff for your ability, but instead of that you create Torando aura ability. So you pass not buff, but ability as buff to your stun ability.

You need something like this for buff

`new BuffDefinition(buffId, 'Basl')
			..setName(1, name)
			..setTooltipNormal(1, name)
			..setTooltipNormalExtended(1, tooltip)
			..setIcon(iconpath)`

**Comment by N1ghtSiren** [comment]
Aw, thank you

**Comment by Frotty** [comment]
Hi, I am only seeing this now.
If you want to create dummy buffs, you should use `createDummyBuffObject` which creates the aura dummy and the real ability for you.
