### ISSUE TITLE
bug:Unable to prompt nested class fields

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#753]
```
public class SchoolSpell
    static let qinyun   = new QINYUN()
    static class QINYUN
        let leiyunjianqi  = '0000'// 绝技：雷云剑气 被动
        let xuanbinjinqi  = '0000'// 绝技：玄冰劲气 被动
        let zhanguishen   = '0000'// 绝技：斩鬼神 被动
        let shenjianyulei = '0000'// 绝技：神剑御雷
init
    let a = SchoolSpell.qinyun. //cant tip the fields
```

**Comment by PhoenixZeng** [comment]
In fact, manually writing the following contents can be compiled, so I think this is a plug-in problem.

**Comment by Frotty** [comment]
> In fact, manually writing the following contents can be compiled

Not sure what you mean. Compilation and auto complete are 2 different tasks in the language server, which are both in this repository. The plugin only requests a list of suggestion items from the language server and then sends it to vscode. No real computing logic happens in the plugin. If nothing is shown means the lang server is returning an empty list of suggestions, which should be addressed here.

**Comment by PhoenixZeng** [comment]
> In fact, manually writing the following contents can be compiled
mean this can be compiled and run .
```
public class SchoolSpell
    static let qinyun   = new QINYUN()
    static class QINYUN
        let leiyunjianqi  = '0000'//
init
    let a = SchoolSpell.qinyun.leiyunjianqi  
    print(a)
```
> Compilation and auto complete are 2 different tasks in the language server
thanks
