### ISSUE TITLE
bug: error tip `never read.`

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#756]
```
class aa
    static unit array hero
    static function getTargetHero ( integer id ,real range,bool lock)
        unit hero1 = hero[id]
        real hP = 0.  // green line on this var .tip never read
        real dis = 0. // green line on this var
        group G = CreateGroup()
        for u from G
            hP = GetUnitState(u,UNIT_STATE_LIFE)
            if hP > 0.405
                if lock == false
                    dis = hero1.getPos().distanceTo(u.getPos())
                    if dis < 0
                else
                    if hP < 0
```
plugin tip:
The assignment to local variable dis is never read.

**Comment by PhoenixZeng** [comment]
It comes from a system modified by the vjass system, and I deleted a lot of it, which makes the function look meaningless. But it's enough to show the problem.

**Comment by Frotty** [comment]
Because it isn't. The `0.` in your variable is never accessed because you always assign `hP = GetUnitState(u,UNIT_STATE_LIFE)` before you acces it. This is a legit warning. Remove ` = 0.` to fix.

**Comment by PhoenixZeng** [comment]
oh. i see.
I erroneous thought that the variable was not used. I didn't expect the value to be unused.
