### ISSUE TITLE
If you specify "bla.w3x" in wurst.build file, you'll get a filename bla.w3x.w3x

### ISSUE THREAD

**Issue by Cokemonkey11** [wurstscript/WurstScript#763]
all in the title

**Comment by Frotty** [comment]
then remove .w3x?

**Comment by Cokemonkey11** [comment]
Seems like it would be easy to detect this and avoid in wurstscript

**Comment by Frotty** [comment]
Then closing as duplicate of https://github.com/wurstscript/WurstScript/issues/699
