### ISSUE TITLE
Unexpected ordering in `initGlobals` function

### ISSUE THREAD

**Issue by nvs** [wurstscript/WurstScript#773]
When providing Jass files to Wurst (`1.8.0.0-42aa66f8`) I encounter the following behavior with respect to the handling of globals within the produced `initGlobals` function. It should be noted that adding either of the optimization options `-inline` or `-localOptimizations` produces code that does not exhibit the same behavior. The ordering of the input files seems to matter as well.

In the following example, I would expect to find `A` after both `B` and `C` within the `initGlobals` function. However, it is not.

Run: `java -jar ~/.wurst/wurstscript.j -out output.j a.j bc.j main.j common.j blizzard.j`.

`a.j`:
```jass
globals
    integer A = GetRandomInt (B, C)
endglobals
```

`bc.j`:
```jass
globals
    integer B = 2
    integer C = 3
endglobals
```

`main.j`:
```jass
function main takes nothing returns nothing
    call BJDebugMsg (I2S (A))
    call BJDebugMsg (I2S (B))
    call BJDebugMsg (I2S (C))
endfunction

function config takes nothing returns nothing
endfunction
```

`ouput.j`:
```jass
// this script was compiled with wurst 1.8.0.0-42aa66f8
globals
integer A=0
integer B=0
integer C=0
// integer bj_MAX_PLAYERS=0
endglobals
function initGlobals takes nothing returns nothing
    set A = GetRandomInt(B, C)
    set B = 2
    set C = 3
endfunction

function main takes nothing returns nothing
    local trigger initTrig
    call initGlobals()
    call BJDebugMsg(I2S(A))
    call BJDebugMsg(I2S(B))
    call BJDebugMsg(I2S(C))
    set initTrig = CreateTrigger()
    call DestroyTrigger(initTrig)
    set initTrig = null
endfunction

function config takes nothing returns nothing
endfunction
```

`output.j` (`-localOptimizations`):
```jass
// this script was compiled with wurst 1.8.0.0-42aa66f8
globals
integer A=0
// integer bj_MAX_PLAYERS=0
endglobals
function initGlobals takes nothing returns nothing
    set A = GetRandomInt(2, 3)
endfunction

function main takes nothing returns nothing
    call initGlobals()
    call BJDebugMsg(I2S(A))
    call BJDebugMsg(I2S(2))
    call BJDebugMsg(I2S(3))
    call DestroyTrigger(CreateTrigger())
endfunction

function config takes nothing returns nothing
endfunction
```

`output.j` (`-inline`):
```jass
// this script was compiled with wurst 1.8.0.0-42aa66f8
globals
integer A=0
// integer bj_MAX_PLAYERS=0
endglobals
function initGlobals takes nothing returns nothing
    set A = GetRandomInt(2, 3)
endfunction

function main takes nothing returns nothing
    local trigger initTrig
    local string msg
    local integer i
    local string msg_2
    local integer i_2
    local string msg_3
    local integer i_3
    call initGlobals()
    set msg = I2S(A)
    set i = 0
    loop
        call DisplayTimedTextToPlayer(Player(i), 0., 0., 60., msg)
        set i = i + 1
        exitwhen i == bj_MAX_PLAYERS
    endloop
    set msg_2 = I2S(2)
    set i_2 = 0
    loop
        call DisplayTimedTextToPlayer(Player(i_2), 0., 0., 60., msg_2)
        set i_2 = i_2 + 1
        exitwhen i_2 == bj_MAX_PLAYERS
    endloop
    set msg_3 = I2S(3)
    set i_3 = 0
    loop
        call DisplayTimedTextToPlayer(Player(i_3), 0., 0., 60., msg_3)
        set i_3 = i_3 + 1
        exitwhen i_3 == bj_MAX_PLAYERS
    endloop
    set initTrig = CreateTrigger()
    call DestroyTrigger(initTrig)
    set initTrig = null
endfunction

function config takes nothing returns nothing
endfunction
```

However, when swapping the order of the files around the results are different. Run: `java -jar ~/.wurst/wurstscript.j -out output.j bc.j a.j main.j common.j blizzard.j`

`output.j` (`bc.j` before `a.j`):
```jass
// this script was compiled with wurst 1.8.0.0-42aa66f8
globals
integer B=0
integer C=0
integer A=0
// integer bj_MAX_PLAYERS=0
endglobals
function initGlobals takes nothing returns nothing
	set B = 2
	set C = 3
	set A = GetRandomInt(B, C)
endfunction

function main takes nothing returns nothing
	local trigger initTrig
	call initGlobals()
	call BJDebugMsg(I2S(A))
	call BJDebugMsg(I2S(B))
	call BJDebugMsg(I2S(C))
	set initTrig = CreateTrigger()
	call DestroyTrigger(initTrig)
	set initTrig = null
endfunction

function config takes nothing returns nothing
endfunction
```

**Comment by peq** [comment]
I don't see the issue here. You include a.j before bc.j and the order in the output is the same.

Wurst does not try to automatically reorder your code.

If you use Wurst packages you can use imports to specify that A depends on BC but Jass does not have this feature.

**Comment by nvs** [comment]
The issue, as I see it, is that the in-game behavior for the code Wurst produces is not the same in all the cases. Even those where the ordering of the input files is the same.

`a.j` before `bc.j`:
- No optimization flags: `GetRandomInt (0, 0)`.
- Optimization flags: `GetRandomInt (2, 3)`.

`bc.j` before `a.j`:
- No optimization flags: `GetRandomInt (2, 3)`.
- Optimization flags: `GetRandomInt (2, 3)`.

But Wurst does automatically order Jass functions according to dependencies, and I have been leveraging this exact behavior. Although, based on what you're saying, I guess I have been using an unintended feature of Wurst? I had just assumed globals would be getting the same treatment as functions. 

And here is an example of Wurst reordering Jass functions:

`c.j`:
```jass
function C takes nothing returns nothing
    call D (10)
endfunction
```

`d.j`:
```jass
function D takes integer c returns nothing
	call BJDebugMsg (I2S (GetRandomInt (c, 25)))
endfunction
```

`main.j`:
```jass
function main takes nothing returns nothing
	call C ()
	call D (5)
endfunction

function config takes nothing returns nothing
endfunction
```

`output.j` (`c.j` before `d.j` is the same as that when `d.j` is before `c.j`):
```jass
// this script was compiled with wurst 1.8.0.0-42aa66f8
globals
// integer bj_MAX_PLAYERS=0
endglobals
function D takes integer c returns nothing
	call BJDebugMsg(I2S(GetRandomInt(c, 25)))
endfunction

function C takes nothing returns nothing
	call D(10)
endfunction

function initGlobals takes nothing returns nothing
endfunction

function main takes nothing returns nothing
	local trigger initTrig
	call initGlobals()
	call C()
	call D(5)
	set initTrig = CreateTrigger()
	call DestroyTrigger(initTrig)
	set initTrig = null
endfunction

function config takes nothing returns nothing
endfunction
```

**Comment by nvs** [comment]
As a follow up to this, it should be noted that Wurst happily accepts this (invalid) Jass within a single file.

```
globals
	integer A = B
	integer B = GetRandomInt (2, 3)
endglobals
```

And then the behavior of the Jass it emits varies depending on compiler flags. That's the crux of the issue. It seems to me that Wurst should either complain about the ordering or behave in a fashion that acknowledges that globals may be out of order. Currently, it does neither.

**Comment by Frotty** [comment]
Functions are reordered because you can generally only call functions above another in Jass.
The same does not apply to variables obviously. 

> As a follow up to this, it should be noted that Wurst happily accepts this (invalid) Jass within a single file.

Because Jass isn't parsed the way Wurst is - it can't - there is information missing such as scoping. Single Jass files don't count as packages, it's just like 1 long file split into multiple.

 **In proper wurst** you get a warning and there is a ticket for further errors.
![](https://i.imgur.com/izxoksd.jpg)

Wurst works on the premise of outputting correct Jass from wurst. Not working on and validating existing Jass.
In any case `integer A = B` will still be marked as error by pJass.

In the end it comes down to why are you  using Jass actively with wurst in the first place?
The main purpose is to read the mapscript and expose variables and functions from there, as well as maybe carrying over a few legacy scripts to update maps with wurst. Having dynamically modified .j files is simply not intended, which is why they don't dynamically reconcile.

**Comment by nvs** [comment]
Before looking into Wurst my workflow involved multiple Jass files. I did not want to use vJass, and wanted to give Jass a real go. This has remained, for now, although my plans are to shift to simply using Wurst. But the process has been slow. And yes, had I continued passing my files to PJass before sending them to Wurst, none of this would be an issue. I should probably still be doing that. But, when checking out Wurst I realized it magically reordered functions for me. I assumed, erroneously and without asking for clarification, that this extended to globals. As such, I cut PJass out of the loop since it seemed unnecessary.

That being said, using Jurst without packages seems to have the same issue as using plain Jass files (at least for global variables). Once a package is in the mix, the warning you mentioned is seen. Perhaps another option for Wurst would be to simply run supplied Jass files through PJass first? Or a stronger notification somewhere (e.g. the CLI) that this expectation should be met? Of course, this won't help with Jurst files that lack a package.

My plan now is to shift my Jass files over to Jurst and use the package system.

**Comment by Frotty** [comment]
> But, when checking out Wurst I realized it magically reordered functions for me. I assumed, erroneously and without asking for clarification, that this extended to globals.

Yes, two different things. Your example will throw a simple compilation error in most other languages and our current warning will be converted to one soon. Related to https://github.com/wurstscript/WurstScript/issues/770

> And yes, had I continued passing my files to PJass before sending them to Wurst, [...] Perhaps another option for Wurst would be to simply run supplied Jass files through PJass first? Or a stronger notification somewhere (e.g. the CLI) that this expectation should be met?

Wurst already uses pJass to check the output script, unless you disable that. You should get an error for your case. Manual usage of PJass is never expected.

> My plan now is to shift my Jass files over to Jurst and use the package system.

Yes I am wondering why you aren't using packages in the first place?

Regarding the issue I suppose the warning/error that shows packaged should simply also be shown for unpackaged jass/jurst vars. Everything else seems fine.

**Comment by nvs** [comment]
Like I said, I was planning to only use Jass, warts and all. I remained pretty steadfast in this decision for quite a while. In such a situation, I was only using Wurst as an optimizer. And to be fair, it works wonderfully. Better than the alternatives I tested.

Yeah, displaying a warning/error would certainly have made me realize that something was amiss in my use case. Sounds like a reasonable option.
