### ISSUE TITLE
Delay in removing buffs

### ISSUE THREAD

**Issue by StN-NL** [wurstscript/WurstScript#789]
It appears that the removal of buffs is delayed when using the method for adding and removing buffs from https://wurstlang.org/blog/bestofthewurst5.html

Example:
Code snippet: https://bin.wurstlang.org/epotupuwir.wurst

**Comment by Frotty** [comment]
I think the delay simply comes from the wc3 aura effect update delay.
What exactly is your issue? Do you want the blog post changed?

**Comment by StN-NL** [comment]
Not really an issue, but I thought it might be useful to have some sort of wurst function for full control over timing of the removal of a buff.
