### ISSUE TITLE
ignore function when the war3map.j have the same func-sign and return type func (maybe body)

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#793]
some time I need use the enhanced-WorldEditor(simple call it `we`)  do some like `Macro` or `pretreatment` and use some new native func

to ensure the `we` can compile success , i should make some func in `we`
to ensure the `wurst` with out coding-time error and compile-time error.  i should put some `j` file in wurst-project (Mainly for writing my own wurst Library, it need can be use in others project)

but the compiled `war3map.j` have same func with the `j` which i have put in `wurst` project will make a error. Although they are the same function

Another scenario is that it makes it easier for me to collaborate with people who don't know how to write code (like : GUI users).

Another scenario. China have more then one `wc3-platform` (Similar-like Battle.net) . they have different native function for  `net-save` ,`custom player user interface` and other. 
with out the `Macro definition` is hard to build a map witch  can be used on different   `wc3-platform`

**Comment by peq** [comment]
Not sure if this is what you need, but you can annotate functions with `@extern` and they will not appear in the output mapscript. For example:

```
@extern function blub(int x) returns int
    return 5
```

Of course Pjass will complain that there is a missing function once you call it, so you have to run with the `-noPJass` option then.

**Comment by PhoenixZeng** [comment]
i will test it

**Comment by Frotty** [comment]
> i will test it

any results?

**Comment by PhoenixZeng** [comment]
now is near the chinese new year. I am busy now. wait some days

**Comment by Frotty** [comment]
if the native is inside the war3map.j, why do you need it in your code? It's already in your code via war3map.j ? The @extern is used to refer to functions not available at compiletime.

**Comment by PhoenixZeng** [comment]
`Ydwe` automatically imports the corresponding jass Library Based on the triggers used, which leads me to wonder what functions exist in `war3map.j`. To ensure that my wurst library does not report errors on an unknown map, I need to include the functions I use in wurst file once. 
That's what I want in my title.

**Comment by Frotty** [comment]
Keep war3map.j static, prevet extraction from map and put your stuff in there, just like [Legacy Map](https://wurstlang.org/tutorials/legacymaps.html) imo

**Comment by PhoenixZeng** [comment]
For native functions, this is easy to handle, just need to comment it out once. But for other custom jass functions, it becomes very difficult to handle.

**Comment by Frotty** [comment]
"Commenting out" is not related to anything I said.

**Comment by PhoenixZeng** [comment]
if Keep war3map.j static. when build the map. the inner map or the static  war3map.j which war3map.j will be used  ?

**Comment by Frotty** [comment]
> if Keep war3map.j static. when build the map. the inner map `s war3map.j or the static war3map.j which will be used ?

Read carefully and you should realize only one makes sense.

You are simply trying to have an extended build pipeline with wurst.
The title "ignore function when the war3map.j have the same func-sign and return type func (maybe body)" makes no sense, because if the function is in the war3map.j you don't need it in code, because wurst will parse the war3map.j

If those "special functions" are removed from the map's war3map.j for some reason, then you need the no extract runarg to keep the same war3map.j

Should be very straight foward, your case is nothing different than vJass preprocessing from what I can tell.

**Comment by PhoenixZeng** [comment]
in this case. all map should static war3map.j and put some special functions in it which map want use the wurst lib(which lib base on the special functions  ) .
There are two drawbacks.
1.the map cant be modfiy (because the map`s war3map.j is static. remove or add some func will not work)
2.every map should do it by hand (1Extract j by mpq tool because at the first time the wurst will report error for no war3map.j ; 2 make it static ; 3 put some special functions in it . 4 file cant modfiy code )

> Another scenario is that it makes it easier for  to collaborate with people who don't know how to write code (like : GUI users).
Another hope is that it makes it easier for  to collaborate with people who don't know how to write code (like : GUI users). as the ref

**Comment by PhoenixZeng** [comment]
i think make a way to ignore the func (like by a new annotation) for 'Call to function testfunc is ambiguous, alternatives are ...'  are more elegant
That is to say, when two functions with the same function signature and the same return value appear, one of them with annotations is ignored or one of them with annotations is adopted.

**Comment by Frotty** [comment]
The reason to have a "static" war3map.j is to be able to make changes to it without them being overwritten from the map. If you want to make dynamic changes to triggers in the map, you want it to be updated.

Thus I still don't understand your problem. 

> to ensure the we can compile success , i should make some func in we
to ensure the wurst with out coding-time error and compile-time error. i should put some j file in wurst-project

If the natives are inside the war3map.j from the map, why would you need another .j file in the wurst project to begin with? Consider the war3map.j file just like a globally imported wurst package. If the Jass function is in the map, where you want it to be available to GUI users, it will be extracted.

```
package War3mapJ // Hypothetical
native foo takes nothing returns int

package SomeOtherJFile
native foo takes nothing returns int // Why? Just use `foo` from War3mapJ
```

I also tried this with the example map provided on project setup:

1. Wrote some function
![](https://i.imgur.com/c5J97fn.jpg)

2. Use in GUI
![](https://i.imgur.com/qikpMWg.jpg)

3. Delete war3map.j in project, then `F1 -> Run Map` (it will extract), Triggers now inside
![](https://i.imgur.com/35J6GCY.jpg)

4. `F1 -> Reload Window`. Now you can use it in code
![](https://i.imgur.com/VnICM5R.jpg)

5. When run from Editor it prints once, from vscode prints twice:
![](https://i.imgur.com/9i8hGE8.jpg)
![](https://i.imgur.com/BB5rtkS.jpg)

Please specify your exact issue step by step

**Comment by PhoenixZeng** [comment]
> If the natives are inside the war3map.j from the map, why would you need another .j file in the wurst project to begin with? 

beacuse for a new project . the wurst lib should not report error

well.

eg: (for not static war3map.j)

i have jass files: n1 n2 (some native funcs)

i have  jass  lib:
j1 (some  native func`s encapsulation base on n1  )
j2 (some  native func`s encapsulation base on n2 )
j3 (some other jass functions )

i have wurst package:
w1  (some  native func`s encapsulation base on n1 )
w2  (some  native func`s encapsulation base on n2 )
w3  (some  func`s encapsulation base on j3 )


if `ydwe auto import` is open

Event  1 .when the gui users use some triggers not base on natives and libs
 w1 w2 report error
(1) put the n1 n2 file in the wurst project .
    Nothing happens at this time, go to Event 2
(2) copy n1 n2 it to map. 
    in this case. when the gui users use some triggers base on j1
    jasshelper report error for `Duplicate Definitions of Functions`

Event  2 .when the gui users use some triggers base on j1 and j3.
the function witch in  j1 j2 n1  will be inject and extract to war3map.j
if on the event 1
(1)put the n1 n2 file in the wurst project .
the w1 and war3map.j in project report error for 'Call to function testfunc is ambiguous, alternatives are ...' 
at this time . i make this issue
At this point, the w1 w2 is universal. 
(2)not put the n1 n2 file in the wurst project .
w2 report error
At this point, the w1 w2 is not universal. Putting the new map will encounter these problems again.

if `ydwe auto import` is close

Event  1 .when the gui users use some triggers not base on natives and libs
w1 w2 report error
(1)put the n1 n2 file in the wurst project .
(2)Because you don't know how many jasslib functions GUI users will use, you need to put them all on the map, and library files may be a lot more in the real used.

Event  2 .when the gui users use some triggers base on j1 and j3.
if on the event 1
(1)put the n1 n2 file in the wurst project .
the w1 and war3map.j in project report error for 'Call to function testfunc is ambiguous, alternatives are ...' 
At this point, the w1 w2 is universal. 
(2)put all in map.
nothing. but the jass lib may be have many files
At this point, the w1 w2 is not universal. Putting the new map will encounter these problems again.

-------------------------------------

My English is poor. I'm not sure if you can understand that.
But I also feel that my requirements are not within the scope of the repository.

If you still don't understand the problem I'm facing, or if you think it's beyond what you should maintain, then close it.
I can refuse to cooperate with GUI users

**Comment by PhoenixZeng** [comment]
yes. 
That's what I first asked for.
but it should be useful for any func(except class func) not only for native func

if have the `@ifNotDefined` 
I'm going to write a wurst version of N1 and N2 as WN1 and WN2 and annotation  it
the w1 w2 will not report error any more.
and i dont need to care whtch func in the war3map.j. because not give an error and just use the function without the annotation 

Another usage

for different platforms, i can use the same function name in wurst and annotate it. Then ican use macro definition in jass to decide which one is his real implementation.

**Comment by PhoenixZeng** [comment]
l update the compiler. and some strange things happended..
what is this type
@peq 
![qq 20190204003918](https://user-images.githubusercontent.com/26225903/52179412-62e35280-2815-11e9-83c8-921931e4f65a.jpg)

**Comment by PhoenixZeng** [comment]
some thing workd. @peq .good job

and i find i need the annotation can be used on globals vars 
(used for some jass library)

**Comment by PhoenixZeng** [comment]
Has the proposal to make `@ifNotDefined`  able to used on a global variable been rejected? 
Or I didn't make it clear.
