### ISSUE TITLE
"Global variable MAP_SPEED_NORMAL used before it is declared."

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstScript#798]
Since the last update, I have this warning coming from the line 527 of the blizzard.j in the _build folder.
"Global variable MAP_SPEED_NORMAL used before it is declared."

**Comment by Frotty** [comment]
Yea we just added that warning for Jass top level declarations, which also applies to common.j, blizzard.j and even war3map.j 
Looks like the compiler doesn't correctly relate common.j as parent of blizzard.j in certain cases. Weird that most other functions don't seem to throw warning.
I pushed a small fix ignoring common.j/blizzard.j files for now, which should probably be done for all warnings anyway ?!
