### ISSUE TITLE
Joint Case Clauses in Switch Statements

### ISSUE THREAD

**Issue by frederikaalund** [wurstscript/WurstScript#812]
I assume that you left out `case` fallthrough in the `switch` statement by design. Indeed, fallthrough can be tricky for newcomers to the language. On the other hand, `switch` feels slightly crippled without it.

Here is an example of the current behaviour:

    switch command
        case "-lvlup" // Currently doesn't do anything. I'm used to fallthrough so this came as a surpise for me.
        case "-lu"
            lvlup()

I'd like to execute the same statement for both `case` clauses without repeating the statement. This is currently not possible.

I propose the following solution: Joint `case` clauses. E.g.,

    switch command
        case "-lvlup", "-lu"
            lvlup()

It's an alternative approach to fallthrough without the ambiguity. I've used the a comma symbol to separate the literals in the `case` clause. If you prefer another symbol then just use your preference.

Assuming that `switch` compiles to a long `if..elseif..else` statement, the implementation can simply `or` together the arguments of the joint `case` clause.

What do you think? Is it worth the effort?

**Comment by Frotty** [comment]
Yes, switch was implemented in the most basic manner with the only additional being that it checks if all cases of an enum are handled.
I think improvements could be made, perhaps even syntax wise similar to [Kotlin's when](https://superkotlin.com/kotlin-when-statement/).

**Comment by peq** [comment]
Several cases can now be combined using a pipe symbol (`|`).

```wurst
enum Animal
    Sheep
    Dog
    Eagle

function canFly(Animal animal) returns boolean
    switch animal
        case Dog | Sheep
            return false
        case Eagle
            return true
```

I used the pipe rather than a comma, because a comma is often used for things like tuples and function parameters and we might add language features to match on tuples in the future.

**Comment by Frotty** [comment]
Why not just use `or` like with all other conditional operations in wurst?
Why suddenly and for the only usage in wurst, use pipe here? Imho a bad choice.

**Comment by peq** [comment]
Or is already used as an operator and I don't like giving the same operator different meanings.

**Comment by Frotty** [comment]
> Or is already used as an operator and I don't like giving the same operator different meanings.

I think it's only a different syntax meaning, the intuitive meaning, or understanding even would not suggest `|` especially in a wurst context. We started trying to cut down on verbosity, but rather keep it verbose than "just use hard to reach/type symbols" for the heck of it afair.
`|` for me is either a pipe, or a bitwise OR operation. As join in switch it doesn't look great to me.
Thinking about writing it, it's also trash on most layouts, requiring 3-key shortcuts e.g. under osx to even type it.

**Comment by peq** [comment]
F#, Ocaml, Reason, ML, Scala, Rust all use `| ` for this. Kotlin and Java12 use `,`.

I don't know any language that uses the logical disjunction operator to express disjunctive patterns. So I think we should use one of the above.

 I liked `|` in F# because then you can use `&` for conjunctive patterns whereas there is no corresponding symbol for `,`. Also commas are already used in many other places, so it's harder to read if we add more complex patterns.

**Comment by Frotty** [comment]
> F#, Ocaml, Reason, ML, Scala, Rust all use `|` for this

> I don't know any language that uses the logical disjunction operator to express disjunctive patterns. So I think we should use one of the above.

Those languages above also use `||` as short circuit logical or operator. So I would say it makes intuitive sense to also use "|" in a very similar fashion.
