### ISSUE TITLE
Incorrect warning for unread local array assignments

### ISSUE THREAD

**Issue by nvs** [wurstscript/WurstScript#813]
When using local arrays, incorrect warnings are produced:

> The assignment to local variable b is never read.

```wurst
package A

class A
    function a ()
        integer array b

        b[0] = 0 // Warning.
        b[1] = 0 // Warning.
        b[2] = 0 // No warning.

        I2S(b[0])
        I2S(b[1])

        for i = 0 to 2
            I2S(b[i])
```

The same issue holds true for both Jurst and Jass.

**Comment by Frotty** [comment]
arrays aren't handled specifically and it's probably not possible to reliable detect it.

**Comment by peq** [comment]
The warning is disabled for array variables now. 

We could detect something like the following example statically using abstract interpretation but I think it is not worth the effort to implement this.

        b[0] = 0 
        b[1] = 0 // Could be a warning ...
        b[1] = 0
