### ISSUE TITLE
Chinese character encoding error

### ISSUE THREAD

**Issue by yefq** [wurstscript/WurstScript#823]
Character encoding error when use `wurst: build your map...` command  to build map.
But no problem when use `wurst:  Run a Wurst map` command to build map.

I was unpack and compare `war3map.j` from `MyWurstMap.w3x` and `WurstRunMap.w3x`. 
Chinese word `"完成！"` was compile into `"??ɣ?"` in  `MyWurstMap.w3x` , But no problem in `WurstRunMap.w3x`.

I guess that they use different character encoding to compile, which leads to this error.
I can only use the command line to test the map, because I have to load the plug-ins of the game platform in China, So I had to build a running map first.

Sorry for my poor English.

**Comment by Frotty** [comment]
Be more specific. Is the string inside the war3map.j or inside object data?

**Comment by yefq** [comment]
Only inside the war3map.j , object data and compiled.j.txt is normal.
This error occurred after recent updates.
