### ISSUE TITLE
Enum referencing in if statements

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstScript#825]
It would be nice to be able to reference enums in if statements like we can in switches. 
For instance instead of `if state == MyCustomState.STATE_1` we could write `if state == STATE_1`.

**Comment by peq** [comment]
We could either add a new kind of import statement like `import MyCustomState.STATE_1` or we could resolve `STATE_1` by inferring the expected type based on the context (comparison with state which is a variable of type `MyCustomState`).

Which option would you prefer?

CC: @Frotty

**Comment by WareditorGit** [comment]
I think the second option is better.
