### ISSUE TITLE
Ambiguous call showing 2 identical path as alternative

### ISSUE THREAD

**Issue by Jaccouille** [wurstscript/WurstScript#828]
My english and my words might not be correct, would appreciate correction.

**Describe the bug**
Error happening when they shouldn't, it's about ambiguous call to a function, it shows 2 alternative having the exact same path.

**To Reproduce**
1. Call/declare a function and call one of it's method e.g : "vec2(1, 1)..toString()"
2. Right click on function name, click p, "Go to definition"
3. Select the function name
4. Go back to your declaration, try to change it
5. Error appear on your declaration, telling that the call is ambiguous

**Expected behavior**
No error? Not showing 2 identical path as alternatives.

**Screenshots**
[Click here for a better quality gif on gfycat, last 40 seconds](https://gfycat.com/WhiteWindingHuemul)

![](https://thumbs.gfycat.com/WhiteWindingHuemul-size_restricted.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [Is this for the browser? Firefox 66.0.1 (64-bit)]

**Comment by peq** [comment]
Thanks for the detailled report. I pushed two commits that should fix this problem.

If there are still problems, please reopen this issue or create a new one.

Btw: The browser version is not important, the issue template refers to the Wurst version.
