### ISSUE TITLE
Improve package import suggestion order

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#829]
![](https://i.imgur.com/VtaaHYV.jpg)

Right now it seems fairly random. Usually I would want to import the package this annotation/function comes from - not one where I get it via a chain of 4 public imports.
In this screen BuilderConstants should be at the top, maybe even marked as "package of origin".

**Comment by Frotty** [comment]
Removing all other suggestions isn't really that ideal though.

**Comment by peq** [comment]
Why would you want the others?
