### ISSUE TITLE
Can't build map with specific player settings - 20th+ player as Computer (compile works)

### ISSUE THREAD

**Issue by Donach** [wurstscript/WurstScript#832]
We have encountered a bit random issue with building the map with specific player settings.
If there are up to 19 players, and 20th+ player is Computer, the map will not Build with following error:
![image](https://user-images.githubusercontent.com/39565367/55990238-81e3e200-5ca7-11e9-84a6-8a1ed11233e2.png)
![image](https://user-images.githubusercontent.com/39565367/55990292-9f18b080-5ca7-11e9-9adc-1c7ed8e5fca5.png)

Raising heap space does not help in this case (I tried 4-6GB), however changing the 20th computer player back to User works (or changing to None).
So these settings work:
![image](https://user-images.githubusercontent.com/39565367/55990331-b48dda80-5ca7-11e9-9839-94bc79ed0fee.png)

I created new map for this purpose and set the size to 480x480, set some descriptions (otherwise there is nullpointer), and set the players, nothing more.
Usually it happens, if you save map with no 20th+ player as Computer, and then try to build map (which works), and then you set 20th+ player as Computer and try to build, which leads to error above.

Funnily enough, this error never appears on "Run a Wurst Map" task, only during "Build" task.

**Mapfile:**
[test.zip](https://github.com/wurstscript/WurstScript/files/3070444/test.zip)

**Comment by Frotty** [comment]
@WaterKnight Looks like wc3libs issue?

> Funnily enough, this error never appears on "Run a Wurst Map" task, only during "Build" task.

Nothing funny, the new wurst.build changes only get executed on the build task.

**Comment by WaterKnight** [comment]
I am uneasy with bit arithmetics :(

But the Player 20 in your map has an ally low priority flags value of 1100 0001 1111 1110 0010 0111 0110. This means it contains the players 1, 2, 4, 5, 6, 9, 13, 14, 15, 16, 17, 18, 19, 20, 26, 27 (0-based), which makes me wonder if Blizzard hiddenly also stores relationships to the neutral players because, otherwise, there is no 28th player.

**Comment by Frotty** [comment]
> But the Player 20 in your map has an ally low priority flags value of 1100 0001 1111 1110 0010 0111 0110. This means it contains the players 1, 2, 4, 5, 6, 9, 13, 14, 15, 16, 17, 18, 19, 20, 26, 27 (0-based), which makes me wonder if Blizzard hiddenly also stores relationships to the neutral players because, otherwise, there is no 28th player.

What does it mean? Is it a change due to 24 player limit? Why does it work if the player is computer?
No fix in sight?

**Comment by WaterKnight** [comment]
No, that was just for notice. The problem was probably an infinite loop as continuous shifting did not result in an expected 0 integer. It should be fixed now.
