### ISSUE TITLE
Language server error

### ISSUE THREAD

**Issue by SnekMuffin** [wurstscript/WurstScript#834]
> Request 'de.peeeq.wurstio.languageserver.LanguageWorker$FileReconcile@107dff4' could not be processed (see log for details): java.lang.NullPointerException

This error pops up when I try to edit the code, on every single change. I.e. I write 3 letters, it pops out 3 errors, I erase 3 letters, it pops out 3 more errors.

Also, I can't run any of the commands such as running a map.

![image](https://user-images.githubusercontent.com/49637097/56121558-f027ed80-5fa2-11e9-8c0e-d2a271992d7f.png)

**Desktop**
 - Win10 x64
 - Latest Wurst and Wurst Extension versions
 - WC3 1.30 (Also tried on my 1.26a and 1.29 installations)

**Comment by Frotty** [comment]
Yea, you should open the "MyWurstProject" folder via `File -> open folder` as I mentioned above.

**Comment by SnekMuffin** [comment]
Allright, I see. Thanks a lot for the help.
