### ISSUE TITLE
ID Generator Bug

### ISSUE THREAD

**Issue by delitaru** [wurstscript/WurstScript#836]
Generating multiple Ability and Buff IDs can cause Ids to be messed up and possible cause heavy load during compiletime.

Test: [CHSX.zip](https://github.com/wurstscript/WurstScript/files/3101586/CHSX.zip)
Heroes/Archmage.wurst by itself works as intended, it generates custom aura abilities (icon is hidden, gives a buff to self). Running the map will create a unit for each ability in the center.

Uncommenting Burn.wurst will cause the buffs to be offset (Burn will replace 1 buff and the rest will be shifted).
Uncommenting Bosses.wurst will cause abilities and buffs to be completely messed up.

Note: I use a custom function to convert id codes into id strings when generating the abilities. I am certain it works correctly but it may be related to the issue.

**Comment by peq** [comment]
The id generator should be used inside `compiletime` expressions as in the example under: https://wurstlang.org/stdlib/buff_objed

So try changing `static constant int BUFF = BUFF_ID_GEN.next()` to `static constant int BUFF = compiletime(BUFF_ID_GEN.next())`

If you don't do this, the id generator will run at compiletime AND at runtime and might run in different orders.

**Comment by delitaru** [comment]
Yep, it works. I should have known it was a simple mistake like that.

I assumed it wouldn't make a difference if i added that or not because it worked for the first few generated ids.
I think it would be a good idea add a note that id generators should be in inside compiletime() functions to help other people avoid this problem.

**Comment by Frotty** [comment]
> I think it would be a good idea add a note that id generators should be in inside compiletime() functions to help other people avoid this problem.

In certain scenarios  you don't want object id generators in compiletime expressions, and those are valid use cases. If you generate objects of which you don't need the ID accessible (e.g. spawn system for TD) you could create a new ObjectIdGenerator object with your given start id, and then run it compile and runtime.
You put it in compiletime expressions only, if you need the global reference or you are using the generator across multiple packages.

I'm not sure if such a hint is worth being added to all objediting doc pages or just one page for the id generator itself.
