### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by cloudfox2** [wurstscript/WurstScript#839]
java.lang.RuntimeException: There was a Wurst bug in the translation of endfunctionstatement  (E:\CF\Wurst\wurst\91Base\Unit\Damage.wurst:46): Cannot change parent of element ImClassImpl, as it is already used in another tree.Use the copy method to create a new tree or remove the tree from its old parent or set the parent to null before moving the tree. 
Please open a ticket with source code and the error log.

this happened after i updated wurst from 756 to 1098
Damage.wurst: https://bin.wurstlang.org/obizubiqij.wurst

if i comment "Act onKill" part, it will be ok but there are same errors in other files

**Comment by Frotty** [comment]
> this happened after i updated wurst from 756 to 1098

1098 is already outdated again, that bug is most likely already fixed.
Make sure you update to latest version before reporting issues, since they might have been addressed.

**Comment by cloudfox2** [comment]
yeah it works
