### ISSUE TITLE
Can we have PTR build of Wurst?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#841]
So we can keep our libraries up-to-date and test new features in a convenient way.

**Comment by Frotty** [comment]
As far as I know there is no incompatibility with the current build, what exactly do you want?

**Comment by peq** [comment]
Just to clarify: Are you referring to the wc3 PTR or do you just want us to provide something similar for wurst (e.g. a stable version and a nightly version?).

**Comment by GetLocalPlayer** [comment]
> Just to clarify: Are you referring to the wc3 PTR or do you just want us to provide something similar for wurst (e.g. a stable version and a nightly version?).

Warcraft

**Comment by peq** [comment]
Since PTR uses a different folder to store maps in, I'll add an option for configuring it. Otherwise the normal version should work with PTR.

**Comment by Frotty** [comment]
> Since PTR uses a different folder to store maps in, I'll add an option for configuring it. Otherwise the normal version should work with PTR.

already exists
