### ISSUE TITLE
Using any map description makes map unopenable after build

### ISSUE THREAD

**Issue by Donach** [wurstscript/WurstScript#843]
Hello,
I have encountered weird bug, happens with your ExampleMap and also my mapfiles, probably since some version of Wurst. (I'm currently using the latest 1148 build)

When there is any map description in "Scenario -> Map Properties -> Description", the map is unopenable when built.

I'm attaching two ExampleMaps, where one is working fine, one now and the screen that I get in WC3 using the bad one.

If you need more information, feel free to reach me.

![image](https://user-images.githubusercontent.com/39565367/56999914-8f5b0080-6bb1-11e9-8a15-39552f338875.png)
[ExampleMaps.zip](https://github.com/wurstscript/WurstScript/files/3133482/ExampleMaps.zip)

**Comment by Frotty** [comment]
All maps have a default description afaik, and I don't get any problems regardless of it.
Do you have something special inside your description text? Can you paste it? Are you on the latest version?

**Comment by Donach** [comment]
For me, any description text besides empty would not work.

So even text like "TEST" would fail.

**Comment by Frotty** [comment]
Are you on PTR?
