### ISSUE TITLE
support 'folded imports'

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#844]
like this
```
package foo
\timport bar
\timport baz
```
let vscode can do this
![QQ截图20190504062553](https://user-images.githubusercontent.com/26225903/57168707-81b5ad00-6e35-11e9-84c3-0f1cd3c22c2a.jpg)

**Comment by PhoenixZeng** [comment]
Two schemes
1.let compiler support a `\tab` with import
or
2.let vscode plugin support  `folded `

**Comment by Frotty** [comment]
3. add warning for lowercase package names 😆

**Comment by Frotty** [comment]
See https://github.com/wurstscript/WurstScript/pull/914
