### ISSUE TITLE
configurable wc3 launcher for `run` and `run with jhcr`

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#845]
code near
[RunMap.java](https://github.com/wurstscript/WurstScript/blob/master/de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunMap.java)
line 207

at here . you try find wc3 GameExecutable in wc3 path and run map

but I request a ExecutableCommond to run the map
like this
`X:\\war3\\war3.exe  -loadfile {mapPath}`
and we can config it to other
like
 `X:\\foo\\baz.exe -bar  -quz {mapPath}`

we can make a vscode config to do this . and if it not exists, do the `findGameExecutable()` like now .

**Comment by fe3dback** [comment]
Also warcraft 3 can run map, if path to -loadfile contain spaces. 

Wurst run script should wrap all path's with quotes:

Log
```
2019-05-09 18:30:26 [Wurst LanguageWorker] INFO  languageServer - Starting wc3 ...  
2019-05-09 18:30:26 [Wurst LanguageWorker] INFO  languageServer - progress: running [C:\games\Warcraft III Public Test\x86_64\Warcraft III.exe, -window, -loadfile, C:\Users\fe3db\Documents\Warcraft III\Maps\Test\WurstTestMap.w3x] 
```

This is not working:
```bash
"C:\games\Warcraft III Public Test\x86_64\Warcraft III.exe" -loadfile C:\Users\fe3db\Documents\Warcraft III\Maps\Test\WurstTestMap.w3x
```

This is working correctly:
```bash
"C:\games\Warcraft III Public Test\x86_64\Warcraft III.exe" -loadfile "C:\Users\fe3db\Documents\Warcraft III\Maps\Test\WurstTestMap.w3x"
```

**Comment by Frotty** [comment]
@PhoenixZeng The problem is that we use the game exe to determine the patch version, which might not work on a custom exe.
I would suppose that this is somewhat of an edge case and you should be able to achieve it with vscode tasks yourself.

@fe3dback This issue was fixed some time ago by switchting to ProcessBuilder.
