### ISSUE TITLE
Error in file compiled.j

### ISSUE THREAD

**Issue by Jaccouille** [wurstscript/WurstScript#852]
**Describe the bug**
I believe this picture is explicit : ![ErrorScreenshot](https://i.gyazo.com/18cf19fc2ca38692097a2138619bc57a.png)

 I had an error on another project, the error is different from this one, so I switched to this small project I use to test stuff, and couldn't compile for some reason. I'll create an issue for the other project later it later if I can't fix it.

Project code : https://bin.wurstlang.org/zefugodufa.wurst

Compile.log file content : https://bin.wurstlang.org/ozotemojuq.wurst

**Comment by Frotty** [comment]
I reverted the regression, but we need a proper fix for this
