### ISSUE TITLE
wurst_stack_depth exception!

### ISSUE THREAD

**Issue by supemeko** [wurstscript/WurstScript#853]
**Describe the bug**

![D](https://user-images.githubusercontent.com/38853195/57645618-4499a980-75f1-11e9-8196-41c5fdbedbc3.png)

![EE](https://user-images.githubusercontent.com/38853195/57646457-3482c980-75f3-11e9-8327-173f8f7dbd65.png)

 * If possible include steps to reproduce the bug (e.g. a small code example or a link to your project code)
 * For compiler crashes include the log file from `${user.home}/.wurst/logs/compiler.log`
 * For language server bugs (e.g. Visual Studio Code plugin) include the log file from `${user.home}/.wurst/logs/languageServer.log`

**Comment by supemeko** [comment]
![EE](https://user-images.githubusercontent.com/38853195/57646098-62b3d980-75f2-11e9-8887-6ba411e60a09.png)

**Comment by supemeko** [comment]
![FFF](https://user-images.githubusercontent.com/38853195/57647888-bc1e0780-75f6-11e9-8066-49282f9500de.png)

![GGG](https://user-images.githubusercontent.com/38853195/57647911-c7713300-75f6-11e9-90af-f6ebdf66cc96.png)

**Comment by supemeko** [comment]
Maybe it is opcode limit cause to.

**Comment by Frotty** [comment]
You can easily avoid oplimit by using the `Execute` package btw.
