### ISSUE TITLE
Is the @ifNotDefined been removed in current version?

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#854]
![微信截图_20190522154418](https://user-images.githubusercontent.com/26225903/58156624-17ac5d00-7ca9-11e9-9ca2-ff3f8568afb2.png)

**Comment by Frotty** [comment]
No, but annotations now need to be defined, and it's not in the `Annotations` package as it seems.

**Comment by PhoenixZeng** [comment]
so. do i need defined it myself or make a pr for the std

**Comment by Frotty** [comment]
Should be fixed by https://github.com/wurstscript/WurstStdlib2/commit/4c0f3ab4b7a5ff62927b1c98d4d6041fa87b16f4
Let me know if that works.

**Comment by PhoenixZeng** [comment]
error .  by my test. the annotations  seem to `have to be lowcase`

**Comment by PhoenixZeng** [comment]
change to 
```
@annotation public function ifnotdefined()
```
and workd

**Comment by Frotty** [comment]
Ok, I updated stdlib 👍
