### ISSUE TITLE
injection of game interface and gameplay constants into map

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstScript#855]
Would be nice to be able to put the game interface and gameplay constants into the imports folder and inject them with some run_args like `-injectgameplayconstants`.

![Capture](https://user-images.githubusercontent.com/640169/58288336-97bee980-7db3-11e9-9a08-fd01b91eeff6.PNG)

**Comment by Frotty** [comment]
The gameplay constants are simple text files, you can already do this 
Example here: https://github.com/Frotty/EBR/blob/master/imports/war3mapMisc.txt

**Comment by Krypt0n** [comment]
oh yeah, wtf, I think i already did that in the past, pleased delete haha
