### ISSUE TITLE
can`t build

### ISSUE THREAD

**Issue by PhoenixZeng** [wurstscript/WurstScript#856]
build this example: https://github.com/PhoenixZeng/wurstError

it looks like a mpq problem. but it run well in the old version for wurst
this problem related to  `cog.w3x` and `imports\war3mapImported\` 
change each one to other file will not reproduce
it happend when compile last `applying map config`

![QQ截图20190526072030](https://user-images.githubusercontent.com/26225903/58375594-0b661f80-7f89-11e9-967d-9b6c15c28b42.png)

logs:
[logs.zip](https://github.com/wurstscript/WurstScript/files/3219846/logs.zip)

**Comment by Frotty** [comment]
How to reproduce this?

**Comment by PhoenixZeng** [comment]
1. clone the `example` .
2. update project by wurstsetup
2. F1 ->  wurst:build

**Comment by Frotty** [comment]
Some JMPQ issue, I'm not sure what causes it.
Needs additional information and smaller way to reproduce.

**Comment by Frotty** [comment]
Please re-check if this is still an issue, there have been plenty jmpq updates.
