### ISSUE TITLE
Installation manual.

### ISSUE THREAD

**Issue by nelloy-git** [wurstscript/WurstScript#858]
Can you add full instalation description for lua branch? Im getting "Fix errors in your code ..." error when i have any .wurst file in project. Nothing interesting in log. I built wurstscript with grandlew and coppied files from build/distributions/wurstpack_compiler.zip to C:/Users/.../.wurst. What am i doing wrong? Using VSCode with extendion from marketplace

**Comment by Frotty** [comment]
Did you check the [README](https://github.com/wurstscript/WurstScript#build-process)?

You should run `./gradlew make_for_userdir` if you have an existing installation.

If you get `Fix errors in your code ...` then you either have compilation errors (see vscode problems tab) or the project isn't setup correctly.

The lua branch is also not up to date with master and contains the old natives iirc. It will be updated soon and merged into master.

**Comment by nelloy-git** [comment]
Nice to hear about merging. Problems tab is empty...

**Comment by Frotty** [comment]
The lua branch is now merged and a few projects have been successfully tested.
Simply supply `-lua` in the wurst_run.args file. Wurst will now generate lua and adjust the map automatically.
Enjoy and make sure to report issues.
