### ISSUE TITLE
-inline issue (cannot convert returned int to real)

### ISSUE THREAD

**Issue by WareditorGit** [wurstscript/WurstScript#866]
When using -inline while building my map ([repo here](https://github.com/WareditorGit/WoWArena-Reforged)) I get the following error:

![image](https://user-images.githubusercontent.com/38940363/59567952-24d42600-9074-11e9-9680-04e46eabba09.png)

[compiled.j](https://github.com/wurstscript/WurstScript/files/3294436/compiled.j.txt)
[log.txt](https://github.com/wurstscript/WurstScript/files/3294443/log.txt)

**Comment by peq** [comment]
Sorry, referenced wrong bug number in commit.

**Comment by peq** [comment]
@WareditorGit I cannot compile the project. Which dependencies are you using?
