### ISSUE TITLE
Forest Defense produces ingame errors with -lua option

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstScript#869]
Produces this scriptfile:

https://lounge.oxbot.stream/uploads/f6208c7e2e9c5996/war3map.lua

Error examples:
![](https://i.imgur.com/84qdERy.jpg)
![](https://i.imgur.com/Gp58yt1.jpg)

**Comment by peq** [comment]
Are these versions correct to reproduce the bug?

EBR: a2c1b756957eab20213f848df1872579de5cec23
Frentity: e2059e71528600e457694b7b5560c5091dbc4a6f
WurstStdLib: b7bfd89233e3d6aca3be35e0af2810aca98c9926

Any steps necessary to reproduce this ingame?

**Comment by Frotty** [comment]
> `EBR: a2c1b756957eab20213f848df1872579de5cec23`

It's Forest Defense, not EBR, but the hash is correct.

> Any steps necessary to reproduce this ingame?

Add `-lua` to run args.
Happens after playing a while and specific events, such as picking up a coin.
