### ISSUE TITLE
Can't find WC3 Installation 

### ISSUE THREAD

**Issue by maltebp** [wurstscript/WurstScript#873]
Haven't been working with wurst for over a month now. So I came back, ran my map and it worked fine. Then I went and updated WurstSetup tool and my project to compiler build to 1178, and now it throws the this error "Could not find Warcraft III installation!" when I run my map.

**I've Tried:**

 - To change the installation path to \Warcraft III\x86, \Warcraft III\x86_64 and \Warcraft III both via the setup tool and in setup.json.
 - Re-install the game. This moved the game directoy to \Program Files (x86)\ to \Program Files\, and updating the installation path to this.
 - Create an entirely new project, letting WurstSetup tool find the installation path.

None of these things worked.

**Logs:**
[vsc_output_wurstLanguageServer.txt](https://github.com/wurstscript/WurstScript/files/3378442/vsc_output_wurstLanguageServer.txt) - This shows that a Java IOException is being thrown, suggesting that the 'wmic' command doesn't exist

[languageServer.log](https://github.com/wurstscript/WurstScript/files/3378440/languageServer)

**Comment by WaterKnight** [comment]
Are you on Windows?

**Comment by Frotty** [comment]
> Are you on Windows? The "load wmic datafile..." message is not in the latest wc3libs commit. I had changed it to consider the full path (%SystemRoot%\System32\Wbem\wmic.exe) because %SystemRoot%\System32\Wbem would miss sometimes in PATH environment variable.

Does this mean it's fixed on the latest wc3libs commit? Or are you just mentioning this?

@maltebp I pushed an update to the wc3libs dependency, please update to 1179 and retry.

**Comment by maltebp** [comment]
Updated, and getting new error now when running the map. Tried to create new project after updating setup tool and compiler, but getting same error

[vsc_output_wurstLanguageServer.txt](https://github.com/wurstscript/WurstScript/files/3378726/vsc_output_wurstLanguageServer.txt)

[languageServer.log](https://github.com/wurstscript/WurstScript/files/3378730/languageServer.log)

**Comment by Frotty** [comment]
Thanks for the quick reply, unfortunately it's an unrelated error, simply caused by jitpack changing JDK version and wc3libs missing gradle compatibility config.
I pushed another fix, please retry.

**Comment by maltebp** [comment]
Hehe, fixed _that_ problem, but again a new one occurs (see logs)

[vsc_output_wurstLanguageServer.txt](https://github.com/wurstscript/WurstScript/files/3378826/vsc_output_wurstLanguageServer.txt)

[languageServer.log](https://github.com/wurstscript/WurstScript/files/3378827/languageServer.log)

**Comment by WaterKnight** [comment]
https://github.com/eclipse/jetty.project/issues/3244

**Comment by peq** [comment]
So it should work when using a recent Java version?

**Comment by WaterKnight** [comment]
> So it should work when using a recent Java version?

The opposite. The compiler compiles according to Java9 when it should according to Java8.

**Comment by Frotty** [comment]
@maltebp Try one more time 😅

**Comment by maltebp** [comment]
Yes! It works fine now - smooth ;) Cheers, and thanks for the help
