### ISSUE TITLE
Can't run a map

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#876]
Each time I tried to run a map I got
```
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Unhandled method workspace/configuration
```
Building is always successful. Have I forgotten anything?

**Comment by peq** [comment]
Added some error handling for this case. Please check if it works now (should just show a warning and no exception).

I could not figure why it cannot read the configuration. Maybe you have an older version of Visual Studio Code that does not support this API yet?

**Comment by GetLocalPlayer** [comment]
> Maybe you have an older version of Visual Studio Code that does not support this API yet?

It seems. I've just figured out my vscode can't update somehow. Now it works.
