### ISSUE TITLE
w3x built map is not compressed (jMPQ bug?)

### ISSUE THREAD

**Issue by anufis** [wurstscript/WurstScript#882]
In this example (zipped wurst project with 1 file in "imports" folder) I have provided snippet for bug reproduction. [Link to google drive](https://drive.google.com/open?id=1XZqJNP48EQlT93ai8gc5mS3tthcE7xBg)
There are 2 maps "map.w3x" and "map pre 1.31.w3x" in the project. Both maps were saved in worldeditor however second one was saved before 1.31 came out.
I have added only 1 file to "imports" to see a difference in size between compiled results. In _build there are 2 examples of compiled map. "map.w3x" (3054 kbytes) and "map pre 1.31.w3x" (1528 kbytes). These results can be reproduced by simply building project.

**Comment by Frotty** [comment]
I'm not exactly sure what the issue is.
A few ideas I had turned out to not be the cause.

For now I added a final mpq rebuild step at the end of the `build` task which should mitigate the issue there.
