### ISSUE TITLE
add bit operations natives for compiletime

### ISSUE THREAD

**Issue by Rhazarian** [wurstscript/WurstScript#884]
Please, allow to use `BlzBitOr`, `BlzBitAnd` and `BlzBitXor` at compiletime. They are very useful and I assume that it's very easy to support them.

**Comment by Frotty** [comment]
Sure should be doable. Do you have mores specific implementation details?
Also, you can already use the [https://github.com/wurstscript/WurstStdlib2/blob/master/wurst/bitwise/Bitwise.wurst](Bitwise package).

**Comment by Rhazarian** [comment]
Thanks, I know about the package, but I am concerned by the fact that some of the work that package do can be done a lot faster using this natives, and I would like to update it as well as `bitset` package, but cannot do so until these natives are supported at compiletime, because these packages should be able to be used at objectgeneration and to be tested.

Actually, I do not have any specific details (in the patchnotes they were introduced just like 

>Bitwise functions (BlzBitOr, BlzBitAnd, BlzBitXor)

I strongly believe that these functions behave just like bit operations in any language (`|`, `&` and `^` in C-like ones).

**Comment by Frotty** [comment]
Okay I added the three natives, let me know how it goes.

**Comment by Rhazarian** [comment]
Wow, thanks! I'll make a few pull requests with appropriate changes soon :)
