### ISSUE TITLE
Error running/building Island Troll Tribes

### ISSUE THREAD

**Issue by HallerJohn** [wurstscript/WurstScript#887]
When i try to run or build the map i get the error:
Request 'init' could not be processed (see log for details): java.lang.OutOfMemoryError: Java heap space
However if i try to run the hello world map it works just fine. Also Jaccouile a dev for Island Troll Tribes is able to run the same version without any errors so it shouldnt be a map problem.

Compiler Log: https://pastebin.com/69KHd34X
LanguageServer Log: https://pastebin.com/0FtM5Cgd

Wurst Language Server Output: https://pastebin.com/jL4XamNP

**Comment by HallerJohn** [comment]
If anyone has a similar problem try increasing java heap space.

**Comment by Frotty** [comment]
Cool.
Makes me wonder though, what causes the drastic increase in heap space with the ITT map.
Should probably follow up on this in some way. 6gb requirement for a build seems overkill.

**Comment by HallerJohn** [comment]
I have no idea, I can try looking into all this but it'll be a long process. I need to learn alot before I'll probably be able to do anything substantial.
