### ISSUE TITLE
Replace begin / end with {}

### ISSUE THREAD

**Issue by DoctorRyner** [wurstscript/WurstScript#888]
Hi, begin and end look so terrible and verbose, why not use {} as in mainstream languages? Shouldn't be too hard to implement

<img width="378" alt="Screenshot 2019-08-18 at 3 10 41 AM" src="https://user-images.githubusercontent.com/24430919/63218563-492cab80-c166-11e9-9043-9cbde3371ef4.png">

<img width="411" alt="Screenshot 2019-08-18 at 3 10 19 AM" src="https://user-images.githubusercontent.com/24430919/63218567-4fbb2300-c166-11e9-87eb-3f51325041be.png">

**Comment by Frotty** [comment]
Because when we started wurst we decided against curly brackets and indentation instead.
Wurst stays closer to Jass, which is a verbose language.
Also, in your case you don't need them at all. 
The keywords are only needed, if there are parameters after the lambda.
Hence you should have neither brackets nor keywords 🎉 
```
Lambda<unit> act = () ->
    return someUnit
```

See https://wurstlang.org/manual.html#lambdas-and-closures

**Comment by DoctorRyner** [comment]
Consider this example code, not only begin / and looks terrible but also it gives a warning

<img width="758" alt="Screenshot 2019-08-18 at 3 57 38 PM" src="https://user-images.githubusercontent.com/24430919/63224735-208dcb80-c1d1-11e9-8ede-5d75609e869e.png">

This IO system is actually works
<img width="1440" alt="Screenshot 2019-08-18 at 3 58 48 PM" src="https://user-images.githubusercontent.com/24430919/63224750-41eeb780-c1d1-11e9-8dca-3e8bd3c6d935.png">
<img width="1440" alt="Screenshot 2019-08-18 at 3 58 50 PM" src="https://user-images.githubusercontent.com/24430919/63224751-43b87b00-c1d1-11e9-8d82-417da9a2088b.png">
<img width="1440" alt="Screenshot 2019-08-18 at 3 58 51 PM" src="https://user-images.githubusercontent.com/24430919/63224755-474c0200-c1d1-11e9-9765-94ba6dfb5020.png">

**Comment by DoctorRyner** [comment]
If there is no way to fix it, can you at least remove this annoying warning?

**Comment by Frotty** [comment]
Please don't screenshot code, paste it instead.
How can I fix the warning if you don't tell me which one it is?
All I can see is that your indentation looks incorrect, as you can see from vscode's vertical indicator lines.

Apart from that I am not a big fan of how confusing that code snippet looks - and not because it's missing curly brackets.

**Comment by DoctorRyner** [comment]
First my code style is pure functional programming, so we write:

```Haskell
let xs = asList
    ( 0
    , 1
    , 2
    )
```

instead of:

```Haskell
let xs = asList(
    0,
    1,
    2
)
```

So I can't write as in first example so I forced to use this style instead:

```Haskell
let xs = asList (
      0
    , 1
    , 2
    )
```

The warning is "Inconsistent indentation: Earlier in this file 4 spaces were used for indentation and here it is 18 spaces."

Code with warning:
```Haskell
init
    EventListener.add(EVENT_PLAYER_UNIT_SPELL_EFFECT) ->
        putStrLn ("Doesn't do anything") // :: IO<Void>

        LinkedList<IO<Void>> actions = asList (
            bind1 ( // :: IO<A> -> (A -> IO<B>) -> IO<B>
                  getCaster () // :: IO<Maybe<unit>>
                , (Maybe<unit> maybeCaster) -> cata (
                      (unit caster) ->
        begin // return if Maybe has value
            caster.kill ()
            caster.remove ()
            return pure (void)
        end
                    , putStrLn ("No caster")   // return if Maybe doesn't have a value
                    , maybeCaster
                    )
                )
            , putStrLn ("Actually works")
            )

        runIO (actions)
        doAfter(1, () -> runIO (actions))
```

And that fixes warning
```Haskell
init
    EventListener.add(EVENT_PLAYER_UNIT_SPELL_EFFECT) ->
        putStrLn ("Doesn't do anything") // :: IO<Void>

        LinkedList<IO<Void>> actions = asList (
            bind1 ( // :: IO<A> -> (A -> IO<B>) -> IO<B>
                  getCaster () // :: IO<Maybe<unit>>
                , (Maybe<unit> maybeCaster) -> cata (
                      (unit caster) ->
        begin // return if Maybe has value
            caster.kill ()
            caster.remove ()
            return pure (void)
        end
                    , putStrLn ("No caster")   // return if Maybe doesn't have a value
                    , maybeCaster
                    )
                )
            , putStrLn ("Actually works")
            )

        runIO (actions)
        doAfter(1, () -> runIO (actions))
```

**Comment by peq** [comment]
I removed the indentation warning for blocks used inside parentheses.

If we want better Syntax support for functional programming, we probably have to get rid of the distinction between expressions and statements, but I don't have a good idea to make this work in a backwards compatible way.

If you have any suggestions, please let us know.

Regarding the curly brace suggestion: 
I want to reserve curly braces for set- and map literals in a future version of Wurst. For example: `{1, 2, 3}` or `{x: 1, y: 2, z: 3}`. I think curly braces for grouping expressions or statements are a bit ugly and Haskell is a good example that people don't like to use this kind of Syntax if they have the choice.

**Comment by DoctorRyner** [comment]
Thanks! I'll let you know if I will encounter any troubles with pure functional programming in wurst :)

`{x: 1, y: 2, z: 3}`
So, are you going to support something like objects in JS or records in Haskell? That would be great!

Just share my thoughts of some of hardest things for me now (that I could remember at midnight):
1. That functions are not first class and can't be treated as any other data, there is workaround with interfaces but it makes difficult to pass around / returning other functions, kinda makes code hard to read and its difficult to use carrying to that degree that I prefer not to use it at all and lose all advantages of partial application
2. Lack of qualified import system, you can do something similar by using classes with static fields just to get some namespacing
3. Lack of objects / records, using classes instead doesn't allow you to update fields efficiently without mutations and make you write boilerplate functions just to give ability to change fields
4. Lack of ADT, yes, its pretty rare feature but still... its like really useful enums which can store values of different types but still having common type
