### ISSUE TITLE
Error in compiled.j.txt: This is a bug in the Wurst Compiler. Pjass has found the following problem: Cannot convert null to integer

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#903]
![image](https://user-images.githubusercontent.com/20465861/67657534-4263a700-f914-11e9-8372-c4ac47097a78.png)

I have no idea what the error means or how it occurred. Unfortunately, I made a series of changes to a large project and I don't know what change it was that caused it to happen.

My only guess is that I derived a class _LootableUnit_ from a base class that implements a function "getComponent" and that seems to be at least related to the issue since I'm seeing this line and many like it in compiled.j near the errors:

`set x_u=ykw(F_u,k_u,"when calling getComponent in Composition, line 7")`

[compiler.log](https://pastebin.com/t7Y4F46K)
[languageServer.log](https://pastebin.com/tLYzvKzQ)

[Project Source](https://github.com/jlfarris91/TheLastStand)

**Comment by Frotty** [comment]
Logs and a self contained example to reproduce the problem, as the issue template states.

**Comment by jlfarris91** [comment]
Updated. Sorry, it was late.

**Comment by jlfarris91** [comment]
I sorted this out. Will update with the details I discovered.
