### ISSUE TITLE
Unknown format runtime exception when running Reforged map

### ISSUE THREAD

**Issue by Thorminator** [wurstscript/WurstScript#906]
I'm trying to build a simple map made in the Reforged editor. I just used the basic hello world project and added some neutrals.

In order to get it to compile I extracted the blizzard.j and common.j scripts from my game files and added a '-noPJass' argument to 'wurst_run.args', as PJass was not recognizing some of the new Reforged natives. Now the map seems to build and compile, but it still cannot run.

When using the 'runmap' command I get the following exception at the apply map config step: 

Exception occurred 
java.lang.RuntimeException: 
unknown format 31
supported formats:
-1
28
25
18

[Compile log](https://pastebin.com/Ub4FgvUx)
[Langauge server log ](https://pastebin.com/zHTEhZjL)

EDIT: Attached .w3i file as requested. Zipped to match required format.
[war3map.zip](https://github.com/wurstscript/WurstScript/files/3855436/war3map.zip)

**Comment by Frotty** [comment]
-> don't use the reforged editor to save the map you input into wurst.

**Comment by Frotty** [comment]
Please try again with latest build.

**Comment by Frotty** [comment]
Ok we have confirmed that reforged editor maps run now 👍
