### ISSUE TITLE
Implicit newlines in object data are not converted.

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#909]
I'm moving an old map to Wurst. All the objects don't use in their descriptions new line `|n`
<details><summary>Screenshots</summary>

![Screenshot_27](https://user-images.githubusercontent.com/19322847/70918235-3bb20000-2038-11ea-82bf-7801d822d731.png)

![Screenshot_24](https://user-images.githubusercontent.com/19322847/70918011-cd6d3d80-2037-11ea-9865-60145706e307.png)

</details>

Compilation with Wurst messes it up

<details><summary>Screenshot</summary>

![Screenshot_23](https://user-images.githubusercontent.com/19322847/70918708-f3dfa880-2038-11ea-9ba8-411226573adf.png)

</details>

**Comment by Frotty** [comment]
Upload the corresponding .w3a file to reproduce the issue.
Also paste the output of that ability from the `_build\objectEditingOutput\WurstExportedObjects_w3a.wurst.txt` file.

**Comment by GetLocalPlayer** [comment]
It's a unit in this case

[Built war3map.w3u](https://github.com/wurstscript/WurstScript/files/3968880/war3map.zip)

<details><summary>WurstExportedObjects_w3u.wurst.txt</summary>

```
@compiletime function create_w3u_E000()
	let def = createObjectDefinition("w3u", 'E000', 'Ekee')
	/*
		Unnecessary fields are skipped
	*/
	..setString("utub", "Divine energy that restores health to the allies in a target area dealing damage, equal to halved healing, to the enemies.|cffc3dbffHealing:|r <A02S,HeroDur1>/<A02S,HeroDur2>/<A02S,HeroDur3>/<A02S,HeroDur4>/<A02S,HeroDur5>|cffc3dbffCooldown:|r <A02S,Cool1>s|cffc3dbffManacost:|r <A02S,Cost1>/<A02S,Cost2>/<A02S,Cost3>/<A02S,Cost4>/<A02S,Cost5>")
	..setString("utip", "Holy Light")
	..setString("unam", "Holy Light")
	..setInt("ubpy", 0)
	..setString("uico", "ReplaceableTextures\\CommandButtons\\BTNHolyBolt.blp")
	..setInt("ubpx", 2)
```

</details>

**Comment by Frotty** [comment]
I need the original .w3u file of course...

**Comment by GetLocalPlayer** [comment]
The only you will find there is a TRIGSTR_XXX reference to a string in the .wts that wurst replaces with actual value. Do you still need it?

**Comment by Frotty** [comment]
I would have needed it, but I already found the issue, thanks. Implicit newlines were removed by wc3libs.
https://github.com/inwc3/wc3libs/commit/8f4185e50d00ced8b2154cc3aabf20249c13d95e fixes the issue.

**Comment by GetLocalPlayer** [comment]
Thanks.
