### ISSUE TITLE
createObjectDefinition always creates hero objects

### ISSUE THREAD

**Issue by kenkz447** [wurstscript/WurstScript#910]
I'm using **createObjectDefinition** to create new unit objects. But all object units in the output become heroes instead of normal units. Here is output files(w3o, txt):

[objectEditingOutput.zip](https://github.com/wurstscript/WurstScript/files/3988792/objectEditingOutput.zip)

**Comment by Frotty** [comment]
No it doesn't, read the doc: https://wurstlang.org/stdlib/unit_objed
Rawcodes starting with a capital letter are considered heroes. Also you shouldn't ever use `createObjectDefinition` manually.
