### ISSUE TITLE
i can't run a wurst map

### ISSUE THREAD

**Issue by mfishoy** [wurstscript/WurstScript#911]
I opened the Hello.wurst file according to the method in the tutorial, then I pressed the F1 key and used the run a wurst map command to select the ExampleMap.w3x file. Nothing is displayed on the screen (it's completely dark), you can only see the mouse. After pressing CTRL + ALT + DEL, war3.exe pops up an error message and ends the game.

**Comment by Frotty** [comment]
What was the problem?
