### ISSUE TITLE
1.26 Critical error

### ISSUE THREAD

**Issue by netVoix** [wurstscript/WurstScript#924]
Critical error when trying to run map or select map in wc3 menu with using wc3 1.26.

* Create new project
* Try to run compiled map on wc3 1.26 or just select compiled map in wc3 itself.

**Comment by Frotty** [comment]
As expected. The stdlib uses 1.30+ natives, which won't work on 1.26. Older patches are not automatically supported. If you want to build for them you need to:
- Provide 1.26 common.j / blizzard.j files and replace the ones in the _build folder
- Use the `pre1.29` stdlib branch in wurst.build `https://github.com/wurstscript/wurstStdlib2:pre1.29` (not maintained, contains bugs fixed on master)

**Comment by netVoix** [comment]
It worked before (didn't throw crit error), but now it works only with pre1.29 branch. =( Thanks.

**Comment by Frotty** [comment]
What did you update? Compiler and stdlib? What does "before" mean exactly?

**Comment by netVoix** [comment]
Just compiler. I use fork of master stdlib which works well in 1.26 (not fully, only functional that i used) and when I updated the compiler it stopped working.

**Comment by netVoix** [comment]
Ok. I removed all breaking changes from stdlib master branch fork and now it works. Also maybe its not worked cause update project changed build file in unexpected way.

**Comment by Frotty** [comment]
could you be more specific on that? Make PR for stdlib?

**Comment by netVoix** [comment]
I just remove all 1.29+ stuff and replace some packages with the ones from pre1.29 branch. It works well for me, but i dont use all of the functionality of the lib and not sure that my fork works well in any cases.

**Comment by Frotty** [comment]
So the latest compiler works, it's just the stdlib?

**Comment by netVoix** [comment]
Yes. Now it works well with the latest version of compiler.

**Comment by Frotty** [comment]
Could you make a PR for the pre1.29 branch? 😄
