### ISSUE TITLE
Functional interface causes `let` warning

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#930]
This
```
interface Test
	function call()

init
	Test x = () ->
		skip
```

causes this

```
Constant local variables should be defined using 'let'.
```

**Comment by peq** [comment]
I see two options to fix this:

1. We could disable the warning when an explicit type is given.
2. We could allow the following syntax to define constant local variables with a given type:

    ```
	let Test x = () ->
		skip
    ```

    or:
    
    ```
	constant Test x = () ->
		skip
    ```

**Comment by Frotty** [comment]
3. Can we detect whether the type can be inferred to omit the warning?

**Comment by peq** [comment]
> Can we detect whether the type can be inferred to omit the warning?

I think only in these 2½ cases an expected type is required: 
 - function expressions (closures)
 - `null`
 - integer literals that are supposed to be reals, 

So probably it is enough to suppress the warning for closures.

Nevertheless there might be cases where you want to add a type for readability and not use `let` with an inferred type. So maybe we should also add option 1?

**Comment by Frotty** [comment]
> So probably it is enough to suppress the warning for closures.

agreed.

> Nevertheless there might be cases where you want to add a type for readability and not use let with an inferred type. So maybe we should also add option 1 or 2?

I think in most cases immutable local variables should not require an explicit type to be "readable". If I were to choose I would prefer 2.
The best solution imho would be displaying the type like intellij
![](https://i.imgur.com/sA4b5QM.jpg)
