### ISSUE TITLE
Does it support running map on macOS?

### ISSUE THREAD

**Issue by 634750802** [wurstscript/WurstScript#936]

**Comment by Frotty** [comment]
Has nothing to do with the extension.
In theory yes, but right now probably not, because osx versions were broken until reforged iirc.
You can try to provide the necessary information to have it added.

**Comment by 634750802** [comment]
Thanks for your replying.
I'm not using my Mac to play wc3, only writing and testing simple logic codes on it :)

As far as I know:
- The wc3 reforged is already released on macOS.
- There is no WorldEditor in wc3 bundle on macOS currently (Chinese version).

I could provide some help if you need, but I have very little knowledge about wc3 starter (both on win or mac).

By the way, wurst is really a brilliant project!

**Comment by Frotty** [comment]
Any update on this?
