### ISSUE TITLE
BlzCreateUnitWithSkin missing in latest patch?

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#942]

**Comment by jlfarris91** [comment]
Turns out that the blizzard.j and common.j files in my _build directory were out of date. I tried to update the project and the wurst compiler via the setup app and neither provided newer files. After manually deleting them and building the map, they were finally replaced with up-to-date versions.

**Comment by Frotty** [comment]
That's the normal workflow.
You can use older common.j files as people do targeting older patches.
Overwriting those would make no sense.
