### ISSUE TITLE
Main function missing map configuration calls

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#944]
I am working on setting up a build pipeline in circleci that will actually have wurst build the map, along with some automation I have set up to introduce some complicated features to my map. I am very aware that this is unsupported and sketchy territory but nevertheless I am interested in getting this pipeline to work.

Building this map locally works perfectly fine and the game plays exactly as expected. The map built by my circleci pipeline succeeds and loads fine by war3 but it does not work as expected in-game.

As far as I can tell the only _real_ dependency by the compiler on the war 3 exe is to get the version number in order to make decisions about how to load/save the map files. I did some sneaky registry business to point the compiler to my version of the exe which ultimately provides the compiler with the correct version number it expects and continues building the map to success. I have compared the compiler.log from my local build and the build machine build to see that they are more-or-less the same - minus path differences and war3map.j line counts that don't match but I'll get to that below.

The map built on a circleci machine loads perfectly fine in war3 and has all of my map logic but there is one issue: the camera is locked at the origin and cannot be moved by mouse or arrow keys. I compared the war3map.j resulting from a local build and the one from the map generated on the build machine and there is one big difference I spotted: the map configuration and initialization portion of the `main` function is missing on the version generated on the build machine. The camera bounds are never set up, among other things, which is why my camera cannot move and is locked to the value of (0,0).

```
call SetCameraBounds((-11520.0)+GetCameraMargin(CAMERA_MARGIN_LEFT),(-11776.0)+GetCameraMargin(CAMERA_MARGIN_BOTTOM),11520.0-GetCameraMargin(CAMERA_MARGIN_RIGHT),11264.0-GetCameraMargin(CAMERA_MARGIN_TOP),(-11520.0)+GetCameraMargin(CAMERA_MARGIN_LEFT),11264.0-GetCameraMargin(CAMERA_MARGIN_TOP),11520.0-GetCameraMargin(CAMERA_MARGIN_RIGHT),(-11776.0)+GetCameraMargin(CAMERA_MARGIN_BOTTOM))
call SetDayNightModels("Environment\\DNC\\DNCDalaran\\DNCDalaranTerrain\\DNCDalaranTerrain.mdl","Environment\\DNC\\DNCDalaran\\DNCDalaranUnit\\DNCDalaranUnit.mdl")
call SetWaterBaseColor(0,128,255,255)
call NewSoundEnvironment("Default")
call SetAmbientDaySound("DalaranRuinsDay")
call SetAmbientNightSound("DalaranRuinsNight")
call SetMapMusic("Music",true,0)
call H3()
call Rect(10912.0,-11616.0,11296.0,-10848.0)
call Rect(-320.0,-7648.0,-128.0,-7456.0)
call M3()
call V3()
call K3()
call N3()
call X3()
call InitBlizzard()
```

These lines, from my local build, are missing from the build machine build and, for example, there is no call to InitBlizzard() anywhere. _I know this is the cause: I added the lines to the broken war3map.j file manually, updated my map file via the MPQEditor and it worked as expected._

I have diff'd all files from the 2 builds of the map and the only difference is the war3map.j files and more or less these lines in the main function and the functions they call.

I've burned 2 days on this and I know I'm SO close to getting this pipeline to work. I'm wondering if anyone can think of any reason why this portion of the code would be missing. It clearly must be because of the build machine environment but I get no error messages and I'm out of ideas. I suspect I'm 1 step away from getting this to work.

Any help beyond "it's unsupported don't do it" would be greatly appreciated.

You can see my circleci pipeline here: https://app.circleci.com/pipelines/github/jlfarris91/TheLastStand

And my map project here: https://github.com/jlfarris91/TheLastStand

**Comment by jlfarris91** [comment]
If you investigate this you'll see a few nasty things I had to do in order to get this to work:

1. There is no wurst docker image for windows. I tried to make one myself but I would need to update to Windows 10 Pro first - which I intend to do, just not yet.
2. Lacking the docker image I needed to find another way to install wurst and the user account on the circleci machine doesn't seem to have permissions to call `wget` sooooo I just copied wurstsetup into my repo. Gross but it works.
3. I think could rip the PE headers off of the war3 exe for the compiler to read the version instead of including the actual war3 exe but you'll see that I did that for now just to see if I could get it to work.

**Comment by Frotty** [comment]
> I am very aware that this is unsupported and sketchy territory but nevertheless I am interested in getting this pipeline to work.

I don't see how. `grill build` was made exactly for this purpose, I don't understand what you're trying to do here nor what exactly the question is. Why aren't you using `grill build`?
Wc3 is not necessary to build a map, that is one of the key features of wurst.

**Comment by jlfarris91** [comment]
I do use `grill build` in the `Wurst Map Build` step of my pipeline. However, when I executed 'grill build' in my build job (**on a circleci build machine without war3 installed**) I got an exception:

```
Forwarded run arguments: ["build", "C:\\Users\\circleci\\project\\TheLastStand.w3x"]
? Grill warming up..
? Ready. Version: <1.3.4.1-jenkins-WurstSetup-143>
? Building project..
net.moonlightflower.wc3libs.port.NotFoundException
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.find(WinGameExeFinder.java:141)
	at net.moonlightflower.wc3libs.port.win.WinGameExeFinder.find(WinGameExeFinder.java:12)
	at net.moonlightflower.wc3libs.port.Finder.get(Finder.java:25)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.find(StdGameExeFinder.java:39)
	at net.moonlightflower.wc3libs.port.StdGameExeFinder.find(StdGameExeFinder.java:12)
	at net.moonlightflower.wc3libs.port.Finder.get(Finder.java:25)
	at de.peeeq.wurstio.utils.W3Utils.getWc3PatchVersion(W3Utils.java:26)
	at de.peeeq.wurstio.languageserver.ProjectConfigBuilder.apply(ProjectConfigBuilder.java:51)
	at de.peeeq.wurstio.Main.main(Main.java:162)
Build succeeded. Output file: <C:\Users\circleci\project\.\_build\TheLastStand.w3x>
compilation finished (errors: 0, warnings: 4)
?? Map has been built!
```

It's clear from the exception that wc3libs couldn't find the war3 exe on the build machine, of course because it wasn't there. I found the wc3libs repo and stepped through this to find that indeed the library was looking for the game exe by using the `HKCU:\Software\Blizzard Entertainment\Warcraft III\Program` registry key, which typically points to the war3 exe after installation. It uses the game exe to read the version number, in my case was `[1, 32, 3, 14857]`, into a GameVersion object. The GameVersion object is used many places to determine branching in save/load code. I managed to "fix" this exception by giving the lib what it wanted: I added the war3 exe to my repo and set that reg key to point to it. After that, the version printed in the `compiler.log` file was `[1, 32, 3, 14857]` as expected and matched my local build's version.

So, I thought I was done there. I expected that the war3map.j files from the local version and the build machine version would be identical - they were not. This is my question: **will you help me determine what is the cause of the differences in these 2 generated war3map.j files and what in the build machine env or setup could be causing this**

**Comment by Frotty** [comment]
The wc3libs exception doesn't matter. It is only printed and the build then completes with the default patch level which is 1.32. The whole "fix" is completely pointless, unless you want to target another patch.
If the map works when you build from vscode, it should work from `grill build`, which does the same. Perhaps you are missing the original war3map.j in your project.

**Comment by jlfarris91** [comment]
Okay that's good to hear, thanks. I will undo that fix.

> Perhaps you are missing the original war3map.j in your project.

Could it be that simple? I will give it a shot and let you know.

**Comment by jlfarris91** [comment]
That did the trick! Thanks, Frotty. I had excluded my war3map.j from git for some reason I can't remember.

**Comment by Frotty** [comment]
You're welcome. I suppose the war3map.j extraction should be added to build.
