### ISSUE TITLE
Wurst.build cannot start loadingScreen\text options with a color string

### ISSUE THREAD

**Issue by jlfarris91** [wurstscript/WurstScript#945]
Starting the loadingScreen text options with a color string is a syntax error

![image](https://user-images.githubusercontent.com/20465861/77443942-a649a900-6da8-11ea-81d6-50d0d2f916a8.png)

![image](https://user-images.githubusercontent.com/20465861/77444176-cc6f4900-6da8-11ea-9444-dbe6f56e84b6.png)

**Comment by Frotty** [comment]
Just wrap it inside quotes?

**Comment by jlfarris91** [comment]
I wasn't aware you could do that. Might I suggest adding it to the build file documentation?

**Comment by Frotty** [comment]
The wurst.build file is simply [YAML](https://yaml.org/spec/)
