### ISSUE TITLE
Could we use wurst.build without vscode?

### ISSUE THREAD

**Issue by LazyKnightX** [wurstscript/WurstScript#946]
**Is your feature request related to a problem? Please describe.**
I want to make wurst.build process into my custom build pipeline, thus that I could distribute my modules into separate places on my disk, and easily work with online cooperators. (I have multiple cooperators for projects)
I didn't found out how to call wurst.build without visual studio code, could we call wurst.build using shells like .bat/.cmd or somethings?

**Describe the solution you'd like**
command like:
`{wurst}\wurstscript.jar --build "x:\wurst_projects\crystalzone" "x:\wurst_projects\crystalzone\map.w3x"`

**Extra**
Well, I found https://github.com/wurstscript/WurstScript/issues/946#issue-590729129 , but it seems there is nothing mentioned on wurstlang.org or docs? Please tell me where I could find the document about this feature.
Thanks in advance.

**Comment by LazyKnightX** [comment]
https://github.com/wurstscript/WurstScript/issues/550

**Comment by LazyKnightX** [comment]
Finally, I found wurstscript.exe.
The problem solved.

**Comment by Frotty** [comment]
Just do `grill install` ?!
Read the setup guide.

**Comment by LazyKnightX** [comment]
> Just do `grill install` ?!
> Read the setup guide.

No, the setup guide does not solve this problem. Actually I'm going to build the project with existing wurst codes. Like call the wurst.build in command-line, thus that I could make my building pipeline without vscode.

For example, I could use things like **gulp**, assign my custom compiling parameters, using the specific files as the language source, then assign those language content into my script, then I could easily build an English edition and other language edition.

Setup guide tell how to create the project, not build it to warcraft .w3x file.
I didn't fully understand how wurstscript.exe does the work, later I'm try diving into the source code.
:/

**Comment by Frotty** [comment]
Sigh, this has been working for a long time, just checkout existing projects or the docker image https://github.com/wurstscript/docker-wurst
`grill build` builds the project just like vscode would with buildMap.
`wurstscript.exe` does nothing, it is a native executable wrapper for wurstscript .jar
