### ISSUE TITLE
RELEASE constant?

### ISSUE THREAD

**Issue by GetLocalPlayer** [wurstscript/WurstScript#949]
There are pieces of code I would like to ignore during testing with "Run map" command like the abilities' resources preload or different values for my compiletime constants (e.g. max ability level). That would significantly reduce build/loading time.

**Comment by Frotty** [comment]
Nothing stops you from using your own constant or annotation to solve this

**Comment by Frotty** [comment]
Of course a flag in MagicFunctions could help make this less manual.
I think this could be part of the build config rework (patch target, multiple outputs), which seems a bit far away though.
