### ISSUE TITLE
increase timeout exception time for testruns

### ISSUE THREAD

**Issue by Krypt0n** [wurstscript/WurstScript#956]
https://github.com/wurstscript/WurstScript/blob/53728206d7ffb32764ad2aafb2cf0cb55d60a984/de.peeeq.wurstscript/src/main/java/de/peeeq/wurstio/languageserver/requests/RunTests.java#L201

Can we give this a higher timeout, or even a configurable timeout?
Cause I want to run several batched tests which will take way more time.
Also I think on slower CPUs this would be very neat. As we now Java is not the fasted train.

**Comment by Frotty** [comment]
> or even a configurable timeout?

PR ?

**Comment by Krypt0n** [comment]
Did not create any, cause i wanted to check firstly, if that is the right spot, and do not want to mess up anything, even tho it seems to work when change the value and compile with that, I placed 300s instead of the 20s tho.

**Comment by Frotty** [comment]
You can now use the vscode setting `wurst.testTimeout` or the runArg `-testTimeout` to set a custom value.
