### ISSUE TITLE
Command 'wurst: Run a Wurst map' resulted in an error (Internal error.)

### ISSUE THREAD

**Issue by goldenravioli** [wurstscript/WurstScript#961]
Had Wurst working a few months ago. On a new install, I try to run the generic hello.wurst. I get internal error with run and build.
VSCode output is blank. I removed the space from my username, but that didn't help either.

I have changed the wc3 path in VSCode settings to .../_retail_/... to no effect.

`Caused by: java.lang.Exception: tried: [Warcraft III.exe, Frozen Throne.exe, war3.exe, x86\Warcraft III.exe, x86_64\Warcraft III.exe]
	... 25 common frames omitted
2020-07-24 15:31:02 [pool-1-thread-1] INFO  languageServer - Game Executable from path: Optional.empty 
2020-07-24 15:31:02 [pool-1-thread-1] INFO  languageServer - Parsed custom game version from executable: Optional.empty 
2020-07-24 15:31:02 [pool-1-thread-1] WARN  languageServer - The provided wc3 path wasn't suitable. Falling back to discovery. 
`

**Comment by goldenravioli** [comment]
I have resolve the issue. Opened the Wurst GUI installer and changing the WC3 install path there.
Things that did not work: changing install path in vscode settings; changing install path in vscode .json edit; changing install path manually through the .vscode/.wurst/.json.
Things that did work: Changing install path through Wurst Installer GUI.

**Comment by Frotty** [comment]
> Things that did not work: changing install path in vscode settings;

Then you specified it incorrectly, because that is what the setup does.
