### ISSUE TITLE
AutoComplete Bug?

### ISSUE THREAD

**Issue by tester1101** [wurstscript/WurstScript#967]
![GIF](https://user-images.githubusercontent.com/57724590/95790990-6386f880-0d1b-11eb-999f-9d4360778dfc.gif)

**Describe the bug**
autocomplete didn't show list?

 * Include the steps required to reproduce the bug (e.g. a small code example or a link to your project code)
 1.make new project. e.g. named as Hello
 
 2. write as below
 
 pakage Hello
 constant MyCoNsTaNt = "string"
 init
 
 3.
 3-1.[ first line of flashEffect (this is bug)]
 input fl, then you can see autocomplete lists.
 press 'enter'
 then fl is autocompleted as flashEffect(path, pos)
 and path is highlighted.
 input 'myconstant', then normally MyCoNsTaNt must be shown. but it's not.
 
 3-2. [second line of flashEffect ]
 input fl and press 'enter' as 3-1 above.
 then fl is autocompleted as flashEffect(path, pos)
 and path is highlighted.
 now, input 'backspace' and 'right arrow' and 'left arrow'.
 input myconstant, you can see MyCoNsTaN appears when only you input "my" and this is what I originally wanted.

**Comment by Frotty** [comment]
Yea seems bit iffy. Btw you can always use ctrl+space to show completions.

**Comment by tester1101** [comment]
Ok, then I temporarily adapt using ctrl+space.
I hope this bug will be fixed later..

I attatched new code for showing why I want it to be fixed.

`
package example

function write_this_with_auto_completing(int i) returns int
	return 0

function this_is_function_1(int i) returns int
	return 0

function this_is_next_function_nested(int i) returns int
	return 0

function you_can_recognize_how_much_uncomfortable_this_problem_is() returns int
	return 0

init
	write_this_with_auto_completing(this_is_function_1(this_is_next_function_nested(you_can_recognize_how_much_uncomfortable_this_problem_is())))
`

**Comment by peq** [comment]
This is a builtin behavior in Vscode that the Wurst plugin cannot control directly.
You can change it by setting the Vscode option `editor.suggest.snippetsPreventQuickSuggestions` to false.

See https://github.com/microsoft/vscode/issues/107742#issuecomment-701181250 for more details
