### ISSUE TITLE
Unit tests do not generate output in VS Code

### ISSUE THREAD

**Issue by dani906** [wurstscript/WurstScript#983]
I can't get the unit tests to work and I don't know why. The *console simply does not show anything* when I run any test, does not matter which one I run. Sorry, if this is not the right place to ask for help, I just started with wurst.

EDIT: I run the tests like described [here](https://wurstlang.org/blog/bestofthewurst4.html)

Thanks in advance!

![image](https://user-images.githubusercontent.com/77580931/104944636-c7bef580-59b7-11eb-80fe-1359270c5e2a.png)

**Comment by Frotty** [comment]
Did you select the correct output ? 
![image](https://user-images.githubusercontent.com/1486037/104966720-efc34e80-59e1-11eb-8c2c-9a31539d7871.png)

**Comment by dani906** [comment]
That simply fixed it! Thank very much frotty!
