### ISSUE TITLE
war3.exe FATAL ERROR!

### ISSUE THREAD

**Issue by isaced** [wurstscript/WurstScript#987]
I use vscode to run WurstBareboneTemplate, start the game by extension "wurst: run a wurst map", build success, then game crash directly, I don't know why?

![image](https://user-images.githubusercontent.com/2088605/109380718-848a6780-7911-11eb-860f-d4f18d6536a5.png)

this is my WurstSetup version:

![image](https://user-images.githubusercontent.com/2088605/109380932-5e18fc00-7912-11eb-9b30-037cd4b8a88c.png)

> war3 1.27

thanks for help

**Comment by Frotty** [comment]
The master branch of the standard library uses new natives, you need to use the pre1.29 branch if you want to build for earlier wc3 versions.

**Comment by isaced** [comment]
@Frotty  Thank you very much for your reply. I tried the pre1.29 branch to work.

However, some fatal errors are encountered in the pre1.29 branch, which will lead to compilation failure. **Can I submit PR to pre1.29**?

For example:

https://github.com/wurstscript/WurstStdlib2/blob/8966dd98178aa8c64a99229c68888c412eb2ff86/wurst/data/LinkedList.wurst#L108

```
/** Removes the element and it's entry at the given index */
function removeAt(int index) returns T
    let entry = getEntry(index)
    entry.prev.next = entry.next
    entry.next.prev = entry.prev
    destroy entry	
    size--
    return entry.elem    //  will catch null after "destroy entry" 
```

**Comment by Frotty** [comment]
> However, some fatal errors are encountered in the pre1.29 branch, which will lead to compilation failure. Can I submit PR to pre1.29?

Sure, I didn't actively maintain it. The compiler error was introduced after the branch was made.
